import { RECLAIM_HYBRID_REFERENCE_USD, RECLAIM_HYBRID_SLIPPAGE_BPS } from "@/config/reclaimHybridStrategy";

export const BOT_CONFIG = {
  LOOP_MS: 3500,
  MAX_PARALLEL_QUOTES: 6,

  ROUTE_COMPARE: {
    MIN_SWITCH_EDGE_BPS: 10,
    MIN_SWITCH_EDGE_USD_SMALL: 0.03,
  },

  ARBITRAGE: {
    SMALL_WALLET_MAX_USD: 50,
    MAX_TRADE_USD_SMALL: 12,
    MIN_NET_PROFIT_USD: 0.12,
    MIN_NET_PROFIT_PCT: 0.35,
    MAX_GAS_SHARE_PCT: 18,
    MAX_PRICE_IMPACT_PCT: 1.2,
  },

  REFERENCE_USD: {
    BNB: RECLAIM_HYBRID_REFERENCE_USD.BNB,
    USDT: RECLAIM_HYBRID_REFERENCE_USD.USDT,
    USDC: RECLAIM_HYBRID_REFERENCE_USD.USDC,
    USD1: RECLAIM_HYBRID_REFERENCE_USD.USD1,
    ETH: RECLAIM_HYBRID_REFERENCE_USD.ETH,
    SOL: RECLAIM_HYBRID_REFERENCE_USD.SOL,
    AVAX: RECLAIM_HYBRID_REFERENCE_USD.AVAX,
    LINK: RECLAIM_HYBRID_REFERENCE_USD.LINK,
    DAI: 1,
    FDUSD: 1,
    BUSD: 1,
  },

  LANE_A: {
    MIN_PNL_PCT: 0.25,
    SIZE_PCT: 3.0,
    MIN_USD: 15,
    MAX_USD: 120,
    MEV_MARGIN_PCT: 0.15,
    FAILURE_BUFFER_PCT: 0.1,
  },

  LANE_B: {
    MIN_PNL_PCT: 0.9,
    SIZE_PCT: 1.5,
    MIN_USD: 10,
    MAX_USD: 60,
    MEV_MARGIN_PCT: 0.6,
    FAILURE_BUFFER_PCT: 0.1,
  },

  SLIPPAGE: {
    AVAX_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.AVAX_USDT,
    BNB_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.BNB_USDT,
    ETH_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.ETH_USDT,
    LINK_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.LINK_USDT,
    SOL_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.SOL_USDT,
    USDC_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.USDC_USDT,
    USD1_USDT: RECLAIM_HYBRID_SLIPPAGE_BPS.USD1_USDT,
    AVAX_USDC: 90,
    AVAX_USD1: 95,
    BNB_USDC: 45,
    BNB_USD1: 55,
    ETH_USDC: 65,
    ETH_USD1: 70,
    LINK_USDC: 85,
    LINK_USD1: 90,
    SOL_USDC: 85,
    SOL_USD1: 90,
    WLFI_USD1: 150,
    ASTER_USD1: 150,
  },

  ENABLE_BSC: true,
  ENABLE_CROSS_CHAIN: false,

  STOP_LOSS_MOVING_SUM_PCT: -1.0,
  WIN_LOSS_SAMPLES: 10,
  COOLDOWN_MS_DRAWDOWN: 30 * 60 * 1000,
  LANE_B_STOP_LOSES: 3,
  COOLDOWN_MS_LANE_B: 60 * 60 * 1000,
} as const;
