module.exports = {
  apps: [
    {
      name: "ai-dex-manager",
      cwd: "/home/deploy/ai-dex-manager",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1200M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
    },
    {
      name: "auto-trade-scheduler",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/auto-trade-scheduler.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "160M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "pengu-strong-scheduler",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/pengu-strong-scheduler.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "160M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "inj-spring-scheduler",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/inj-spring-scheduler.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "180M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "live-decision-cache-touch",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/live-decision-cache-touch-scheduler.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "80M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "runtime-cache-prune",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/runtime-cache-prune-scheduler.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "80M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "telegram-poller",
      cwd: "/home/deploy/ai-dex-manager",
      script: "scripts/telegram-poller.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
