import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureResidentStop, residentStopPlan, type ResidentStopGateway, type ResidentStopOrder } from '../lib/venue-resident-stop';
const position={strategy:'PENGU' as const,symbol:'PENGUUSDT',side:1 as const,entryTs:1000,entryPrice:10,quantity:3,stopFraction:.08};
function fixture(){const orders:ResidentStopOrder[]=[];let placements=0,cancels=0;const gateway:ResidentStopGateway={normalize:async p=>p,openOrders:async()=>orders,place:async p=>{placements++;const o={...p,status:'NEW',executedQuantity:0,averagePrice:0,orderId:42};orders.push(o);return o;},getOrder:async(_,id)=>orders.find(o=>o.clientOrderId===id)!,cancel:async()=>{cancels++;}};return{orders,gateway,counts:()=>({placements,cancels})};}
test('uses actual quantity/average and original stop fraction for both sides',()=>{assert.ok(Math.abs(residentStopPlan(position).stopPrice-9.2)<1e-12);assert.equal(residentStopPlan({...position,side:-1}).stopPrice,10.8);assert.equal(residentStopPlan(position).quantity,3);assert.equal(residentStopPlan(position).reduceOnly,true);assert.throws(()=>residentStopPlan({...position,quantity:0}));});
test('requires read-back, then restart adopts same stop without placing twice',async()=>{const f=fixture();const p=await ensureResidentStop(f.gateway,position,undefined,2000);assert.equal(p.protected,true);assert.equal(p.orderId,42);await ensureResidentStop(f.gateway,position,p,3000);assert.deepEqual(f.counts(),{placements:1,cancels:0});});
test('acknowledgement without read-back is never protected',async()=>{const f=fixture();f.gateway.openOrders=async()=>[];await assert.rejects(ensureResidentStop(f.gateway,position,undefined,2000),/READ_BACK/);});
test('timeout after accepted order reconciles on next invocation without duplicate',async()=>{const f=fixture(),place=f.gateway.place;f.gateway.place=async p=>{await place(p);throw Error('timeout');};await assert.rejects(ensureResidentStop(f.gateway,position,undefined,2000),/timeout/);const p=await ensureResidentStop(f.gateway,position,undefined,3000);assert.equal(p.protected,true);assert.equal(f.counts().placements,1);});
for(const field of ['side','quantity','stopPrice','reduceOnly','status'] as const)test(`invalid ${field} read-back fails closed`,async()=>{const f=fixture();const place=f.gateway.place;f.gateway.place=async p=>{const o=await place(p);Object.assign(o,{[field]:field==='side'?'BUY':field==='quantity'?2:field==='stopPrice'?9:field==='reduceOnly'?false:'UNKNOWN'});return o;};await assert.rejects(ensureResidentStop(f.gateway,position,undefined,2000));assert.equal(f.counts().cancels,0);});
test('duplicate protection rejects without cancelling a valid stop',async()=>{const f=fixture();const p=residentStopPlan(position);f.orders.push({...p,status:'NEW',executedQuantity:0,averagePrice:0,orderId:1},{...p,clientOrderId:'pengu-stop-aaaaaaaaaaaaaaaaaaaaaa',status:'NEW',executedQuantity:0,averagePrice:0,orderId:2});await assert.rejects(ensureResidentStop(f.gateway,position,undefined,2000),/DUPLICATE/);assert.deepEqual(f.counts(),{placements:0,cancels:0});});
test('quantity reduction verifies replacement before cancelling prior protection',async()=>{const f=fixture();const old=await ensureResidentStop(f.gateway,position,undefined,2000);const events:string[]=[];const place=f.gateway.place;f.gateway.place=async p=>{events.push('place');return place(p);};f.gateway.openOrders=async()=>{events.push('read');return f.orders;};f.gateway.cancel=async (_,id)=>{events.push('cancel');f.orders.splice(f.orders.findIndex(o=>o.clientOrderId===id),1);};const p=await ensureResidentStop(f.gateway,{...position,quantity:2},old,3000);assert.equal(p.quantity,2);assert.ok(events.indexOf('read',events.indexOf('place'))<events.indexOf('cancel'));assert.equal(f.orders.length,1);});
test('partially filled resident stop is retained for exact remaining quantity',async()=>{const f=fixture();const old=await ensureResidentStop(f.gateway,position,undefined,2000);f.orders[0].status='PARTIALLY_FILLED';f.orders[0].executedQuantity=1;const p=await ensureResidentStop(f.gateway,{...position,quantity:2},old,3000);assert.equal(p.clientOrderId,old.clientOrderId);assert.equal(p.quantity,2);assert.equal(f.counts().placements,1);assert.equal(f.counts().cancels,0);});
