#!/usr/bin/env python3
"""High-vol scanner v2 with a reserved PENGU slot and forward evidence gate.

This script post-processes candidates generated by
run_high_vol_scanner_portfolio_v1.py. PENGU is never filtered or loosened.
Satellites must pass both their trailing-180-day rule evidence and a completed
forward-candidate warm-up before they can use the separate scanner slot.

Research only. No live or automatic paper activation.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import run_high_vol_scanner_portfolio_v1 as hv
import run_pengu_adaptive_72h_v2 as core

TRAILING_MIN_TRADES = 6
TRAILING_MIN_WIN_RATE = 0.65
TRAILING_MIN_PROFIT_FACTOR = 1.50
TRAILING_MIN_EXPECTANCY = 0.015
FORWARD_WARMUP_CLOSED_TRADES = 5
FORWARD_MIN_WIN_RATE = 0.60
FORWARD_MIN_PROFIT_FACTOR = 1.20
CORRELATION_CAP = 0.80
NOTIONAL_PER_SLOT = 0.15


def safe_number(value: Any, default: float = 0.0) -> float:
    try:
        result = float(value)
        return result if math.isfinite(result) else default
    except (TypeError, ValueError):
        return default


def satellite_trailing_gate(row: dict[str, Any]) -> bool:
    metrics = row.get("trailing_metrics") or {}
    return (
        int(metrics.get("trades", 0) or 0) >= TRAILING_MIN_TRADES
        and safe_number(metrics.get("win_rate")) >= TRAILING_MIN_WIN_RATE
        and safe_number(metrics.get("profit_factor")) >= TRAILING_MIN_PROFIT_FACTOR
        and safe_number(metrics.get("expectancy")) >= TRAILING_MIN_EXPECTANCY
    )


def forward_evidence(
    all_candidates: list[dict[str, Any]],
    symbol: str,
    entry_time: pd.Timestamp,
) -> dict[str, Any]:
    completed = [
        row
        for row in all_candidates
        if row["symbol"] == symbol
        and pd.Timestamp(row["exit_time"]) < entry_time
    ]
    returns = np.asarray([safe_number(row.get("net_return")) for row in completed], dtype=float)
    if len(returns) == 0:
        return {
            "closed_trades": 0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "compound_return": 0.0,
            "passed": False,
        }
    winners = returns[returns > 0]
    losers = returns[returns <= 0]
    negative_sum = float(losers.sum())
    win_rate = float((returns > 0).mean())
    profit_factor = float(winners.sum() / -negative_sum) if negative_sum < 0 else 999.0
    compound_return = float(np.prod(1.0 + returns) - 1.0)
    passed = (
        len(returns) >= FORWARD_WARMUP_CLOSED_TRADES
        and win_rate >= FORWARD_MIN_WIN_RATE
        and profit_factor >= FORWARD_MIN_PROFIT_FACTOR
        and compound_return > 0.0
    )
    return {
        "closed_trades": int(len(returns)),
        "win_rate": win_rate,
        "profit_factor": profit_factor,
        "compound_return": compound_return,
        "passed": passed,
    }


def eligible_candidates(all_candidates: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    eligible: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    for source in all_candidates:
        row = dict(source)
        row["entry_time"] = pd.Timestamp(row["entry_time"])
        row["exit_time"] = pd.Timestamp(row["exit_time"])
        if row["symbol"] == "PENGU":
            row["admission"] = "PENGU_UNCHANGED"
            eligible.append(row)
            continue
        if not satellite_trailing_gate(row):
            row["admission_rejection"] = "TRAILING_180D_EVIDENCE_GATE"
            rejected.append(row)
            continue
        evidence = forward_evidence(all_candidates, row["symbol"], row["entry_time"])
        row["forward_evidence"] = evidence
        if not evidence["passed"]:
            row["admission_rejection"] = "FORWARD_WARMUP_GATE"
            rejected.append(row)
            continue
        row["admission"] = "SATELLITE_TWO_STAGE_PASS"
        eligible.append(row)
    return eligible, rejected


def reserved_slot_selection(
    candidates: list[dict[str, Any]],
    returns: dict[str, pd.Series],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped: dict[pd.Timestamp, list[dict[str, Any]]] = {}
    for row in candidates:
        grouped.setdefault(pd.Timestamp(row["entry_time"]), []).append(row)

    selected: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    active_pengu: list[dict[str, Any]] = []
    active_satellite: list[dict[str, Any]] = []

    for timestamp in sorted(grouped):
        active_pengu = [row for row in active_pengu if pd.Timestamp(row["exit_time"]) >= timestamp]
        active_satellite = [row for row in active_satellite if pd.Timestamp(row["exit_time"]) >= timestamp]
        same_hour = grouped[timestamp]

        # PENGU has its own slot and keeps its existing signal conditions.
        pengu_rows = sorted(
            [row for row in same_hour if row["symbol"] == "PENGU"],
            key=lambda row: safe_number(row.get("priority_score")),
            reverse=True,
        )
        for row in pengu_rows:
            if active_pengu:
                rejected.append({**row, "portfolio_rejection": "PENGU_SLOT_ALREADY_ACTIVE"})
            else:
                chosen = {**row, "slot": "PENGU", "portfolio_weight": NOTIONAL_PER_SLOT}
                selected.append(chosen)
                active_pengu.append(chosen)

        # Only one satellite can occupy the independent scanner slot.
        satellite_rows = sorted(
            [row for row in same_hour if row["symbol"] != "PENGU"],
            key=lambda row: safe_number(row.get("priority_score")),
            reverse=True,
        )
        for row in satellite_rows:
            if active_satellite:
                rejected.append({**row, "portfolio_rejection": "SATELLITE_SLOT_ALREADY_ACTIVE"})
                continue

            correlation_block = None
            for pengu in active_pengu:
                if int(row["side"]) != int(pengu["side"]):
                    continue
                correlation = abs(
                    hv.trailing_correlation(
                        returns,
                        row["symbol"],
                        "PENGU",
                        timestamp,
                    )
                )
                if correlation >= CORRELATION_CAP:
                    correlation_block = correlation
                    break
            if correlation_block is not None:
                rejected.append(
                    {
                        **row,
                        "portfolio_rejection": f"CORRELATED_WITH_ACTIVE_PENGU_{correlation_block:.3f}",
                    }
                )
                continue

            chosen = {**row, "slot": "SATELLITE", "portfolio_weight": NOTIONAL_PER_SLOT}
            selected.append(chosen)
            active_satellite.append(chosen)

    return selected, rejected


def exact_realized_metrics(selected: list[dict[str, Any]], return_field: str = "net_return") -> dict[str, Any]:
    if not selected:
        return {}
    frame = pd.DataFrame(
        {
            "exit_time": [pd.Timestamp(row["exit_time"]) for row in selected],
            "return": [safe_number(row.get(return_field)) * NOTIONAL_PER_SLOT for row in selected],
            "win": [safe_number(row.get(return_field)) > 0 for row in selected],
            "hold_hours": [int(row["hold_hours"]) for row in selected],
        }
    ).sort_values("exit_time")
    events = frame.groupby("exit_time")["return"].sum()
    equity = (1.0 + events).cumprod()
    drawdown = equity / equity.cummax() - 1.0
    monthly = (1.0 + events).resample("ME").prod() - 1.0
    winners = frame.loc[frame["return"] > 0, "return"]
    losers = frame.loc[frame["return"] <= 0, "return"]
    negative_sum = float(losers.sum())
    return {
        "trades": int(len(frame)),
        "total_return": float(equity.iloc[-1] - 1.0),
        "win_rate": float(frame["win"].mean()),
        "profit_factor": float(winners.sum() / -negative_sum) if negative_sum < 0 else 999.0,
        "realized_event_max_drawdown": float(drawdown.min()),
        "average_hold_hours": float(frame["hold_hours"].mean()),
        "average_month": float(monthly.mean()),
        "compound_month": float(equity.iloc[-1] ** (1.0 / 12.0) - 1.0),
        "positive_months": int((monthly > 0).sum()),
        "best_month": float(monthly.max()),
        "worst_month": float(monthly.min()),
    }


def load_market(cache: Path) -> tuple[dict[str, pd.DataFrame], dict[str, pd.Series]]:
    market: dict[str, pd.DataFrame] = {}
    returns: dict[str, pd.Series] = {}
    for symbol, exchange_symbol in hv.SYMBOLS.items():
        file = cache / f"{exchange_symbol}_1h_2024-12_2026-06.csv"
        data = pd.read_csv(file, parse_dates=["timestamp"]).set_index("timestamp").sort_index()
        if data.index.tz is None:
            data.index = data.index.tz_localize("UTC")
        market[symbol] = data
        returns[symbol] = data["close"].pct_change()
    return market, returns


def write_report(path: Path, payload: dict[str, Any]) -> None:
    hourly = payload["recommended"]["hourly_mark_to_market"]
    exact = payload["recommended"]["exact_realized"]
    stress = payload["recommended"]["hourly_stress"]
    lines = [
        "# High-Vol Scanner v2 — Reserved PENGU Slot + Forward Evidence",
        "",
        "Status: research only; real and automatic paper trading remain disabled.",
        "",
        "## Fixed overlap policy",
        "",
        "1. PENGU conditions are unchanged and PENGU has a dedicated 15% slot.",
        "2. The scanner has one separate 15% satellite slot; total standard gross is at most 30%.",
        "3. Open positions are never replaced merely because a later score is higher.",
        "4. Same symbol/same direction is one position only; never double notional.",
        "5. Same symbol/opposite direction is blocked; do not instant-reverse.",
        "6. Simultaneous satellite signals are ranked by trailing win rate, PF, expectancy, current move, ATR and volume.",
        "7. A satellite must have trailing-180d trades >=6, win rate >=65%, PF >=1.50 and expectancy >=1.5%.",
        "8. Before activation, a satellite also needs five completed forward candidates, forward win rate >=60%, PF >=1.20 and positive compounded return.",
        "9. A new satellite is rejected when an active same-direction PENGU position has absolute trailing-30d correlation >=0.80.",
        "10. A later PENGU signal is not blocked by an existing satellite; the PENGU slot was reserved for this purpose.",
        "",
        "## Recommended combined result",
        "",
        "| Metric | Result |",
        "|---|---:|",
        f"| Trades | {hourly.get('trades', 0)} |",
        f"| Win rate | {exact.get('win_rate', 0):.1%} |",
        f"| Profit factor | {exact.get('profit_factor', 0):.2f} |",
        f"| Total return | {hourly.get('total_return', 0):.2%} |",
        f"| Average month | {hourly.get('average_month', 0):.2%} |",
        f"| Compound month | {hourly.get('compound_month', 0):.2%} |",
        f"| Hourly mark-to-market max DD | {hourly.get('max_drawdown', 0):.2%} |",
        f"| Worst month | {hourly.get('worst_month', 0):.2%} |",
        f"| Average hold | {exact.get('average_hold_hours', 0):.1f}h |",
        "",
        "## Stress",
        "",
        f"At 10 bps/side and 5 bps/day reserve: total {stress.get('total_return', 0):.2%}, max DD {stress.get('max_drawdown', 0):.2%}, compound month {stress.get('compound_month', 0):.2%}.",
        "",
        "## Caveat",
        "",
        "The two-stage satellite thresholds were reviewed on this historical window. They are temporally valid within the simulation but are not an untouched independent discovery. Freeze them and collect new forward evidence before activation.",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", type=Path, required=True)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("research_outputs/high_vol_scanner_forward_gate_v2"))
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    raw_candidates = json.loads(args.candidates.read_text(encoding="utf-8"))
    for row in raw_candidates:
        row["entry_time"] = pd.Timestamp(row["entry_time"])
        row["exit_time"] = pd.Timestamp(row["exit_time"])

    market, hourly_returns = load_market(args.cache)
    admitted, admission_rejected = eligible_candidates(raw_candidates)
    selected, portfolio_rejected = reserved_slot_selection(admitted, hourly_returns)

    pnl, equity = hv.simulate_hourly_portfolio(
        selected,
        market,
        notional_per_position=NOTIONAL_PER_SLOT,
        cost_per_side=0.0006,
        funding_per_day=0.0002,
    )
    stress_pnl, stress_equity = hv.simulate_hourly_portfolio(
        selected,
        market,
        notional_per_position=NOTIONAL_PER_SLOT,
        cost_per_side=0.0010,
        funding_per_day=0.0005,
    )

    payload = {
        "status": "RESEARCH_ONLY_DISABLED",
        "parameters": {
            "pengu_conditions_changed": False,
            "pengu_slot": NOTIONAL_PER_SLOT,
            "satellite_slot": NOTIONAL_PER_SLOT,
            "trailing_min_trades": TRAILING_MIN_TRADES,
            "trailing_min_win_rate": TRAILING_MIN_WIN_RATE,
            "trailing_min_profit_factor": TRAILING_MIN_PROFIT_FACTOR,
            "trailing_min_expectancy": TRAILING_MIN_EXPECTANCY,
            "forward_warmup_closed_trades": FORWARD_WARMUP_CLOSED_TRADES,
            "forward_min_win_rate": FORWARD_MIN_WIN_RATE,
            "forward_min_profit_factor": FORWARD_MIN_PROFIT_FACTOR,
            "correlation_cap": CORRELATION_CAP,
        },
        "counts": {
            "raw_candidates": len(raw_candidates),
            "admitted_candidates": len(admitted),
            "admission_rejected": len(admission_rejected),
            "selected_trades": len(selected),
            "portfolio_rejected": len(portfolio_rejected),
            "selected_by_symbol": dict(Counter(row["symbol"] for row in selected)),
            "admission_rejections": dict(Counter(row["admission_rejection"] for row in admission_rejected)),
            "portfolio_rejections": dict(Counter(
                "CORRELATED_WITH_ACTIVE_PENGU" if row["portfolio_rejection"].startswith("CORRELATED_WITH_ACTIVE_PENGU") else row["portfolio_rejection"]
                for row in portfolio_rejected
            )),
        },
        "recommended": {
            "hourly_mark_to_market": hv.portfolio_metrics(pnl, equity, selected),
            "exact_realized": exact_realized_metrics(selected),
            "hourly_stress": hv.portfolio_metrics(stress_pnl, stress_equity, selected),
        },
    }
    payload = core.json_safe(payload)

    (args.output / "summary.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    pd.DataFrame(selected).to_json(args.output / "selected_trades.json", orient="records", indent=2)
    pd.DataFrame(admission_rejected).to_json(args.output / "admission_rejected.json", orient="records", indent=2)
    pd.DataFrame(portfolio_rejected).to_json(args.output / "portfolio_rejected.json", orient="records", indent=2)
    pd.DataFrame({"pnl": pnl, "equity": equity}).to_csv(args.output / "equity.csv")
    pd.DataFrame({"pnl": stress_pnl, "equity": stress_equity}).to_csv(args.output / "equity_stress.csv")
    write_report(args.output / "REPORT.md", payload)

    print("HIGH_VOL_SCANNER_FORWARD_GATE_V2=" + json.dumps(payload, separators=(",", ":")))
    print((args.output / "REPORT.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
