"use client";
import { RefreshCw, Wallet } from "lucide-react";
import { useOperationalWallet } from "@/hooks/useOperationalWallet";

export default function WalletsPage() {
  const { wallet, loading, refresh } = useOperationalWallet();
  const updatedAt = wallet?.lastAsterBalanceUpdatedAt ? new Date(wallet.lastAsterBalanceUpdatedAt).toLocaleString("ja-JP") : null;
  return <main className="space-y-4"><header className="panel-gold rounded-[30px] p-5 md:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.28em] text-gold-100/75"><Wallet className="h-4 w-4" />ウォレット／残高</div><h1 className="gold-heading mt-3 text-3xl font-black md:text-5xl">AsterDEX口座</h1><p className="mt-3 text-sm leading-7 text-white/75">AsterDEXの設定済み口座から、残高と資産をread-onlyで取得します。秘密鍵やAPI credentialは返しません。</p></header><section className="grid gap-3 md:grid-cols-4"><Metric title="Aster口座アドレス" value={wallet?.asterAccountAddress || "取得不能"} detail="サーバー側設定の公開アドレス" /><Metric title="Account balance" value={loading ? "読込中" : money(wallet?.lastAsterAccountBalanceUsd)} detail="Aster total wallet / margin balance" /><Metric title="Available balance" value={loading ? "読込中" : money(wallet?.lastAsterAvailableBalanceUsd)} detail="Aster account available balance" /><Metric title="取得時刻" value={updatedAt || "取得不能"} detail="stale・失敗時は明示表示" /></section><section className="panel-gold rounded-[30px] p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">資産内訳</h2><button type="button" onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs hover:bg-white/5"><RefreshCw className="h-4 w-4" />更新</button></div><div className="mt-4 space-y-2">{loading ? <Empty text="残高を取得しています。" /> : wallet?.trackedHoldings?.length ? wallet.trackedHoldings.map((holding) => <div key={holding.symbol} className="flex items-center justify-between rounded-2xl border border-white/10 px-4 py-3"><div><div className="font-semibold">{holding.symbol}</div><div className="text-xs text-white/50">{holding.name}</div></div><div className="text-right"><div>{holding.amount}</div><div className="text-xs text-white/60">{"$"}{Number(holding.usdValue || 0).toFixed(2)}</div></div></div>) : <Empty text={wallet ? "資産データがありません。" : "口座情報を取得できません。"} />}</div></section></main>;
}
function money(value: number | undefined) { return typeof value === "number" && Number.isFinite(value) ? `$${value.toFixed(2)}` : "取得不能"; }
function Metric({ title, value, detail }: { title: string; value: string; detail: string }) { return <div className="panel-gold rounded-[24px] p-4"><div className="text-xs text-white/55">{title}</div><div className="mt-2 break-all text-xl font-black">{value}</div><div className="mt-1 text-xs text-white/55">{detail}</div></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-white/10 px-4 py-8 text-center text-sm text-white/60">{text}</div>; }
