"use client";
import { Activity, ShieldCheck } from "lucide-react";
import { useOperationalWallet } from "@/hooks/useOperationalWallet";
import { DIST_TERMINAL_LIVE_CONFIG as config } from "@/lib/disterminal-live-config";
export default function PositionsPage() {
  const { wallet, loading } = useOperationalWallet();
  const rows = wallet?.trackedHoldings?.filter((entry) => Number(entry.amount) !== 0) ?? [];
  return <main className="space-y-4"><header className="panel-gold rounded-[30px] p-5 md:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.28em] text-gold-100/75"><Activity className="h-4 w-4" />LIVE状況／建玉</div><h1 className="gold-heading mt-3 text-3xl font-black md:text-5xl">V96 Crypto + V52 Stock</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/75">監視専用画面です。注文、決済、手動実行の操作は提供しません。</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-white/10 px-3 py-1.5">Executor: {config.executor}</span><span className="rounded-full border border-white/10 px-3 py-1.5">Execution Parity: VPS確認待ち</span><span className="rounded-full border border-white/10 px-3 py-1.5">Operator Override: VPS確認待ち</span></div></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info title="V96 Daily Loss" value="5%" /><Info title="V52 Daily Loss" value="3.5%" /><Info title="Portfolio最大Gross" value="1.0" /><Info title="PENGU初期Gross" value="0.15" /></section><section className="panel-gold rounded-[30px] p-5"><div className="flex items-center gap-2 font-bold"><ShieldCheck className="h-4 w-4 text-gold-100" />管理対象</div><p className="mt-2 text-xs text-white/60">Crypto: {config.cryptoSymbols.join(" / ")}</p><p className="text-xs text-white/60">Stock: {config.stockSymbols.join(" / ")}</p><div className="mt-5 space-y-2">{loading ? <Empty text="口座状態を読み込んでいます。" /> : rows.length ? rows.map((row) => <div key={row.symbol} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-3"><div><div className="font-bold">{row.symbol}</div><div className="text-xs text-white/55">{row.name}</div></div><div className="text-right"><div>{row.amount}</div><div className="text-xs text-white/60">${Number(row.usdValue || 0).toFixed(2)}</div></div></div>) : <Empty text={wallet ? "現在、表示できる建玉はありません。" : "口座状態を取得できません。"} />}</div></section><section className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4 text-sm leading-6 text-amber-100">Kill Switch、Daily Loss、状態整合性、Open Ordersは取引サービス側で管理されます。Web画面では取得できた最終状態だけを表示し、取得不能を稼働中とは表示しません。</section></main>;
}
function Info({ title, value }: { title: string; value: string }) { return <div className="panel-gold rounded-[24px] p-4"><div className="text-xs text-white/55">{title}</div><div className="mt-2 text-2xl font-black">{value}</div></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-white/10 px-4 py-8 text-center text-sm text-white/60">{text}</div>; }
