"use client";
import Link from "next/link";
import { ArrowRight, BarChart3, FileText, ShieldCheck, Wallet } from "lucide-react";
import { useOperationalWallet } from "@/hooks/useOperationalWallet";
function Card({ title, value, detail }: { title: string; value: string; detail: string }) { return <div className="panel-gold rounded-[24px] p-4"><div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-gold-100/70">{title}</div><div className="mt-2 text-2xl font-black text-white">{value}</div><div className="mt-1 text-xs leading-5 text-white/65">{detail}</div></div>; }
function formatUsd(value: number | undefined) { return typeof value === "number" && Number.isFinite(value) ? `$${value.toFixed(2)}` : "取得不能"; }
export default function HomePage() {
  const { wallet, loading } = useOperationalWallet();
  const balanceAt = wallet?.lastAsterBalanceUpdatedAt ? new Date(wallet.lastAsterBalanceUpdatedAt).toLocaleString("ja-JP") : null;
  const holdings = wallet?.trackedHoldings?.filter((holding) => Number(holding.amount) !== 0) ?? [];
  const links = [["/positions", "LIVE状況／建玉", "V96とV52の対象銘柄、リスク設定、取得状態", BarChart3], ["/wallets", "ウォレット／残高", "Aster口座残高と更新時刻", Wallet], ["/history", "トレード履歴", "実データの約定履歴と未決済状態", FileText], ["/performance", "成績・AI分析", "決済済み取引の統計と改善分析", ShieldCheck]] as const;
  return <main className="relative min-h-full overflow-hidden rounded-[28px] border border-gold-400/16 bg-[#03050a] p-3 text-white md:p-5"><div className="relative z-10 space-y-4">
    <section className="panel-gold rounded-[30px] p-5 md:p-8"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.28em] text-gold-100/75"><ShieldCheck className="h-4 w-4" />DISTerminal</div><h1 className="gold-heading mt-3 text-3xl font-black tracking-tight md:text-5xl">V96 Crypto + V52 Stock 統合LIVE</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/78">AsterDEXの現行LIVE構成を、監視・残高・履歴・分析のために表示します。画面から注文や決済は実行できません。</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full border border-emerald-400/25 bg-emerald-500/10 px-3 py-1.5 text-emerald-100">V96 Crypto / V52 Stock</span><span className="rounded-full border border-gold-400/20 bg-gold-400/10 px-3 py-1.5 text-gold-50">V96 Daily Loss 5%</span><span className="rounded-full border border-gold-400/20 bg-gold-400/10 px-3 py-1.5 text-gold-50">V52 Daily Loss 3.5%</span><span className="rounded-full border border-gold-400/20 bg-gold-400/10 px-3 py-1.5 text-gold-50">最大Gross 1.0 / PENGU 0.15</span></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="Aster口座残高" value={loading ? "読込中" : formatUsd(wallet?.lastAsterAccountBalanceUsd)} detail={balanceAt ? `最終更新: ${balanceAt}` : "取得不能時は0に置換しません"} /><Card title="利用可能残高" value={loading ? "読込中" : formatUsd(wallet?.lastAsterAvailableBalanceUsd)} detail="Aster account available balance" /><Card title="LIVE状態" value="最終確認待ち" detail="VPS実状態を取得できない場合はUNKNOWNとして表示" /><Card title="建玉" value={wallet ? String(holdings.length) : "取得不能"} detail="read-only account view" /></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{links.map(([href, title, detail, Icon]) => <Link key={href} href={href} className="group rounded-[22px] border border-gold-400/16 bg-black/20 p-4 transition hover:border-gold-300/40"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm font-bold text-white"><Icon className="h-4 w-4 text-gold-100" />{title}</span><ArrowRight className="h-4 w-4 text-gold-100/70 transition group-hover:translate-x-1" /></div><p className="mt-2 text-xs leading-5 text-white/65">{detail}</p></Link>)}</section>
  </div></main>;
}
