'use client';
import type {Dd1296Observation} from '@/lib/server/dd1296-observability';
const time=(t:number|null)=>t?new Date(t).toLocaleString('ja-JP'):'—';
export function Dd1296RuntimePanel({data,logic}:{data?:Dd1296Observation;logic?:string}){
 if(!data)return <p className="rounded-xl border border-amber-300/20 p-3 text-sm text-amber-100">DD12.96の実機観測を取得できません。</p>;
 const all=!logic||logic==='all'||logic==='overview';
 return <section className="panel-gold rounded-[28px] p-4 md:p-6 space-y-4 text-sm text-white/75"><h2 className="gold-heading text-lg font-bold">DD12.96 実機判定・損切り保護</h2><p className="text-xs break-all">Production SHA: {data.runtimeSha} / 観測 {time(data.checkedAt)}</p>
 {(all||logic==='q102')&&<div><h3 className="font-bold text-white">Q102 Family × Side Gross</h3><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Family</th><th>Side</th><th>Gross</th></tr></thead><tbody>{Object.entries(data.q102.familySideGross).flatMap(([family,sides])=>Object.entries(sides as Record<string,number>).map(([side,gross])=><tr key={family+side}><td>{family}</td><td>{side}</td><td>{gross.toFixed(2)}x</td></tr>))}</tbody></table></div>{data.q102.position&&<p>実state: {data.q102.position.family} {data.q102.position.side} / applied Gross {data.q102.position.appliedGross??"UNKNOWN"}x / qty {data.q102.position.quantity}</p>}<p>FET BRK SHORT: 72h return ≤ −12% → BLOCK</p>{data.q102.candidates.filter((r:any)=>r.selected||r.reason?.includes('EXHAUSTION')).map((r:any)=><p key={r.symbol}>{r.symbol} / {r.family||'—'} / {r.side} / applied Gross {r.appliedGross}x / {r.reason}</p>)}</div>}
 {(all||logic==='fet')&&<div><h3 className="font-bold text-white">FET 72h / 決済後24h</h3><p>72h return: {data.fet.return72h===null?'確定足の観測待ち':(data.fet.return72h*100).toFixed(3)+'%'} / 必須 ≥ +2% / {data.fet.gatePass===null?'UNKNOWN':data.fet.gatePass?'PASS':'BLOCK'}</p><p>Cooldown until: {time(data.fet.cooldownUntil)} / 残り {(data.fet.cooldownRemainingMs/3600000).toFixed(2)}h / {data.fet.cooldownPass?'PASS':data.fet.configured?'BLOCK':'UNKNOWN'}</p><p>{data.fet.lastEvaluationReason}</p></div>}
 {(all||logic==='v12')&&<div><h3 className="font-bold text-white">V12 Side別連敗・Gate</h3>{(['LONG','SHORT'] as const).map(side=>{const row=data.v12.sideLossLedger?.[side];return <p key={side}>{side}: {row?.losses??'UNKNOWN'}連敗 / Cooldown {time(row?.until)} / 残り {row?Math.max(0,(row.until-data.checkedAt)/3600000).toFixed(2):'—'}h</p>})}<p>AVAX Rank1 SHORT: BTC 3h &lt; 0、directional relative 3h ≤ −0.75% → BLOCK</p><p>ATOM: directional relative 3h ≥ +0.603% → BLOCK</p><p>AVAX Rank1 LONG: directional 24h ≤ +1.65% → BLOCK</p><p>最新判定: {data.v12.lastDecision?.symbol} {data.v12.lastDecision?.side} / {data.v12.lastDecision?.reason??'UNKNOWN'}</p>{data.v12.lastGateMetrics&&<p>実測: asset 3h {(data.v12.lastGateMetrics.asset3h*100).toFixed(3)}% / BTC 3h {(data.v12.lastGateMetrics.btc3h*100).toFixed(3)}% / relative {(data.v12.lastGateMetrics.directionalRelative3h*100).toFixed(3)}% / 24h {(data.v12.lastGateMetrics.directional24h*100).toFixed(3)}%</p>}</div>}
 {(all||logic==='v52')&&<p>V52: dynamic Basis Stop 1.75維持 / Entry reference固定の緊急STOP: DISABLED / Phase 2研究のみ</p>}
 <div><h3 className="font-bold text-white">取引所STOP read-back</h3><p>{data.protection.readBackStatus} / 最終照合 {time(data.protection.lastReconciledAt)} / 未保護 {data.protection.unprotectedCount??'UNKNOWN'}</p>{data.protection.fresh&&data.protection.positions.length===0&&<p>現在建玉なし</p>}{data.protection.positions.map((p:any)=><div key={p.symbol} className="rounded-xl border border-white/10 p-3 mt-2"><p>{p.strategy} {p.symbol} {p.positionSide} qty {p.quantity} / {p.protected===true?'protected':p.protected===null?'dynamic Basis Stop':'UNPROTECTED'}</p>{p.orders.map((o:any)=><p className="break-all text-xs" key={o.orderId}>Order {o.orderId} / {o.clientOrderId} / {o.side} reduce-only {String(o.reduceOnly)} / qty {o.quantity} / Stop {o.stopPrice} / {o.status}</p>)}</div>)}</div></section>;
}
