'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ArrowUp,ArrowDown,RefreshCw,Trophy,X } from 'lucide-react';
import Link from 'next/link';
import { executionBlocked,currentRankRow,rankRows,rankChanges,rankCommentary,type RankRow } from '@/lib/realtime-ranking';
import { SignalGateList } from './SignalGateList';
import { useRankingShow } from './useRankingShow';
type Snapshot={checkedAt:number;runtimeSha:string;rows:RankRow[];metric:string;errors:Record<string,string>};
function missing(row:RankRow){return row.gates.filter(g=>g.kind!=='execution'&&g.state!=='OK').map(g=>g.label+'：'+g.detail).join(' / ')||'市場条件通過。資金・競合はRunner確認待ち';}
function constraints(row:RankRow){return row.gates.filter(g=>g.kind==='execution'&&g.state==='NO').map(g=>g.label).join(' / ');}
function blockReason(row:RankRow){return row.gates.filter(g=>g.kind==='execution'&&g.state==='NO').map(g=>g.key==='clock'||g.label==='S34_4H_GRID'?'受付時間外':g.label==='FET保有・保留注文'?'保有・注文あり':g.label==='同時候補の選定'?'Runner選定未通過':g.label).join(' / ');}
function rankExplanation(row:RankRow,rows:RankRow[]){if(row.score===null)return '必要なデータ・判定が未確認のため順位対象外です。';const ahead=rows.filter(r=>r.score!==null&&!executionBlocked(r)).length;return executionBlocked(row)?'確認済みの発注制約があるため、制約NOのない'+ahead+'件より後に表示しています。この制約ありグループ内ではScore順です。発注停止理由：'+blockReason(row)+'。':'確認済みの発注制約NOがないグループ内でScore順に表示しています。資金・競合など未確認の条件はRunnerの最終判定が必要です。';}
function Movement({delta}:{delta?:number}){return delta===0?<span className="text-[9px] text-[#efd58c]">NEW</span>:delta?<span className={'inline-flex items-center text-[9px] '+(delta>0?'text-emerald-300':'text-rose-300')}>{delta>0?<ArrowUp size={10}/>:<ArrowDown size={10}/>} {Math.abs(delta)}</span>:null;}
export function RealtimeRankingBoard(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logic,setLogic]=useState('ALL'),[side,setSide]=useState('ALL'),[search,setSearch]=useState(''),[remaining,setRemaining]=useState(120),[changes,setChanges]=useState<Record<string,number>>({}),[flash,setFlash]=useState<Record<string,number>>({}),[selectedId,setSelectedId]=useState<string|null>(null);
 const prepareShow=useRef<(()=>void)|null>(null),rowNodes=useRef(new Map<string,HTMLElement>());
 const lastSnapshot=useRef(0);
 const previous=useRef<string[]>([]),requesting=useRef(false),alive=useRef(true),next=useRef(Date.now()+120000),flashTimer=useRef<ReturnType<typeof setTimeout>>(),dialog=useRef<HTMLDialogElement>(null);
 const load=useCallback(async()=>{if(requesting.current)return;requesting.current=true;setBusy(true);try{const res=await fetch('/api/system/realtime-ranking',{cache:'no-store'}),d=await res.json();if(!res.ok||!d.ok)throw Error(d.error||'取得失敗');if(!alive.current)return;if(typeof d.checkedAt!=='number'||!Number.isFinite(d.checkedAt)||d.checkedAt<lastSnapshot.current)throw Error('観測時刻が古いため更新を見送りました');lastSnapshot.current=d.checkedAt;const ids=d.rows.filter((r:RankRow)=>r.score!==null).map((r:RankRow)=>r.id),movement=rankChanges(previous.current,ids);previous.current=ids;setChanges(movement);setFlash(movement);if(flashTimer.current)clearTimeout(flashTimer.current);flashTimer.current=setTimeout(()=>setFlash({}),1200);prepareShow.current?.();setData(d);setError('');}catch(e){if(alive.current){setError(e instanceof Error?e.message:'取得失敗');setFlash({});}}finally{requesting.current=false;if(alive.current){setBusy(false);next.current=Date.now()+120000;setRemaining(120);}}},[]);
 useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>{setRemaining(Math.max(0,Math.ceil((next.current-Date.now())/1000)));if(Date.now()>=next.current)void load();},1000);return()=>{alive.current=false;clearInterval(timer);if(flashTimer.current)clearTimeout(flashTimer.current);};},[load]);
 const all=rankRows((data?.rows||[]).map(r=>currentRankRow(r,Date.now()))),filtered=all.filter(r=>(logic==='ALL'||r.logic===logic)&&(side==='ALL'||r.side===side)&&((r.symbol+' '+r.logic).toLowerCase().includes(search.toLowerCase()))),top=error?[]:filtered.filter(r=>r.score!==null&&!executionBlocked(r)).slice(0,3),selected=all.find(r=>r.id===selectedId);
 const show=useRankingShow(all,data?.checkedAt??0,logic+'|'+side+'|'+search,error);
 prepareShow.current=show.prepare;
 const commentRow=selected||all.find(r=>r.id===show.event?.row.id)||top[0];
 const commentary=commentRow?rankCommentary(commentRow,!selected&&show.event?.row.id===commentRow.id?show.event.from:undefined,!selected&&show.event?.row.id===commentRow.id?show.event.to:undefined):null;

 useEffect(()=>{if(selected&&dialog.current&&!dialog.current.open)dialog.current.showModal();else if(!selected&&dialog.current?.open)dialog.current.close();},[selected]);
 const showRowRef=(id:string,node:HTMLElement|null)=>{show.register(id,node);};
 const cell=(r:RankRow)=> <button key={r.id} type="button" id={'row-'+r.id} data-ranking-row={r.id} ref={node=>{showRowRef(r.id,node);}} onClick={()=>setSelectedId(r.id)} title={r.symbol+' / '+r.logic+' '+r.side+' / '+rankExplanation(r,all)+' / '+(constraints(r)||missing(r))} className={'rank-cell '+(show.highlights[r.id]!==undefined?'rank-flash ':'')+(error||!r.fresh?'rank-unknown':executionBlocked(r)?'rank-blocked':'rank-observed')}><span className="text-[#d9bd74]">{error?'—':r.rank??'—'}{show.highlights[r.id]>0&&<span className="rank-rise-number">↑{show.highlights[r.id]}</span>}</span><span className="flex min-w-0 items-center gap-1 font-semibold text-white"><span className="shrink-0">{r.symbol.replace(/USDT$/,'')}</span>{executionBlocked(r)&&<span className="truncate text-[8px] font-normal text-rose-300">{blockReason(r)}</span>}</span><span className="truncate text-[10px] text-[#d7be76]">{r.logic.replace('Idle Short','Idle S').replace('Idle Long','Idle L')}</span><span className={'text-[9px] '+(r.side==='LONG'?'text-emerald-300':r.side==='SHORT'?'text-rose-300':'text-white/35')}>{r.side==='LONG'?'Long':r.side==='SHORT'?'Short':'—'}</span><span className="text-right font-mono font-bold text-[#ead7a4]">{error||r.score===null?'—':r.score}</span></button>;
 return <div className="compact-radar">
  <header className="radar-heading"><div className="flex min-w-0 items-center gap-3"><h1 className="shrink-0 text-sm font-bold text-[#e9d9a0]">リアルタイム判定 Ranking</h1><span className="hidden truncate text-[10px] text-white/40 sm:block">{data?new Date(data.checkedAt).toLocaleTimeString('ja-JP'):'取得中'} · {data?.rows.length??'—'}ルート · 2分更新</span></div><button disabled={busy} onClick={()=>void load()} className="flex shrink-0 items-center gap-1 rounded-lg border border-[#a68948]/30 px-2 py-1 text-[10px] text-[#efdda7] disabled:opacity-50"><RefreshCw size={11} className={busy?'animate-spin':''}/>{busy?'更新中':'更新'} · {remaining}秒</button></header>
  {error&&<p role="alert" className="rounded-lg bg-rose-400/10 px-2 py-1 text-xs text-rose-200">{error}。前回観測を表示しています。</p>}
  {!!data&&Object.keys(data.errors).length>0&&<p role="status" className="text-[10px] text-amber-200">未確認：{Object.keys(data.errors).join(' / ')}</p>}
  <section aria-label="ランキング実況" className="ranking-commentary">
   <div className="ranking-commentary-copy" role="status" aria-live="polite" aria-atomic="true">
    <p className="ranking-commentary-title">{error?'更新失敗：前回の観測です':commentary?.headline||'ランキング実況 · 次の順位上昇を待っています'}</p>
    <p className="ranking-commentary-signal" title={error?'最新判定は未確認':commentary?.signal}>{error?'最新判定は未確認です。復旧後の観測を待っています。':commentary?.signal||'上昇した通貨と、不足している条件を実判定データからお知らせします。'}</p>
    <p className="ranking-commentary-execution" title={commentary?.execution}>{error?'発注可否は未確認です。':commentary?.execution||'通貨を選ぶと、条件不足と発注制約を確認できます。'}</p>
   </div>
   <div className="ranking-commentary-tools">
    <div className="ranking-commentary-toggles">{(['motion','sound','voice'] as const).map(key=><button type="button" key={key} aria-pressed={show[key]} onClick={()=>show.preference(key,!show[key])} className={show[key]?'ranking-toggle-on':''}>{key==='motion'?'動き':key==='sound'?'効果音':'読み上げ'} {show[key]?'ON':'OFF'}</button>)}</div>
    <button type="button" disabled={!commentRow} onClick={()=>commentRow&&setSelectedId(commentRow.id)} className="ranking-detail-button">不足条件をすべて見る →</button>
    <span className="ranking-audio-notice">{show.audioNotice||'自然AI音声を優先 · 未設定時は高品質な端末日本語音声へ自動切替'}</span>
   </div>
  </section>
  <div className="radar-filters"><input aria-label="通貨を検索" placeholder="通貨・ロジック検索" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1"/><select aria-label="ロジック" value={logic} onChange={e=>setLogic(e.target.value)}><option value="ALL">全ロジック</option>{[...new Set(data?.rows.map(r=>r.logic)||[])].map(v=><option key={v}>{v}</option>)}</select><select aria-label="方向" value={side} onChange={e=>setSide(e.target.value)}><option value="ALL">全方向</option><option>LONG</option><option>SHORT</option><option>WAIT</option></select></div>
  <section aria-label="上位3候補" className="radar-leaders">{top.map((r,i)=><button type="button" key={r.id} onClick={()=>setSelectedId(r.id)} className={'radar-leader '+(show.highlights[r.id]!==undefined?'rank-flash':'')}><div className="flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><Trophy size={12} className="shrink-0 text-[#d8bd75]"/><span className="text-[10px] text-[#d8bd75]">{i+1}</span><h2 className="truncate text-base font-bold text-white">{r.symbol.replace(/USDT$/,'')}</h2><span className="text-[10px] text-[#d8bd75]">{r.logic}</span><span className={'text-[10px] '+(r.side==='LONG'?'text-emerald-300':'text-rose-300')}>{r.side==='LONG'?'Long':'Short'}</span></div><div className="flex items-center gap-2"><Movement delta={changes[r.id]}/><b className="text-xl text-[#ead7a4]">{r.score}</b></div></div><div className="my-1.5 h-[2px] bg-white/10"><div className="h-full bg-[#d6b662]" style={{width:r.score+'%'}}/></div><p className="truncate text-[10px] text-white/50" title={missing(r)}>不足：{missing(r)}</p></button>)}{!top.length&&<p className="col-span-3 px-2 py-3 text-xs text-white/45">{!data?'Production観測を取得中…':'現在、確認済み発注制約のない候補はありません。全件は下の一覧で確認できます。'}</p>}</section>
  <section aria-label="全監視通貨・ロジック" className="radar-ranking"><div className="flex shrink-0 items-center justify-between gap-2 px-2 py-1"><h2 className="text-[11px] font-semibold text-white/80">発注制約優先の順位 · {filtered.length}件</h2><span className="truncate text-[9px] text-white/40" title={data?.metric}>赤＝発注制約 / 灰＝未評価 · 条件充足度（発火確率ではありません） · クリックで詳細</span></div><p className="shrink-0 px-2 pb-1 text-[10px] leading-tight text-[#dbc787]">順位：制約NOなし → 制約あり → 未評価。各グループ内はScore順。同点は固定ID順。Scoreは市場条件の充足度で、100でも受付時間・保有・Runner選定により発注できません。</p><div className="radar-columns">{[0,1,2].map(col=><div key={col} className="radar-column"><div className="rank-column-heading"><span>{col*15<filtered.length?String(col*15+1)+"–"+Math.min(col*15+15,filtered.length):"—"}</span><span>通貨</span><span>ロジック</span><span>方向</span><span>Score</span></div><div className="rank-column-body">{filtered.slice(col*15,col*15+15).map(cell)}</div></div>)}</div>{filtered.length>45&&<div className="radar-tail" aria-label="46位以降">{filtered.slice(45).map(cell)}</div>}{data&&!filtered.length&&<p className="p-3 text-xs text-white/45">該当する通貨はありません。</p>}</section>
  <dialog ref={dialog} aria-labelledby="rank-detail-title" onCancel={()=>setSelectedId(null)} className="rank-dialog">{selected&&<><div className="flex items-center justify-between gap-3 border-b border-white/10 p-4"><h2 id="rank-detail-title" className="text-lg font-bold text-[#ead7a4]">{selected.symbol.replace(/USDT$/,'')} · {selected.logic} · {selected.side}</h2><button autoFocus type="button" aria-label="詳細を閉じる" onClick={()=>setSelectedId(null)} className="rounded-lg border border-white/15 p-2 text-white"><X size={16}/></button></div><div className="overflow-y-auto p-4"><p className="mb-3 text-xs text-white/50">観測 {new Date(selected.checkedAt).toLocaleString('ja-JP')} ／ 順位 {error?'—':selected.rank??'対象外'} ／ Score {error?'更新失敗':selected.score??'未評価'}</p><p className="mb-3 rounded-lg border border-[#a68948]/30 bg-[#d6b662]/5 p-3 text-xs leading-relaxed text-[#ead7a4]">{error?'更新失敗：前回観測のため現在の順位・発注可否は未確認です。':rankExplanation(selected,all)}</p><p className="mb-3 text-xs text-[#dbc787]">{constraints(selected)||missing(selected)}</p><SignalGateList gates={error?selected.gates.map(g=>({...g,state:'UNKNOWN',detail:'更新失敗：前回観測'})):selected.gates}/>{selected.href&&<Link href={selected.href} className="mt-4 inline-block text-xs text-[#dbc787]">{selected.logic} 詳細ページ →</Link>}</div></>}</dialog>
  <style jsx global>{`

   .ranking-commentary{height:98px;flex-shrink:0;display:flex;gap:12px;align-items:center;padding:9px 12px;border:1px solid #c4ab5555;border-radius:12px;background:linear-gradient(110deg,#252315,#0b1520);position:relative}
   .ranking-commentary-copy{min-width:0;flex:1}.ranking-commentary-copy p{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;line-height:1.65}
   .ranking-commentary-title{color:#f2dfa2;font-size:12px;font-weight:700}.ranking-commentary-signal{color:#edf3f8;font-size:11px}.ranking-commentary-execution{color:#e2adac;font-size:10px}
   .ranking-commentary-tools{flex-shrink:0;display:flex;flex-direction:column;align-items:flex-end;gap:5px}.ranking-commentary-toggles{display:flex;gap:4px}.ranking-commentary-toggles button,.ranking-detail-button{font-size:10px;border:1px solid #ffffff25;border-radius:6px;padding:3px 6px;color:#bfc7d2}.ranking-commentary-toggles .ranking-toggle-on{color:#f3e3ac;border-color:#c7ab5c88;background:#c7ab5c12}.ranking-detail-button{color:#ead7a4}.ranking-detail-button:disabled{opacity:.4}.ranking-audio-notice{font-size:9px;color:#9aa6b5;max-width:270px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
   .rank-rise-number{font-size:8px;color:#9df2c1;font-weight:700;white-space:nowrap;display:block}.ranking-flyer .rank-rise-number{color:#c0ffd9}
   @media(max-width:767px){.ranking-commentary{height:128px;align-items:stretch;flex-direction:column;gap:4px;padding:8px 10px}.ranking-commentary-tools{display:grid;grid-template-columns:1fr auto;align-items:center;gap:3px}.ranking-audio-notice{grid-column:1/-1;max-width:none}.ranking-commentary-title{font-size:11px}.ranking-commentary-signal{font-size:10px}.ranking-commentary-execution{font-size:9px}}

   .compact-radar{height:100%;min-height:560px;display:flex;flex-direction:column;gap:6px}
   .radar-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-shrink:0;padding:5px 8px;border:1px solid #a6894833;border-radius:10px;background:#13140f}
   .radar-filters{display:flex;gap:5px;flex-shrink:0}.radar-filters input,.radar-filters select{height:26px;padding:2px 7px;border:1px solid #ffffff18;border-radius:7px;background:#090e16;color:#eee;font-size:10px}
   .radar-leaders{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;flex-shrink:0}
   .radar-leader{min-width:0;text-align:left;padding:9px 10px;border:1px solid #a78b4645;border-radius:12px;background:linear-gradient(140deg,#262116,#090e16 80%)}
   .radar-ranking{display:flex;flex-direction:column;flex:1;min-height:0;border:1px solid #ffffff16;border-radius:10px;background:#080d15;overflow:hidden}
   .radar-columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;flex:1;min-height:0;padding:0 5px 5px}
   .radar-column{display:flex;flex-direction:column;min-width:0;min-height:0;border:1px solid #ffffff0d;border-radius:6px;overflow:hidden}
   .rank-column-heading,.rank-cell{display:grid;grid-template-columns:21px minmax(0,1fr) 42px 28px 26px;align-items:center;gap:3px;padding:0 6px}
   .rank-column-heading{white-space:nowrap;height:21px;flex-shrink:0;color:#ffffff60;background:#ffffff05;font-size:9px}
   .rank-column-heading span:first-child{font-size:8px}.rank-column-body{display:grid;grid-template-rows:repeat(15,minmax(18px,1fr));flex:1;min-height:0}
   .rank-cell{min-width:0;min-height:0;width:100%;text-align:left;border-bottom:1px solid #ffffff0b;border-left:2px solid #a78b4640;font-size:clamp(10px,1.5vh,12px);line-height:1.2;overflow:hidden;background:#ffffff01}.rank-cell:hover{background:#d6b66212}.rank-cell:focus-visible{outline:1px solid #d6b662;outline-offset:-2px}.rank-blocked{border-left-color:#fb718560}.rank-unknown{border-left-color:#ffffff30}
   .radar-tail{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;flex-shrink:0;padding:0 5px 5px}.radar-tail .rank-cell{height:26px;border:1px solid #ffffff12;border-radius:5px;font-size:10px;grid-template-columns:20px minmax(0,1fr) 36px 29px 22px}
   .rank-dialog{width:min(720px,calc(100vw - 24px));max-height:85dvh;padding:0;border:1px solid #a78b4660;border-radius:18px;background:#080d15;color:white}.rank-dialog[open]{display:flex;flex-direction:column}.rank-dialog::backdrop{background:#000a;backdrop-filter:blur(3px)}
   @keyframes radar-gold-flash{0%{background-color:rgba(244,211,125,.04)}25%{background-color:rgba(255,223,133,.30);box-shadow:inset 0 0 35px rgba(255,216,116,.15)}100%{background-color:transparent}}.rank-flash{animation:radar-gold-flash 1.1s ease-out}
   @media(prefers-reduced-motion:reduce){.rank-flash{animation:none;outline:1px solid #f2d27e88}}
   @media(min-width:768px) and (max-width:1000px){.radar-tail{grid-template-columns:repeat(2,minmax(0,1fr))}} @media(max-width:767px){.compact-radar{height:auto;min-height:100%}.radar-heading h1{font-size:12px}.radar-leaders{grid-template-columns:1fr}.radar-columns{grid-template-columns:1fr}.rank-column-body{grid-template-rows:repeat(15,28px)}.radar-tail{grid-template-columns:1fr}.radar-ranking{flex:none}.rank-dialog{max-height:80dvh}}
  `}</style>
 </div>;
}
