'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { Activity,ArrowUp,ArrowDown,RefreshCw,Trophy } from 'lucide-react';
import { executionBlocked,currentRankRow,rankRows,rankChanges,type RankRow } from '@/lib/realtime-ranking';
import { SignalGateList } from './SignalGateList';
type Snapshot={checkedAt:number;runtimeSha:string;rows:RankRow[];metric:string;errors:Record<string,string>};
function constraints(row:RankRow){return row.gates.filter(g=>g.kind==='execution'&&g.state==='NO').map(g=>g.label);}
function missing(row:RankRow){return row.gates.filter(g=>g.kind!=='execution'&&g.state!=='OK').map(g=>g.label+'：'+g.detail).join(' / ')||'市場条件通過。発注時の資金・競合確認待ち';}
function Movement({delta}:{delta?:number}){return delta===0?<span className="text-xs text-[#efd58c]">NEW</span>:delta?<span className={'inline-flex items-center text-xs '+(delta>0?'text-emerald-300':'text-rose-300')}>{delta>0?<ArrowUp size={12}/>:<ArrowDown size={12}/>} {Math.abs(delta)}</span>:<span className="text-xs text-white/25">—</span>;}
export function RealtimeRankingBoard(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logic,setLogic]=useState('ALL'),[side,setSide]=useState('ALL'),[search,setSearch]=useState(''),[remaining,setRemaining]=useState(120),[changes,setChanges]=useState<Record<string,number>>({}),[flash,setFlash]=useState<Record<string,number>>({});
 const previous=useRef<string[]>([]),requesting=useRef(false),alive=useRef(true),next=useRef(Date.now()+120000),flashTimer=useRef<ReturnType<typeof setTimeout>>();
 const load=useCallback(async()=>{if(requesting.current)return;requesting.current=true;setBusy(true);try{const res=await fetch('/api/system/realtime-ranking',{cache:'no-store'}),d=await res.json();if(!res.ok||!d.ok)throw Error(d.error||'取得失敗');if(!alive.current)return;const ids=d.rows.filter((r:RankRow)=>r.score!==null).map((r:RankRow)=>r.id),movement=rankChanges(previous.current,ids);previous.current=ids;setChanges(movement);setFlash(movement);if(flashTimer.current)clearTimeout(flashTimer.current);flashTimer.current=setTimeout(()=>setFlash({}),1200);setData(d);setError('');}catch(e){if(alive.current){setError(e instanceof Error?e.message:'取得失敗');setFlash({});}}finally{requesting.current=false;if(alive.current){setBusy(false);next.current=Date.now()+120000;setRemaining(120);}}},[]);
 useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>{setRemaining(Math.max(0,Math.ceil((next.current-Date.now())/1000)));if(Date.now()>=next.current)void load();},1000);return()=>{alive.current=false;clearInterval(timer);if(flashTimer.current)clearTimeout(flashTimer.current);};},[load]);
 const filtered=rankRows((data?.rows||[]).map(r=>currentRankRow(r,Date.now()))).filter(r=>(logic==='ALL'||r.logic===logic)&&(side==='ALL'||r.side===side)&&((r.symbol+' '+r.logic).toLowerCase().includes(search.toLowerCase()))),top=error?[]:filtered.filter(r=>r.score!==null&&!executionBlocked(r)).slice(0,3);
 return <div className="space-y-5"><section className="panel-gold rounded-[28px] p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs tracking-widest text-[#d7be76]"><Activity size={16}/> LIVE SIGNAL RADAR</div><h1 className="gold-heading mt-2 text-2xl font-black md:text-3xl">リアルタイム判定 Ranking</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/60">いま条件が揃い始めている通貨を、ロジック・方向ごとに確認。上位候補と不足条件を一緒に監視できます。</p></div><button disabled={busy} onClick={()=>void load()} className="flex items-center gap-2 rounded-full border border-[#a68948]/40 bg-[#aa8430]/10 px-4 py-2 text-xs text-[#efdda7] disabled:opacity-50"><RefreshCw size={14} className={busy?'animate-spin':''}/>{busy?'更新中':'更新'} · {remaining}秒</button></div><div className="mt-4 flex flex-wrap gap-3 text-[11px] text-white/45"><span>自動更新 2分</span><span>観測 {data?new Date(data.checkedAt).toLocaleString('ja-JP'):'取得中'}</span><span>監視 {data?.rows.filter(r=>r.symbol!=='—').length??'—'} ルート</span><span>Runtime {data?.runtimeSha.slice(0,12)||'—'}</span></div><p className="mt-3 text-xs leading-5 text-white/40">{data?.metric||'接近度は確認できた市場条件の充足度です。発火確率や期待利益を示す数値ではありません。'} 更新周期と各ロジックの確定足・判定周期は異なります。</p></section>
 {error&&<div role="alert" className="rounded-2xl border border-rose-300/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}。ランキングは前回観測です。最新順位として扱わないでください。</div>}
 {!!data&&Object.keys(data.errors).length>0&&<div role="status" className="rounded-xl border border-amber-300/20 p-3 text-xs text-amber-200">取得未確認：{Object.keys(data.errors).join(' / ')}。他ロジックの観測は表示を継続しています。</div>}
 <div className="flex flex-wrap items-center gap-2"><input aria-label="通貨を検索" placeholder="通貨・ロジックを検索" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#090e16] px-3 py-2 text-sm text-white"/><select aria-label="ロジック" value={logic} onChange={e=>setLogic(e.target.value)} className="rounded-xl border border-white/10 bg-[#090e16] px-3 py-2 text-sm text-white"><option value="ALL">全ロジック</option>{[...new Set(data?.rows.map(r=>r.logic)||[])].map(v=><option key={v}>{v}</option>)}</select><select aria-label="方向" value={side} onChange={e=>setSide(e.target.value)} className="rounded-xl border border-white/10 bg-[#090e16] px-3 py-2 text-sm text-white"><option value="ALL">全方向</option><option>LONG</option><option>SHORT</option><option>WAIT</option></select></div>
 <section aria-label="上位3候補" className="grid gap-3 lg:grid-cols-3">{top.map((r,i)=><article key={r.id} className={'radar-card rounded-[24px] border border-[#a78b46]/30 bg-[linear-gradient(145deg,#262116,#090e16_75%)] p-5 '+(flash[r.id]!==undefined?'rank-flash':'')}><div className="flex items-center justify-between text-[#efd58c]"><span className="flex items-center gap-2 text-xs"><Trophy size={15}/> {i+1} / 全体 #{r.rank}</span><Movement delta={changes[r.id]}/></div><h2 className="mt-4 text-2xl font-black text-white">{r.symbol.replace(/USDT$/,'')}<span className="ml-2 text-xs font-normal text-white/35">USDT</span></h2><div className="mt-2 flex gap-2 text-xs"><span className="rounded-md bg-white/10 px-2 py-1 text-[#efd890]">{r.logic}</span><span className={'rounded-md px-2 py-1 '+(r.side==='LONG'?'bg-emerald-400/10 text-emerald-300':'bg-rose-400/10 text-rose-300')}>{r.side}</span></div><div className="mt-4 flex items-end gap-2"><span className="text-3xl font-bold text-[#f0dfa5]">{r.score}</span><span className="pb-1 text-xs text-white/40">/100 条件充足度</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#d6b662]" style={{width:r.score+'%'}}/></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-white/60">不足：{missing(r)}</p>{constraints(r).length>0&&<p className="mt-3 rounded-lg bg-rose-400/10 p-2 text-xs text-rose-200">発注制約：{constraints(r).join(' / ')}</p>}<Link href={'#row-'+encodeURIComponent(r.id)} className="mt-4 inline-block text-xs text-[#dbc787]">条件の詳細を見る ↓</Link></article>)}</section>
 <section className="overflow-hidden rounded-[24px] border border-white/10 bg-[#080d15]"><div className="flex justify-between border-b border-white/10 p-4"><h2 className="text-sm font-bold text-white">全監視通貨・ロジック</h2><span className="text-xs text-white/40">{filtered.length} 件 · 行を開くと条件詳細</span></div>{filtered.map(r=><details key={r.id} id={'row-'+r.id} className={'border-b border-white/5 last:border-0 '+(flash[r.id]!==undefined?'rank-flash':'')}><summary className="cursor-pointer list-none p-4 hover:bg-white/[.02]"><div className="flex flex-wrap items-center gap-3"><span className="w-8 text-lg font-bold text-[#d9bd74]">{error?'—':r.rank??'—'}</span><div className="min-w-[100px] flex-1"><span className="font-bold text-white">{r.symbol.replace(/USDT$/,'')}</span><div className="mt-1 flex gap-2 text-[11px]"><span className="text-[#d9bd74]">{r.logic}</span><span className={r.side==='LONG'?'text-emerald-300':r.side==='SHORT'?'text-rose-300':'text-white/40'}>{r.side}</span></div></div><Movement delta={error?undefined:changes[r.id]}/><span className="w-24 text-right text-sm font-semibold text-[#ead7a4]">{error?'更新失敗':r.score===null?'未評価':r.score+' / 100'}</span><span className={'rounded-md px-2 py-1 text-[10px] '+(!r.fresh||error?'bg-white/5 text-white/40':constraints(r).length?'bg-rose-300/10 text-rose-200':'bg-[#d2b15f]/10 text-[#e8d092]')}>{error?'前回観測':!r.fresh?'時間外 / 未確認':constraints(r).length?'発注制約あり':'条件観測中'}</span></div><p className="mt-2 pl-11 text-xs leading-5 text-white/50">{r.fresh?missing(r):r.reason}</p>{constraints(r).length>0&&<p className="mt-1 pl-11 text-[11px] text-rose-200/80">制約：{constraints(r).join(' / ')}</p>}</summary><div className="px-4 pb-4 sm:pl-16"><p className="mb-3 text-[11px] text-white/40">ソース観測 {r.checkedAt?new Date(r.checkedAt).toLocaleString('ja-JP'):'未取得'}</p><SignalGateList gates={error?r.gates.map(g=>({...g,state:'UNKNOWN',detail:'更新失敗：前回観測'})):r.gates}/>{r.href&&r.symbol!=='—'&&<Link href={r.href} className="mt-3 inline-block text-xs text-[#dcc68a]">{r.logic} 詳細ページ →</Link>}</div></details>)}{!data&&<p className="p-6 text-sm text-white/50">各ロジックのProduction観測を取得中…</p>}{data&&!filtered.length&&<p className="p-6 text-sm text-white/50">この絞り込みに該当する通貨はありません。</p>}</section>
 <style jsx global>{`@keyframes radar-gold-flash{0%{background-color:rgba(244,211,125,.04)}25%{background-color:rgba(255,223,133,.30);box-shadow:inset 0 0 35px rgba(255,216,116,.15),0 0 18px rgba(255,211,104,.12)}100%{background-color:transparent}}.rank-flash{animation:radar-gold-flash 1.1s ease-out}@media(prefers-reduced-motion:reduce){.rank-flash{animation:none;outline:1px solid rgba(242,210,126,.55)}}`}</style>
 </div>;
}
