export const DIST_TERMINAL_LIVE_CONFIG = {
  productName: "DISTerminal",
  strategyLabel: "V12 X1.00 ALL + PENGU V2 + V52 統合LIVE",
  executionVenue: "AsterDEX",
  executor: "AsterDirectTradeExecutor",
  approvedReleaseSha: "d830b3c8309976e2d8c9532fa373df9e3127a796",
  v12DailyLossPct: 5,
  sharedCryptoDailyLossPct: 5,
  v52DailyLossPct: 3.5,
  /** Gross values are policy caps; V12's requested size remains risk/ATR-driven. */
  maximumGross: 2.5,
  v12Gross: 1.5,
  v12SizingMode: "X1.00要求Gross / Entry上限1.50x / 1建玉上限1.00x",
  sharedCryptoGross: 2.5,
  v52StockGross: 1.5,
  v52V11Gross: 1,
  v52V50Gross: 1,
  v52MaxConcurrentPositions: 2,
  penguGross: 0.75,
  v12Symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "LINKUSDT", "AVAXUSDT", "DOGEUSDT", "INJUSDT", "XRPUSDT", "ADAUSDT", "LTCUSDT", "ATOMUSDT", "AAVEUSDT", "NEARUSDT"],
  penguSymbol: "PENGUUSDT",
  cryptoSymbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "LINKUSDT", "AVAXUSDT", "DOGEUSDT", "INJUSDT", "XRPUSDT", "ADAUSDT", "LTCUSDT", "ATOMUSDT", "AAVEUSDT", "NEARUSDT", "PENGUUSDT"],
  stockSymbols: ["AMZNUSDT", "METAUSDT", "MSFTUSDT", "NVDAUSDT", "TSLAUSDT"],
} as const;
