export const DIST_TERMINAL_LIVE_CONFIG = {
  productName: "DISTerminal",
  strategyLabel: "PENGU Dual LS V2 + V52 Stock 統合LIVE",
  executionVenue: "AsterDEX",
  executor: "AsterDirectTradeExecutor",
  approvedReleaseSha: "a9c66100a1d2147133e859b19bff13495ce50d4c",
  v96DailyLossPct: 5,
  v52DailyLossPct: 3.5,
  maximumGross: 1.5,
  v96CryptoGross: 1.5,
  v52StockGross: 1.5,
  penguInitialGross: 1.15,
  penguStrategyId: "PENGU_DUAL_LS_V2_FINAL",
  penguMode: "LIVE",
  cryptoSymbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "PENGUUSDT"],
  stockSymbols: ["AMZNUSDT", "METAUSDT", "MSFTUSDT", "NVDAUSDT", "TSLAUSDT"],
} as const;
