export type Gate = { key:string; label:string; state:'OK'|'NO'|'UNKNOWN'; actual?:number|string; required?:number|string; detail:string; kind?:'signal'|'execution'; progress?:number };
export type RankRow = { id:string; symbol:string; logic:string; side:string; score:number|null; gates:Gate[]; reason:string; fresh:boolean; checkedAt:number; rank?:number; href?:string };
export function executionBlocked(row:RankRow){return row.gates.some(g=>g.kind==='execution'&&g.state==='NO');}
export function rankRows(rows:RankRow[]){const tier=(r:RankRow)=>r.score===null?0:executionBlocked(r)?1:2;return [...rows].sort((a,b)=>tier(b)-tier(a)||(b.score??-1)-(a.score??-1)||a.id.localeCompare(b.id)).map((r,i)=>({...r,rank:r.score===null?undefined:i+1}));}
export function rankChanges(previous:string[],next:string[]){const result:Record<string,number>={};if(!previous.length)return result;next.forEach((id,i)=>{const old=previous.indexOf(id);if(old<0)result[id]=0;else if(old!==i)result[id]=old-i;});return result;}
export function gateScore(gates:Gate[],fresh:boolean){const signal=gates.filter(g=>g.kind!=='execution');if(!fresh||!signal.length||signal.some(g=>g.state==='UNKNOWN'))return null;const score=Math.round(100*signal.reduce((s,g)=>s+(g.state==='OK'?1:Math.max(0,Math.min(.99,g.progress??0))),0)/signal.length);return signal.every(g=>g.state==='OK')?100:Math.min(99,score);}
export const FET_POLICY={lookbackHours:48,volumeMedianHours:72,minimumVolumeRatio:1.2,decisionEntryHourModulo:4,decisionEntryHourRemainder:1,liveEntryWindowMs:300000};
export function freshTimestamp(at:unknown,now:number,maxAge:number){return typeof at==='number'&&Number.isFinite(at)&&at>0&&now-at>=-60000&&now-at<=maxAge;}
export function updateFetClock(gates:Gate[],now:number){const entry=now-now%3600000,open=new Date(entry).getUTCHours()%FET_POLICY.decisionEntryHourModulo===FET_POLICY.decisionEntryHourRemainder&&now-entry<=FET_POLICY.liveEntryWindowMs;return gates.map(g=>g.key==='clock'?{...g,state:open?'OK' as const:'NO' as const,actual:new Date(now).toISOString(),detail:'現在時刻で受付時間を再評価（市場条件は記載の観測時点）'}:g);}
export function fetObservationExpiry(at:number,ttl:number){const hour=Math.floor(at/3600000)*3600000,cutoff=hour+FET_POLICY.liveEntryWindowMs+1;return Math.min(at+ttl,hour+3600000,at<cutoff?cutoff:Infinity);}
export function currentFetGates(gates:Gate[],checkedAt:number,now:number){return updateFetClock(gates,now).map(g=>Math.floor(checkedAt/3600000)!==Math.floor(now/3600000)&&(g.kind!=='execution'||g.key==='data')?{...g,state:'UNKNOWN' as const,detail:'新しい確定足の観測更新待ち（前回値）'}:g);}
export function currentRankRow(row:RankRow,now:number):RankRow{if(row.logic!=='FET')return row;const fresh=row.fresh&&Math.floor(row.checkedAt/3600000)===Math.floor(now/3600000);return {...row,fresh,gates:currentFetGates(row.gates,row.checkedAt,now),score:fresh?row.score:null,rank:fresh?row.rank:undefined,reason:fresh?row.reason:'新しい確定足の観測更新待ち'};}
export function evaluateFet(raw:unknown,now:number,policy=FET_POLICY):{valid:boolean;gates:Gate[];referenceTs?:number}{
 const H=3600000,entry=now-now%H;
 const clock=new Date(entry).getUTCHours()%policy.decisionEntryHourModulo===policy.decisionEntryHourRemainder&&now-entry<=policy.liveEntryWindowMs;
 const gates:Gate[]=[{key:'clock',label:'新規受付時間',state:clock?'OK':'NO',actual:new Date(now).toISOString(),required:'UTC時刻 % '+policy.decisionEntryHourModulo+' = '+policy.decisionEntryHourRemainder+' / 最初の'+policy.liveEntryWindowMs/60000+'分',detail:'市場条件と別に判定する受付時間',kind:'execution'}];
 const rows=Array.isArray(raw)?raw.filter((r):r is unknown[]=>Array.isArray(r)).map(r=>({t:Number(r[0]),high:Number(r[2]),low:Number(r[3]),open:Number(r[1]),close:Number(r[4]),volume:Number(r[5]),end:Number(r[6])})).filter(r=>r.end<entry).sort((a,b)=>a.t-b.t):[];
 const n=Math.max(policy.lookbackHours,policy.volumeMedianHours)+1,used=rows.slice(-n);
 const valid=used.length===n&&used.every((r,i)=>Number.isFinite(r.t)&&r.t%H===0&&r.end===r.t+H-1&&[r.high,r.low,r.open,r.close,r.volume].every(Number.isFinite)&&r.low>0&&r.high>=Math.max(r.close,r.open)&&r.low<=Math.min(r.open,r.close)&&r.volume>=0&&(!i||r.t-used[i-1].t===H))&&used.at(-1)?.t===entry-H;
 gates.push({key:'data',label:'確定1時間足・連続性',state:valid?'OK':'UNKNOWN',actual:used.length,required:n,detail:valid?'未確定足を除外し、欠損・重複なし':'最新足・連続性・価格形式のいずれかが未確認',kind:'execution'});
 if(!valid){gates.push(...['breakout','volume'].map(key=>({key,label:key==='breakout'?'48時間高値更新':'出来高確認',state:'UNKNOWN' as const,detail:'有効な確定足が不足'})));return {valid:false,gates};}
 const last=used.at(-1)!,high=Math.max(...used.slice(-policy.lookbackHours-1,-1).map(r=>r.high));
 const volumes=used.slice(-policy.volumeMedianHours-1,-1).map(r=>r.volume).sort((a,b)=>a-b),m=Math.floor(volumes.length/2),median=volumes.length%2?volumes[m]:(volumes[m-1]+volumes[m])/2,ratio=median>0?last.volume/median:0;
 gates.push({key:'breakout',label:'48時間高値更新',state:last.close>high?'OK':'NO',actual:last.close,required:'終値 > '+high,detail:'高値まで '+Math.max(0,(high/last.close-1)*100).toFixed(3)+'%（同値はNO）。接近度は高値から5%下を0として計算',progress:Math.min(.99,Math.max(0,1-Math.max(0,high/last.close-1)/.05))});
 gates.push({key:'volume',label:'出来高 / 72時間中央値',state:ratio+1e-12>=policy.minimumVolumeRatio?'OK':'NO',actual:ratio,required:policy.minimumVolumeRatio,detail:'直前72本中央値 '+median.toFixed(2)+' / 確定足 '+last.volume.toFixed(2),progress:ratio/policy.minimumVolumeRatio});
 return {valid:true,gates,referenceTs:last.end};
}
