export const DISDEX_V13D_V11EQ_V96_STRATEGY_ID =
    "DISDEX_V13D_V11EQ_STOCK_ROUTER_PLUS_CRYPTO_V96" as const;

export const DISDEX_V13D_V11EQ_V96_LINEAGE = {
    cryptoV96ProductionCommit: "a4529372a4a331b602a51d36f3287345a89436bb",
    v11FrozenSourceCommit: "0fad24c105a7f0f61af6042ba04a8b1386ffec7c",
    v13dFrozenSourceCommit: "dbfd7e026a81343a23ab97d202761f7f9bbe5755",
    oneYearPortfolioResearchPr: 82,
    v13dForwardResearchPr: 81,
    portfolioResearchStatus: "ONE_YEAR_UNIFIED_HISTORICAL_LEAD_FORWARD_EXECUTION_REQUIRED",
} as const;

export const DISDEX_V13D_V11EQ_V96_ALLOCATION = {
    cryptoSleeveGrossCap: 1.0,
    stockSleeveGrossCap: 1.0,
    portfolioGrossCap: 2.0,
    sleeveLendingEnabled: false,
    maximumConcurrentStockPositions: 1,
    stockUnusedCapacityAction: "HOLD_CASH",
    stockMayPreemptCrypto: false,
    cryptoMayPreemptStock: false,
} as const;

export const DISDEX_V13D_CONFIG = {
    strategyId: "V13D_EDGE20_NO_PREVIOUS_SYMBOL",
    enabledForImplementation: true,
    priority: 1,
    timeZone: "America/New_York",
    decisionTimeNy: "10:00:00",
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteBasisBps: 20,
    selection: "LARGEST_ABSOLUTE_BASIS_TOP1_ALPHABETICAL_TIEBREAK",
    makerVenue: "ASTER",
    hedgeVenue: "XYZ",
    makerNotionalUsd: 100,
    previousCompletedSymbolCooldownOnce: true,
    maximumDisplayedAsterQueueUsd: 250,
    minimumXyzTopDepthUsd: 100,
    maximumBookAgeMs: 1500,
    hedgeDelayMs: 250,
    maximumAdverseTwoSecondTradeImbalance: 0.65,
    maximumReferenceMoveBps: 4,
    minimumProjectedNormalNetBps: 2,
    takeProfitCheckTimeNy: "14:30:00",
    takeProfitPriceGrossBps: 30,
    finalExitTimeNy: "15:00:00",
    hardFlatDeadlineNy: "15:10:00",
    overnightAllowed: false,
    incompleteMakerFillAction: "FAIL_CLOSED_FLATTEN",
    incompleteHedgeAction: "FAIL_CLOSED_FLATTEN",
} as const;

export const DISDEX_V11_EQ_CONFIG = {
    strategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1__EQ_V1",
    parentStrategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1",
    enabledForImplementation: true,
    priority: 2,
    timeZone: "America/New_York",
    signalTimeNy: "10:00:00",
    executionWindowStartNy: "10:00:00",
    entryTimeNy: "10:30:00",
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteCashAsterBasisBps: 50,
    selection: "LARGEST_ABSOLUTE_BASIS_TOP1",
    directions: "LONG_AND_SHORT",
    targetGross: 1.0,
    maximumDataAgeMs: 1500,
    maximumSourceClockDifferenceMs: 1500,
    maximumEstimatedRoundTripCostBps: 60,
    maximumCostToEntryBasisRatio: 0.75,
    minimumEstimatedNetEdgeBps: 10,
    convergenceTargetBps: 15,
    minimumDepthMultiple: 2,
    maximumCurrentSpreadBps: 20,
    maximumSpreadToThirtySecondMedianMultiple: 2,
    maximumAdverseTwoSecondMoveBps: 5,
    maximumAdverseBasisMoveBps: 10,
    requireCandidateStillTop1AtEntry: true,
    candidateReplacementAllowed: false,
    entryOrderType: "POST_ONLY_LIMIT",
    entryOrderTtlMs: 10_000,
    minimumAcceptedFillRatio: 0.90,
    marketFallbackAllowed: false,
    partialFillAction: "CANCEL_REMAINDER_AND_FLATTEN_IF_BELOW_MINIMUM_FILL",
    convergenceExitBps: 15,
    zeroCrossExit: true,
    basisExpansionStopMultiple: 1.5,
    finalExitTimeNy: "15:30:00",
    overnightAllowed: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RISK = {
    maximumPortfolioDailyLossPct: 2,
    dailyLossTimeZone: "UTC",
    dailyLossAction: "CANCEL_NEW_ORDERS_AND_FLATTEN_MANAGED",
    dailyLossFailClosed: true,
    killSwitchAction: "CANCEL_ALL_AND_FLATTEN_MANAGED_REDUCE_ONLY",
    unknownOrderStateAction: "FAIL_CLOSED",
    staleMarketDataAction: "FAIL_CLOSED",
    positionReconciliationFailureAction: "FAIL_CLOSED",
    unresolvedStockInventoryAllowed: false,
    closeUnmanagedPositions: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RUNTIME = {
    strategyId: DISDEX_V13D_V11EQ_V96_STRATEGY_ID,
    implementationStatus: "CODEX_IMPLEMENTATION_HANDOFF_NOT_LIVE",
    mode: "DISABLED" as const,
    liveTradingEnabled: false,
    orderSubmissionAllowed: false,
    paperTradingEnabled: false,
    shadowCollectionEnabled: true,
    stateSchemaVersion: 1,
    stateDirectory: ".runtime-state/disdex-v13d-v11eq-v96",
    stockOrderClientIdPrefix: "stock-v13d-v11eq-",
    requireFreshOperatorOverride: true,
    requireExactCommitApproval: true,
    requireV13dForwardReview: true,
    requireV11EqForwardReview: true,
    requireCombinedPaperRehearsal: true,
    requireCredentialsAndEndpointPreflight: true,
    liveBlockReason:
        "Codex must implement and pass all contract, execution, recovery, Paper and operator-approval gates before liveTradingEnabled or orderSubmissionAllowed may be changed.",
} as const;
