export const DISDEX_V13D_V11EQ_V96_STRATEGY_ID =
    "DISDEX_V52_V11EQ_V50_ASTER_ONLY_PLUS_CRYPTO_V96" as const;

export const DISDEX_V13D_V11EQ_V96_LINEAGE = {
    cryptoV96ProductionCommit: "a4529372a4a331b602a51d36f3287345a89436bb",
    v11FrozenSourceCommit: "0fad24c105a7f0f61af6042ba04a8b1386ffec7c",
    v50ResearchPr: 94,
    v52PortfolioResearchPr: 97,
    portfolioResearchStatus: "V96_V52_ONE_YEAR_COMPOUNDED_REPLAY_PASS_RESEARCH_ONLY",
} as const;

export const DISDEX_V13D_V11EQ_V96_ALLOCATION = {
    cryptoSleeveGrossCap: 2.5,
    stockSleeveGrossCap: 1.5,
    v11MaximumGross: 1.0,
    v50MaximumGross: 1.0,
    portfolioGrossCap: 2.5,
    sleeveLendingEnabled: false,
    cryptoMayUsePortfolioResidual: true,
    maximumConcurrentStockPositions: 2,
    maximumConcurrentPositionsPerStockStrategy: 1,
    sameSymbolConcurrentStockPositionAllowed: false,
    firstFilledPositionPreserved: true,
    forcedReplacementAllowed: false,
    stockUnusedCapacityAction: "HOLD_CASH",
    stockMayPreemptCrypto: false,
    cryptoMarginEmergencyMayFlattenStock: true,
} as const;

export const DISDEX_V13D_CONFIG = {
    strategyId: "V13D_DISABLED",
    enabledForLive: false,
} as const;

export const DISDEX_V11_EQ_CONFIG = {
    strategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1__EQ_V1",
    parentStrategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1",
    enabledForLive: true,
    priority: 1,
    timeZone: "America/New_York",
    signalTimeNy: "10:00:00",
    entryTimeNy: "10:30:00",
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteCashAsterBasisBps: 50,
    selection: "SIGNAL_TOP1_MUST_REMAIN_TOP1_AT_ENTRY",
    directions: "LONG_AND_SHORT",
    targetGross: 1.0,
    maximumDataAgeMs: 5000,
    maximumSourceClockDifferenceMs: 1500,
    maximumEstimatedRoundTripCostBps: 60,
    maximumCostToEntryBasisRatio: 0.75,
    minimumEstimatedNetEdgeBps: 10,
    convergenceTargetBps: 15,
    minimumDepthMultiple: 2,
    maximumCurrentSpreadBps: 20,
    maximumSpreadToThirtySecondMedianMultiple: 2,
    maximumAdverseTwoSecondMoveBps: 5,
    maximumAdverseBasisMoveBps: 10,
    requireCandidateStillTop1AtEntry: true,
    candidateReplacementAllowed: false,
    entryOrderType: "POST_ONLY_LIMIT_GTX",
    entryOrderTtlMs: 10_000,
    minimumAcceptedFillRatio: 0.90,
    marketFallbackAllowed: false,
    convergenceExitBps: 15,
    zeroCrossExit: true,
    basisExpansionStopMultiple: 1.5,
    finalExitTimeNy: "15:30:00",
    overnightAllowed: false,
} as const;

export const DISDEX_V50_CONFIG = {
    strategyId: "POST_EARLY3__B75__H3__BOTH__NONE",
    enabledForLive: true,
    priority: 2,
    timeZone: "America/New_York",
    entryTimesNy: ["11:30:00", "12:30:00", "13:30:00"],
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteCashAsterBasisBps: 75,
    directions: "LONG_AND_SHORT",
    maximumGross: 1.0,
    receivesOnlyRemainingStockGross: true,
    maximumDailyTrades: 3,
    maximumConcurrentPositions: 1,
    sameSymbolCooldown: false,
    sameSymbolConcurrentWithV11Allowed: false,
    maximumHoldingHours: 3,
    hourlyCheckpointExitOnly: true,
    convergenceExitBps: 15,
    zeroCrossExit: true,
    basisExpansionStopMultiple: 1.5,
    maximumAdverseBasisMoveBps: 10,
    maximumEstimatedRoundTripCostBps: 60,
    minimumEstimatedNetEdgeBps: 10,
    minimumDepthMultiple: 2,
    entryOrderType: "POST_ONLY_LIMIT_GTX",
    entryOrderTtlMs: 10_000,
    minimumAcceptedFillRatio: 0.90,
    finalExitTimeNy: "15:30:00",
    missedCheckpointAction: "FAIL_CLOSED_FLATTEN",
    overnightAllowed: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RISK = {
    maximumPortfolioDailyLossPct: 2,
    dailyLossTimeZone: "UTC",
    dailyLossAction: "CANCEL_NEW_ORDERS_AND_FLATTEN_MANAGED",
    dailyLossFailClosed: true,
    killSwitchAction: "CANCEL_ALL_AND_FLATTEN_MANAGED_REDUCE_ONLY",
    sharedWithCryptoV96: true,
    unknownOrderStateAction: "FAIL_CLOSED_OPERATOR_REVIEW",
    staleMarketDataAction: "FAIL_CLOSED",
    positionReconciliationFailureAction: "FAIL_CLOSED",
    unresolvedStockInventoryAllowed: false,
    closeUnmanagedPositions: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RUNTIME = {
    strategyId: DISDEX_V13D_V11EQ_V96_STRATEGY_ID,
    implementationStatus: "VPS_LIVE_READY_GROSS_2P5_PENGU_1P15_ENV_PREFLIGHT_AND_STATE_MIGRATION_GATED",
    mode: "LIVE_READY" as const,
    liveTradingEnabled: true,
    orderSubmissionAllowed: true,
    paperTradingEnabled: true,
    stateSchemaVersion: 3,
    stateDirectory: ".runtime-state/disdex-v13d-v11eq-v96",
    stockOrderClientIdPrefix: "stock-v52-",
    pythonStockEngine: "scripts/disdex_v52_aster_only_live_engine.py",
    combinedSupervisor: "scripts/disdex-v13d-v11eq-v96-live-runner.ts",
    combinedPreflight: "scripts/disdex-v13d-v11eq-v96-live-preflight.ts",
    requireCredentialsAndEndpointPreflight: true,
    requireExternalFreshStockReferenceFeedForLive: true,
    requireCombinedLiveEnvironmentSwitch: true,
    requiredCombinedLiveAcknowledgement: "I_ACCEPT_REAL_MONEY_V96_V52_ASTER_ONLY",
    legacyV11StateMigrationAcknowledgement: "I_ACKNOWLEDGE_V11_TO_V52_STATE_MIGRATION",
    cryptoV96RetainsOwnLiveGates: true,
    liveBlockReason:
        "Real orders require V52 live mode, the acknowledgement, verified V96 migration, exact-commit approval for PENGU 1.15 and portfolio Gross 2.5, fresh Pyth/IEX references, inactive Kill Switch, reconciled positions, and all Gross limits. Hyperliquid and V13D remain excluded.",
} as const;
