export const DISDEX_PENGU_DUAL_ENGINE_V46 = {
    id: "PENGU_DUAL_ENGINE_V46",
    status: "IMPLEMENTED_PAPER_FORWARD",
    enabled: true,
    decisionHours: 6,
    longGross: 0.15,
    shortGross: 0.15,
    forwardPromotionGross: 0.30,
    holdHours: 24,
    confirmationDecisionBars: 2,
    reentryCooldownHours: 12,
    minimumRoundTripEdgeBps: 80,
    volumeRecentHours: 12,
    volumeBaseHours: 72,
    volumeFloor: 0.8,
    fundingCap: 0.0003,
    long: {
        entryTrendSmaHours: 72,
        regimeSmaHours: 168,
        regimeSlopeHours: 48,
        momentum6hThresholdPct: 1,
        momentum24hThresholdPct: 0,
        momentum120hThresholdPct: 2,
        relative48hThresholdPct: 1,
        relative120hThresholdPct: 0,
        crossoverLagHours: 12,
        rsiLengthHours: 14,
        rsiMinimum: 45,
        rsiMaximum: 72,
    },
    short: {
        breakdownLookbackHours: 24,
        confirmationMomentumHours: 6,
        confirmationThresholdPct: 0,
    },
    btcRisk: {
        smaHours: 168,
        momentumHours: 72,
        blockLongBelowMomentumPct: -2,
        blockShortAboveMomentumPct: 4,
    },
    evidence: {
        researchVersion: 46,
        selectedLongGate: "G44_SMA168_SL48_M120_2p0_R120_0p0",
        selectedShortRule: "S_BREAKDOWN_F6_S24_T0p0_A0p0_V0p8_FR0p0_BRISK_TIME24",
        fullReturnPct: 99.5831,
        fullProfitFactor: 2.9302,
        fullMaxDrawdownPct: -10.2442,
        frozenHoldoutReturnPct: 9.2219,
        frozenHoldoutProfitFactor: 2.4784,
        frozenHoldoutSevereReturnPct: 8.3937,
        frozenHoldoutMaxDrawdownPct: -4.5835,
        frozenHoldoutLongTrades: 3,
        frozenHoldoutShortTrades: 4,
        pristineForwardEvidence: false,
    },
} as const;

export const DISDEX_V46_RUNTIME = {
    strategyId: "DISDEX_V35_CORE_PLUS_PENGU_DUAL_V46",
    mode: "LIVE" as const,
    liveTradingEnabled: true,
    maximumGross: 2,
    cashReservePct: 2,
    maximumSlippageBps: 35,
    minimumOrderNotionalUsd: 5,
    rebalanceTolerancePct: 1,
    closeUnmanagedPositions: false,
    livePromotionBasis: "MANUAL_OPERATOR_OVERRIDE",
    evidenceNotice: "PENGU V46 pristine forward evidence is incomplete. LIVE execution was enabled by explicit operator approval.",
} as const;
