export const DISDEX_V13D_V11EQ_V96_STRATEGY_ID =
    "DISDEX_V13D_V11EQ_STOCK_ROUTER_PLUS_CRYPTO_V96" as const;

export const DISDEX_V13D_V11EQ_V96_LINEAGE = {
    cryptoV96ProductionCommit: "a4529372a4a331b602a51d36f3287345a89436bb",
    v11FrozenSourceCommit: "0fad24c105a7f0f61af6042ba04a8b1386ffec7c",
    v13dFrozenSourceCommit: "dbfd7e026a81343a23ab97d202761f7f9bbe5755",
    oneYearPortfolioResearchPr: 84,
    v13dForwardResearchPr: 81,
    portfolioResearchStatus: "ONE_YEAR_V11EQ_OBSERVABLE_PROXY_FORWARD_EXECUTION_REQUIRED",
} as const;

export const DISDEX_V13D_V11EQ_V96_ALLOCATION = {
    cryptoSleeveGrossCap: 1.0,
    stockSleeveGrossCap: 1.0,
    portfolioGrossCap: 2.0,
    sleeveLendingEnabled: false,
    maximumConcurrentStockPositions: 1,
    stockUnusedCapacityAction: "HOLD_CASH",
    stockMayPreemptCrypto: false,
    cryptoMayPreemptStock: false,
} as const;

export const DISDEX_V13D_CONFIG = {
    strategyId: "V13D_EDGE20_NO_PREVIOUS_SYMBOL",
    enabledForLive: true,
    priority: 1,
    timeZone: "America/New_York",
    decisionTimeNy: "10:00:00",
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteBasisBps: 20,
    selection: "LARGEST_ABSOLUTE_BASIS_TOP1_ALPHABETICAL_TIEBREAK",
    makerVenue: "ASTER",
    hedgeVenue: "HYPERLIQUID_XYZ",
    makerNotionalUsd: 100,
    previousCompletedSymbolCooldownOnce: true,
    maximumDisplayedAsterQueueUsd: 250,
    minimumXyzTopDepthUsd: 100,
    maximumBookAgeMs: 1500,
    hedgeDelayMs: 250,
    maximumAdverseTwoSecondTradeImbalance: 0.65,
    maximumReferenceMoveBps: 4,
    minimumProjectedNormalNetBps: 2,
    makerOrderType: "POST_ONLY_LIMIT_GTX",
    makerOrderTtlMs: 3000,
    minimumAcceptedMakerFillRatio: 0.90,
    minimumAcceptedHedgeFillRatio: 0.99,
    hedgeOrderType: "IOC_LIMIT",
    takeProfitCheckTimeNy: "14:30:00",
    takeProfitPriceGrossBps: 30,
    finalExitTimeNy: "15:00:00",
    hardFlatDeadlineNy: "15:10:00",
    overnightAllowed: false,
    incompleteMakerFillAction: "FAIL_CLOSED_FLATTEN",
    incompleteHedgeAction: "FAIL_CLOSED_FLATTEN_AND_KILL_SWITCH",
} as const;

export const DISDEX_V11_EQ_CONFIG = {
    strategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1__EQ_V1",
    parentStrategyId: "BOTH__FLAT__CONVERGENCE__ABS_TOP1",
    enabledForLive: true,
    priority: 2,
    timeZone: "America/New_York",
    signalTimeNy: "10:00:00",
    executionWindowStartNy: "10:00:00",
    entryTimeNy: "10:30:00",
    universe: ["AMZN", "META", "MSFT", "NVDA", "TSLA"],
    minimumAbsoluteCashAsterBasisBps: 50,
    selection: "SIGNAL_TOP1_MUST_REMAIN_TOP1_AT_ENTRY",
    directions: "LONG_AND_SHORT",
    targetGross: 1.0,
    maximumDataAgeMs: 1500,
    maximumSourceClockDifferenceMs: 1500,
    maximumEstimatedRoundTripCostBps: 60,
    maximumCostToEntryBasisRatio: 0.75,
    minimumEstimatedNetEdgeBps: 10,
    convergenceTargetBps: 15,
    minimumDepthMultiple: 2,
    maximumCurrentSpreadBps: 20,
    maximumSpreadToThirtySecondMedianMultiple: 2,
    maximumAdverseTwoSecondMoveBps: 5,
    maximumAdverseBasisMoveBps: 10,
    requireCandidateStillTop1AtEntry: true,
    candidateReplacementAllowed: false,
    entryOrderType: "POST_ONLY_LIMIT_GTX",
    entryOrderTtlMs: 10_000,
    minimumAcceptedFillRatio: 0.90,
    marketFallbackAllowed: false,
    partialFillAction: "CANCEL_REMAINDER_AND_FLATTEN_IF_BELOW_MINIMUM_FILL",
    convergenceExitBps: 15,
    zeroCrossExit: true,
    basisExpansionStopMultiple: 1.5,
    finalExitTimeNy: "15:30:00",
    overnightAllowed: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RISK = {
    maximumPortfolioDailyLossPct: 2,
    dailyLossTimeZone: "UTC",
    dailyLossAction: "CANCEL_NEW_ORDERS_AND_FLATTEN_MANAGED",
    dailyLossFailClosed: true,
    killSwitchAction: "CANCEL_ALL_AND_FLATTEN_MANAGED_REDUCE_ONLY",
    sharedWithCryptoV96: true,
    unknownOrderStateAction: "FAIL_CLOSED",
    staleMarketDataAction: "FAIL_CLOSED",
    positionReconciliationFailureAction: "FAIL_CLOSED",
    unresolvedStockInventoryAllowed: false,
    closeUnmanagedPositions: false,
} as const;

export const DISDEX_V13D_V11EQ_V96_RUNTIME = {
    strategyId: DISDEX_V13D_V11EQ_V96_STRATEGY_ID,
    implementationStatus: "LIVE_EXECUTION_IMPLEMENTED_ENV_AND_PREFLIGHT_GATED",
    mode: "LIVE_READY" as const,
    liveTradingEnabled: true,
    orderSubmissionAllowed: true,
    paperTradingEnabled: true,
    shadowCollectionEnabled: true,
    stateSchemaVersion: 2,
    stateDirectory: ".runtime-state/disdex-v13d-v11eq-v96",
    stockOrderClientIdPrefix: "stock-v13d-v11eq-",
    pythonStockEngine: "scripts/disdex_v13d_v11eq_stock_live_engine.py",
    combinedSupervisor: "scripts/disdex-v13d-v11eq-v96-live-runner.ts",
    combinedPreflight: "scripts/disdex-v13d-v11eq-v96-live-preflight.ts",
    requireCredentialsAndEndpointPreflight: true,
    requireExternalFreshStockReferenceFeedForLive: true,
    requireCombinedLiveEnvironmentSwitch: true,
    requiredCombinedLiveAcknowledgement: "I_ACCEPT_REAL_MONEY_V13D_V11EQ_V96",
    cryptoV96RetainsOwnLiveGates: true,
    liveBlockReason:
        "Real orders are submitted only when the combined runner is started in live mode, the combined live environment switch and acknowledgement are present, Stock and V96 preflight pass, venue credentials and fresh external Stock references are available, and the existing V96 exact-commit live gates pass.",
} as const;
