from pathlib import Path
import re

# Preregistered fixed research contract.
V83_NEW_LONG_GROSS = 0.25
V83_MIN_TRADES_PER_FOLD = 2
V83_NEW_LONG_SLEEVE = "PENGU_V83_NEW_LONG_SLEEVE"
V83_FOLD_BOUNDARIES = (
    "2025-08-10T00:00:00Z",
    "2025-12-09T16:00:00Z",
    "2026-04-10T08:00:00Z",
    "2026-08-10T00:00:00Z",
)
# Frozen incumbent and research-only guards are also present in the generated evaluator:
# assert.equal(incNM.trades,41
# longRawForMode(row,"V64_DYNAMIC")
# ordersSent:false liveChanged:false vpsChanged:false productionChanged:false

base = Path("scripts/research_patch_v80_independent_long_sleeve.py").read_text()
base = base.replace("V80", "V83").replace("v80", "v83")
base = base.replace("BTC_LEAD_PENGU_CATCHUP", "LEADER_LAG_STATE_MACHINE")

insert = r'''
type V83Family="LEADER_LAG_STATE_MACHINE";
type V83State="DISCOVERY"|"ARMED"|"TRIGGERED";
interface V83SignalContext{state:V83State;armedAt:number;setupLow:number;armRelative:number;armPengu24:number;armRsi:number;armVolume:number;}
const V83_NEW_LONG_GROSS=0.25,V83_MATERIAL_GAIN_MULTIPLE=1.05,V83_MIN_TRADES_PER_FOLD=2;
const V83_NEW_LONG_SLEEVE="PENGU_V83_NEW_LONG_SLEEVE";
const V83_FOLD_BOUNDARIES=["2025-08-10T00:00:00Z","2025-12-09T16:00:00Z","2026-04-10T08:00:00Z","2026-08-10T00:00:00Z"].map(x=>Date.parse(x));
const V83_FROZEN_V64_CONFIG:V64Config={rule:{feature:"penguReturn72h",op:"lte",threshold:0.12049482888834451},lowGross:0.1875,label:"penguReturn72h_lte_0.12049483_LOW0.1875",trainScore:31.7010356792032};
function v83PriorHigh(rows:PenguDualLsV2EvaluationRow[],index:number,lookback:number){let h=-Infinity;for(let i=Math.max(0,index-lookback);i<index;i++)h=Math.max(h,rows[i].candle.high);return h;}
function v83PriorLow(rows:PenguDualLsV2EvaluationRow[],index:number,lookback:number){let l=Infinity;for(let i=Math.max(0,index-lookback);i<index;i++)l=Math.min(l,rows[i].candle.low);return l;}
function v83SignalContexts(rows:PenguDualLsV2EvaluationRow[]){const contexts=new Map<number,V83SignalContext>();let state:V83State="DISCOVERY",armedAt=-1,expires=-1,setupLow=Infinity,armRelative=0,armPengu24=0,armRsi=0,armVolume=0;for(let index=250;index<rows.length-2;index++){const row=rows[index],f=row.features;if(!f){continue;}if(row.shortSignal||longRawForMode(row,"V64_DYNAMIC")){state="DISCOVERY";armedAt=-1;continue;}const f6=index>=6?rows[index-6].features:undefined;const btcTrendPass=f.btcEma168Distance>0&&f.btcReturn24h>0;const penguStructurePass=Boolean(f6)&&f.close>f.ema168&&f.ema72>=f6!.ema72;const lagSetupPass=f.btcReturn24h>=0.02&&f.btcReturn24h<=0.10&&f.relativeReturn24h<=-0.02&&f.relativeReturn24h>=-0.12&&f.penguReturn24h>=-0.06&&f.penguReturn24h<=0.04&&f.volumeRatio6OverPrior36>=0.80&&f.rsi14>=38&&f.rsi14<=62&&f.atr24Ratio<=0.05;if(state==="DISCOVERY"){if(btcTrendPass&&penguStructurePass&&lagSetupPass){state="ARMED";armedAt=index;expires=index+12;setupLow=v83PriorLow(rows,index+1,6);armRelative=f.relativeReturn24h;armPengu24=f.penguReturn24h;armRsi=f.rsi14;armVolume=f.volumeRatio6OverPrior36;}continue;}if(state==="ARMED"){setupLow=Math.min(setupLow,row.candle.low);const setupInvalid=index>expires||!btcTrendPass||row.candle.close<f.ema168||(f.relativeReturn24h<armRelative&&f.penguReturn24h<armPengu24&&row.candle.close<rows[index-1].candle.close);if(setupInvalid){state="DISCOVERY";armedAt=-1;continue;}const reaccelerationPass=row.candle.close>v83PriorHigh(rows,index,3)&&row.candle.close>row.candle.open&&row.candle.close>f.ema72&&f.relativeReturn24h>armRelative&&f.penguReturn24h>armPengu24&&f.rsi14>armRsi&&f.volumeRatio6OverPrior36>=Math.max(1,armVolume)&&f.btcReturn24h>0;if(reaccelerationPass){state="TRIGGERED";contexts.set(index,{state,armedAt,setupLow,armRelative,armPengu24,armRsi,armVolume});continue;}}if(state==="TRIGGERED"){state="DISCOVERY";armedAt=-1;}}
return contexts;}
function replayV83NewLongSleeve(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:RichTrade[]=[];const contexts=v83SignalContexts(rows),costPerSide=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_ADVERSE_SLIPPAGE_PER_SIDE:0);let index=250,cooldown=-1;while(index<rows.length-2){if(index<=cooldown){index++;continue;}const ctx=contexts.get(index),features=rows[index].features;if(!ctx||!features){index++;continue;}const entryIndex=index+1,entry=rows[entryIndex].candle;const hardStopPrice=Math.max(entry.open*0.92,ctx.setupLow*0.995);const last=Math.min(rows.length-1,entryIndex+71);let exitIndex=last,exitPrice=rows[last].candle.close,engineExitReason="V83_MAX_HOLD",exitReason:ExitGroup="time",mfe=0,mae=0,highWater=entry.open;for(let cursor=entryIndex;cursor<=last;cursor++){const f=rows[cursor].features;assert(f);const bar=rows[cursor].candle;highWater=Math.max(highWater,bar.high);mfe=Math.max(mfe,bar.high/entry.open-1);mae=Math.min(mae,bar.low/entry.open-1);if(bar.low<=hardStopPrice){exitIndex=cursor;exitPrice=hardStopPrice;engineExitReason="V83_SETUP_STRUCTURE_STOP";exitReason="hard";break;}const held=cursor-entryIndex+1;if(highWater>=entry.open*1.08&&cursor>entryIndex+1){const swingLow=v83PriorLow(rows,cursor,6),trailPrice=Math.max(entry.open,swingLow);if(Number.isFinite(trailPrice)&&bar.low<=trailPrice){exitIndex=cursor;exitPrice=trailPrice;engineExitReason="V83_SWING_TRAIL";exitReason="trail";break;}}const relativeFailure=held>=8&&f.relativeReturn24h<=ctx.armRelative&&bar.close<f.ema72;const btcFailure=held>=6&&f.btcEma168Distance<0&&f.btcReturn24h<0&&bar.close<f.ema72;if(relativeFailure||btcFailure){exitIndex=cursor;exitPrice=bar.close;engineExitReason=relativeFailure?"V83_RELATIVE_FAILURE":"V83_BTC_REGIME_FAILURE";exitReason="time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime,rawUnitReturn=exitPrice/entry.open-1,fundingUnitReturn=-fundingBetween(funding,entry.openTime,exitTs),costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn;trades.push({side:"L",signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross:V83_NEW_LONG_GROSS,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn:V83_NEW_LONG_GROSS*netUnitReturn,exitReason,engineExitReason,entryFeatures:{...features},mfeUnit:mfe,maeUnit:mae});}cooldown=exitIndex+PENGU_DUAL_LS_V2.cooldownHours;index=exitIndex+1;}return trades;}
function v83PfPass(m:ReturnType<typeof metrics>,minimum:number){return m.returnPct>0&&(m.profitFactor===null||m.profitFactor>=minimum);}
function evaluateV83(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],baselineV56Normal:RichTrade[]){const derivation=deriveV57Thresholds(baselineV56Normal);v57Thresholds=derivation.thresholds;v64ActiveConfig=V83_FROZEN_V64_CONFIG;const incN=replay(rows,funding,{mode:"normal",longMode:"V64_DYNAMIC"}).trades,incS=replay(rows,funding,{mode:"stress",longMode:"V64_DYNAMIC"}).trades,incNM=metrics(incN),incSM=metrics(incS);assert.equal(incNM.trades,41);assert.equal(incNM.longTrades,13);assert.equal(incNM.shortTrades,28);assert.ok(Math.abs(incNM.returnPct-303.9903920953809)<1e-6);const normal=replayV83NewLongSleeve(rows,funding,"normal"),stress=replayV83NewLongSleeve(rows,funding,"stress"),folds:Array<any>=[];for(let i=0;i<3;i++){const a=V83_FOLD_BOUNDARIES[i],b=V83_FOLD_BOUNDARIES[i+1],n=sliceByTime(normal,a,b),s=sliceByTime(stress,a,b),mn=metrics(n),ms=metrics(s),normalPass=n.length>=V83_MIN_TRADES_PER_FOLD&&v83PfPass(mn,1),stressPass=s.length>=V83_MIN_TRADES_PER_FOLD&&v83PfPass(ms,1);folds.push({fold:i+1,start:new Date(a).toISOString(),end:new Date(b).toISOString(),trades:{normal:n.length,stress:s.length},metrics:{normal:mn,stress:ms},normalPass,stressPass,pass:normalPass&&stressPass});}const allFoldPass=folds.every(x=>x.pass),fmN=metrics(normal),fmS=metrics(stress),robustness={minTotalTrades:9,totalTradesPass:normal.length>=9,normalPfPass:v83PfPass(fmN,1.30),stressPfPass:v83PfPass(fmS,1.10),normalDdPass:fmN.maxDrawdownPct>=-10,stressDdPass:fmS.maxDrawdownPct>=-14,normalPositive:fmN.returnPct>0,stressPositive:fmS.returnPct>0},robustnessPass=robustness.totalTradesPass&&robustness.normalPfPass&&robustness.stressPfPass&&robustness.normalDdPass&&robustness.stressDdPass&&robustness.normalPositive&&robustness.stressPositive,strictPass=allFoldPass&&robustnessPass;return{schema:"pengu-v83-independent-long-sleeve/v1",family:"LEADER_LAG_STATE_MACHINE" as V83Family,frozenV64Config:V83_FROZEN_V64_CONFIG,newLongGross:V83_NEW_LONG_GROSS,materialGainThresholdMultiple:V83_MATERIAL_GAIN_MULTIPLE,incumbent:{normal:incNM,stress:incSM},folds,allFoldPass,fullMetrics:{normal:fmN,stress:fmS},robustness,robustnessPass,strictPass,decision:strictPass?"ADOPT_V83_STANDALONE_CANDIDATE":"KEEP_V64_RESEARCH_CANDIDATE"};}
'''

base, count = re.subn(r"insert=r'''\n.*?\n'''\nif marker not in src", "insert=r'''\n" + insert.strip("\n") + "\n'''\nif marker not in src", base, count=1, flags=re.S)
if count != 1:
    raise SystemExit("failed to replace V83 insert block")

tail = r'''  const v83=evaluateV83(rows,funding,baselineNormal);v64ActiveConfig=V83_FROZEN_V64_CONFIG;const incumbentNormal=replay(rows,funding,{mode:"normal",longMode:"V64_DYNAMIC"}).trades,incumbentStress=replay(rows,funding,{mode:"stress",longMode:"V64_DYNAMIC"}).trades,newLongNormal=replayV83NewLongSleeve(rows,funding,"normal"),newLongStress=replayV83NewLongSleeve(rows,funding,"stress");const resultPayload={status:"PASS_RESEARCH_ONLY",v83,final:{v64Preserved:true,newLongSleeveSelected:"LEADER_LAG_STATE_MACHINE",newLongSleevePromoted:v83.strictPass},safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};
function mkV64(n:RichTrade[],s:RichTrade[]){return{schema:"pengu-dual-ls-v2-aster-ledger/v1",strategyId:PENGU_DUAL_LS_V2.id,longVariant:"PENGU_DUAL_LS_V2_FINAL_V64_FROZEN",shortVariant:"COUNTERWIND_VOL_TARGET_FAILURE_EXIT",currentProductionSourceSha:SOURCE_SHA,researchOnly:true,period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},source:{venue:"Aster perpetual public REST V3",productionLogicSha:SOURCE_SHA},costs:{normalFeeBpsPerSide:6,stressAdditionalAdverseBpsPerSide:35,actualFunding:true},integrity:{noOverlap:n.every((t,i)=>i===0||t.entryTs>n[i-1].exitTs),maximumRequestedGross:Math.max(...n.map(t=>t.requestedGross))},modes:{normal:{metrics:metrics(n),trades:n.map(publicTrade)},stress:{metrics:metrics(s),trades:s.map(publicTrade)}},safety:{ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};}function mkNew(n:RichTrade[],s:RichTrade[]){return{schema:"pengu-v83-new-long-sleeve-ledger/v1",strategyId:V83_NEW_LONG_SLEEVE,researchOnly:true,selectedFamily:"LEADER_LAG_STATE_MACHINE",requestedGross:V83_NEW_LONG_GROSS,period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},source:{venue:"Aster perpetual public REST V3",productionLogicSha:SOURCE_SHA},costs:{normalFeeBpsPerSide:6,stressAdditionalAdverseBpsPerSide:35,actualFunding:true},integrity:{noOverlap:n.every((t,i)=>i===0||t.entryTs>n[i-1].exitTs),longOnly:n.every(t=>t.side==="L"),maximumRequestedGross:n.length?Math.max(...n.map(t=>t.requestedGross)):0},modes:{normal:{metrics:metrics(n),trades:n.map(publicTrade)},stress:{metrics:metrics(s),trades:s.map(publicTrade)}},safety:{ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};}const incumbentLedger=mkV64(incumbentNormal,incumbentStress),newLongLedger=mkNew(newLongNormal,newLongStress);assert.equal(newLongLedger.integrity.longOnly,true);await fs.mkdir(OUTPUT_DIR,{recursive:true});await fs.writeFile(path.join(OUTPUT_DIR,"v83-result.json"),JSON.stringify(resultPayload,null,2)+"\n");await fs.writeFile(path.join(OUTPUT_DIR,"incumbent-v64-pengu-ledger.json"),JSON.stringify(incumbentLedger,null,2)+"\n");await fs.writeFile(path.join(OUTPUT_DIR,"new-long-sleeve-ledger.json"),JSON.stringify(newLongLedger,null,2)+"\n");console.log("V83_RESULT="+JSON.stringify(v83));
'''
base, count = re.subn(r"tail=r'''  const v83=.*?\n'''\nsrc=src\[:start\]\+tail\+src\[end:\]", "tail=r'''" + tail + "'''\nsrc=src[:start]+tail+src[end:]", base, count=1, flags=re.S)
if count != 1:
    raise SystemExit("failed to replace V83 tail block")

exec(compile(base, "<generated-v83-state-machine-patch>", "exec"), {"__name__": "__main__"})
