V59_MODES = (
    'V59_RSI_HIGH_RECOVERY',
    'V59_VOLUME_HIGH_RECOVERY',
    'V59_RSI_OR_VOLUME_RECOVERY',
)

NATIVE_V57_GROSS_MAX = 0.9375
RECOVERY_GROSS_MAX = 0.375
ALLOWED_FAILED_GATES = ('rsiMax', 'volumeMax')
