import fs from "fs/promises";
import path from "path";
import { loadPerpMarketData } from "../lib/research-lab/perp/data-store";
import { runPerpBacktest } from "../lib/research-lab/perp/engine";
import { normalBacktestSummary, replayWithLatencyStress } from "../lib/research-lab/perp/latency-stress";
import type { PerpExecutionAssumptions, PerpMarketData, PerpStrategyGenome, PerpTrade } from "../lib/research-lab/perp/types";

const HOUR=60*60*1000;
const START=Date.UTC(2023,6,1), DEV_END=Date.UTC(2024,6,1), VAL_END=Date.UTC(2025,6,1), END=Date.UTC(2026,6,1);
const WARMUP_START=START-180*24*HOUR;
const TARGET_MONTHLY=6;
const UNIVERSE=["BTC","ETH","BNB","SOL","LINK","AVAX","DOGE","INJ","XRP","ADA","LTC","ATOM","AAVE","NEAR"];
const NORMAL:PerpExecutionAssumptions={feeBpsPerSide:5,slippageBpsPerSide:0,adverseFundingBpsPer8h:0,maintenanceMarginRate:0.005};
const STRESS={delayHours:1,feeBpsPerSide:10,slippageBpsPerSide:5};
const V26:PerpStrategyGenome={id:"v26-v8-resident-exit-audit",generation:19,parentIds:["v26-v8-resident-exit"],createdBy:"quant-regime",family:"relative_strength",thesis:"Audit the frozen V26/V8 portfolio construction without changing signal, sizing, or exit behavior.",symbols:[...UNIVERSE],parameters:{timeframeHours:2,leverage:1,riskPerTradePct:3.19,maxMarginUsagePct:100,btcRegimeSmaBars:53,btcRegimeMomentumBars:52,regimeThresholdPct:0.0377,momentumBars:45,breakoutBars:18,breakoutBufferPct:0.0233,minimumMomentumPct:0.0227,minimumVolumeRatio:0.9845,minimumEdgeToCostRatio:6.0879,volatilityLookbackBars:15,volatilityPenalty:2.3953,atrBars:31,stopAtr:2.477,takeProfitAtr:3.1995,trailingAtr:0.4,maxHoldBars:23,rebalanceBars:20,cooldownBars:1,allowLong:true,allowShort:true,allowNeutralRegime:true,neutralScoreThreshold:1.4649}};

type Bar={ts:number;open:number;high:number;low:number;close:number;volume:number};
type Candidate={symbol:string;side:"long"|"short";score:number;atr:number;signalTs:number};
type Prepared={bySymbol:Record<string,Bar[]>;indexBySymbolAndTs:Record<string,Map<number,number>>;timeline:number[]};
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const median=(xs:number[])=>{if(!xs.length)return 0;const s=[...xs].sort((a,b)=>a-b);const m=Math.floor(s.length/2);return s.length%2?s[m]!:((s[m-1]??0)+(s[m]??0))/2};
function sd(xs:number[]){if(xs.length<2)return 0;const m=mean(xs);return Math.sqrt(Math.max(0,xs.reduce((s,x)=>s+(x-m)**2,0)/(xs.length-1)))}
function resample(rows:Bar[],hours:number){const ms=hours*HOUR,b=new Map<number,Bar>();for(const r of rows){const ts=Math.floor(r.ts/ms)*ms,e=b.get(ts);if(!e)b.set(ts,{...r,ts});else{e.high=Math.max(e.high,r.high);e.low=Math.min(e.low,r.low);e.close=r.close;e.volume+=r.volume}}return [...b.values()].sort((a,c)=>a.ts-c.ts)}
function prepare(data:PerpMarketData):Prepared{const bySymbol:Record<string,Bar[]>={},indexBySymbolAndTs:Record<string,Map<number,number>>={};for(const [s,rows] of Object.entries(data.bySymbol)){const bars=resample(rows as Bar[],V26.parameters.timeframeHours);bySymbol[s]=bars;indexBySymbolAndTs[s]=new Map(bars.map((b,i)=>[b.ts,i]))}return{bySymbol,indexBySymbolAndTs,timeline:(bySymbol.BTC??[]).map(b=>b.ts)}}
function sma(b:Bar[],i:number,n:number){if(i-n+1<0)return null;return mean(b.slice(i-n+1,i+1).map(x=>x.close))}
function mom(b:Bar[],i:number,n:number){const p=b[i-n],c=b[i];return !p||!c||p.close<=0?null:c.close/p.close-1}
function vol(b:Bar[],i:number,n:number){if(i-n<0)return null;const x:number[]=[];for(let j=i-n+1;j<=i;j++){const c=b[j],p=b[j-1];if(!c||!p||c.close<=0||p.close<=0)return null;x.push(Math.log(c.close/p.close))}return sd(x)}
function atr(b:Bar[],i:number,n:number){if(i-n<0)return null;const x:number[]=[];for(let j=i-n+1;j<=i;j++){const c=b[j],p=b[j-1];if(!c||!p)return null;x.push(Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close)))}return mean(x)}
function volumeRatio(b:Bar[],i:number,n=20){if(i-n<0)return null;const c=b[i],base=mean(b.slice(i-n,i).map(x=>x.volume));return !c||base<=0?null:c.volume/base}
function candidatesAt(p:Prepared,ts:number):Candidate[]{const q=V26.parameters,bb=p.bySymbol.BTC,bi=p.indexBySymbolAndTs.BTC?.get(ts);if(!bb||bi==null)return[];const bs=sma(bb,bi,q.btcRegimeSmaBars),bm=mom(bb,bi,q.btcRegimeMomentumBars),bar=bb[bi];if(!bar||bs==null||bm==null||bs<=0)return[];const dist=bar.close/bs-1,longReg=dist>=q.regimeThresholdPct&&bm>0,shortReg=dist<=-q.regimeThresholdPct&&bm<0,neutral=!longReg&&!shortReg;const fixed=((NORMAL.feeBpsPerSide+NORMAL.slippageBpsPerSide)*2)/10000;const expectedHours=Math.max(1,Math.min(q.maxHoldBars,24))*q.timeframeHours;const minMove=(fixed+(NORMAL.adverseFundingBpsPer8h/10000)*(expectedHours/8))*q.minimumEdgeToCostRatio;const out:Candidate[]=[];for(const s of V26.symbols){const bars=p.bySymbol[s],i=p.indexBySymbolAndTs[s]?.get(ts);if(!bars||i==null)continue;const c=bars[i],m=mom(bars,i,q.momentumBars),v=vol(bars,i,q.volatilityLookbackBars),a=atr(bars,i,q.atrBars),vr=volumeRatio(bars,i);if(!c||m==null||v==null||a==null||vr==null||c.close<=0)continue;if(vr<q.minimumVolumeRatio||Math.abs(m)<minMove)continue;const scale=Math.max(.0001,v*Math.sqrt(q.momentumBars)),normalized=m/scale,score=normalized/(1+q.volatilityPenalty*v*100);const longOk=q.allowLong&&m>=q.minimumMomentumPct,shortOk=q.allowShort&&m<=-q.minimumMomentumPct;if(longOk&&(longReg||(neutral&&q.allowNeutralRegime&&score>=q.neutralScoreThreshold)))out.push({symbol:s,side:"long",score,atr:a,signalTs:ts});if(shortOk&&(shortReg||(neutral&&q.allowNeutralRegime&&-score>=q.neutralScoreThreshold)))out.push({symbol:s,side:"short",score:-score,atr:a,signalTs:ts})}return out.sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol))}
function pf(ts:PerpTrade[]){const gp=ts.filter(t=>t.netPnl>0).reduce((s,t)=>s+t.netPnl,0),gl=Math.abs(ts.filter(t=>t.netPnl<0).reduce((s,t)=>s+t.netPnl,0));return gl>0?gp/gl:gp>0?99:0}
function bySymbol(trades:PerpTrade[]){const totalNet=trades.reduce((s,t)=>s+t.netPnl,0);return Object.fromEntries(UNIVERSE.map(symbol=>{const x=trades.filter(t=>t.symbol===symbol),lev=x.map(t=>t.effectiveLeverage*100),net=x.reduce((s,t)=>s+t.netPnl,0);return[symbol,{tradeCount:x.length,longTrades:x.filter(t=>t.side==="long").length,shortTrades:x.filter(t=>t.side==="short").length,wins:x.filter(t=>t.netPnl>0).length,winRatePct:x.length?100*x.filter(t=>t.netPnl>0).length/x.length:0,profitFactor:pf(x),netPnl:net,pnlContributionPct:totalNet!==0?100*net/totalNet:0,avgCapitalUsagePct:mean(lev),medianCapitalUsagePct:median(lev),minCapitalUsagePct:lev.length?Math.min(...lev):0,maxCapitalUsagePct:lev.length?Math.max(...lev):0,avgHoldingBars:mean(x.map(t=>t.holdingBars))}]}))}
function auditWindow(label:string,startTs:number,endTs:number,data:PerpMarketData,p:Prepared){const original=runPerpBacktest({genome:V26,data,window:{label,startTs,endTs},execution:NORMAL,targetMonthlyReturnPct:TARGET_MONTHLY});const decisionCounts=Object.fromEntries(UNIVERSE.map(s=>[s,{eligibleOnOrderDecisions:0,selectedOrders:0,lostToHigherRank:0}]));let simultaneousOrderDecisionBars=0,maxCandidatesOnOrderDecision=0,selectionMismatch=0;const overlapDepthOnOrderDecisions:Record<string,number>={};for(const t of original.trades){const decisionTs=t.entryTs-V26.parameters.timeframeHours*HOUR,c=candidatesAt(p,decisionTs);maxCandidatesOnOrderDecision=Math.max(maxCandidatesOnOrderDecision,c.length);overlapDepthOnOrderDecisions[String(c.length)]=(overlapDepthOnOrderDecisions[String(c.length)]??0)+1;if(c.length>=2)simultaneousOrderDecisionBars++;for(const z of c)(decisionCounts[z.symbol] as any).eligibleOnOrderDecisions++;const top=c[0];if(top?.symbol===t.symbol&&top.side===t.side)(decisionCounts[t.symbol] as any).selectedOrders++;else selectionMismatch++;for(const z of c.slice(1))(decisionCounts[z.symbol] as any).lostToHigherRank++}
 const allCounts=Object.fromEntries(UNIVERSE.map(s=>[s,{eligibleBars:0,topRankBars:0,rankLossBars:0}]));let allSignalBars=0,allOverlapBars=0,maxCandidatesAnyBar=0;const depth:Record<string,number>={};for(const ts of p.timeline){if(ts<startTs||ts>=endTs)continue;const c=candidatesAt(p,ts);if(!c.length)continue;allSignalBars++;maxCandidatesAnyBar=Math.max(maxCandidatesAnyBar,c.length);depth[String(c.length)]=(depth[String(c.length)]??0)+1;if(c.length>=2)allOverlapBars++;for(const z of c)(allCounts[z.symbol] as any).eligibleBars++;if(c[0])(allCounts[c[0].symbol] as any).topRankBars++;for(const z of c.slice(1))(allCounts[z.symbol] as any).rankLossBars++}
 const sorted=[...original.trades].sort((a,b)=>a.entryTs-b.entryTs||a.exitTs-b.exitTs);let overlapTradePairs=0;for(let i=1;i<sorted.length;i++)if(sorted[i]!.entryTs<sorted[i-1]!.exitTs)overlapTradePairs++;
 const lev=original.trades.map(t=>t.effectiveLeverage*100);const stressedNoDelay=replayWithLatencyStress({original,data,startTs,endTs,mode:"none",stress:STRESS}),entryDelayResidentExit=replayWithLatencyStress({original,data,startTs,endTs,mode:"entry",stress:STRESS});return{window:{label,startTs,endTs},portfolio:normalBacktestSummary(original),residentExecutionStress:{noDelay:stressedNoDelay,entryDelayResidentExit},capitalUsage:{formula:"min(balance*riskPerTradePct/stopDistancePct, balance*leverage*maxMarginUsagePct)",riskPerTradePct:V26.parameters.riskPerTradePct,leverage:V26.parameters.leverage,maxMarginUsagePct:V26.parameters.maxMarginUsagePct,averagePct:mean(lev),medianPct:median(lev),minimumPct:lev.length?Math.min(...lev):0,maximumPct:lev.length?Math.max(...lev):0},concurrency:{engineMaximumOpenPositions:1,actualOverlappingTradePairs:overlapTradePairs,simultaneousOrderDecisionBars,totalOrders:original.trades.length,simultaneousOrderDecisionPct:original.trades.length?100*simultaneousOrderDecisionBars/original.trades.length:0,maxCandidatesOnOrderDecision,overlapDepthOnOrderDecisions,selectionMismatch},signalCompetitionAllBars:{signalBars:allSignalBars,overlapBars:allOverlapBars,overlapPct:allSignalBars?100*allOverlapBars/allSignalBars:0,maxCandidatesAnyBar,depth,bySymbol:allCounts},orderDecisionCompetitionBySymbol:decisionCounts,performanceBySymbol:bySymbol(original.trades)} }
async function main(){if(UNIVERSE.length!==14||UNIVERSE.includes("PENGU")||V26.parameters.leverage!==1)throw new Error("AUDIT_BOUNDARY_FAIL");const data=await loadPerpMarketData({symbols:UNIVERSE,startTs:WARMUP_START,endTs:END+2*HOUR}),p=prepare(data);const development=auditWindow("development",START,DEV_END,data,p),validation=auditWindow("validation",DEV_END,VAL_END,data,p),evaluation=auditWindow("evaluation",VAL_END,END,data,p),combined3Y=auditWindow("combined3y",START,END,data,p);if(combined3Y.concurrency.selectionMismatch!==0)throw new Error(`SELECTION_PARITY_FAIL:${combined3Y.concurrency.selectionMismatch}`);if(combined3Y.concurrency.actualOverlappingTradePairs!==0)throw new Error("TRADE_OVERLAP_FAIL");const out={researchLine:"V26_V8_PORTFOLIO_OVERLAP_AUDIT",researchOnly:true,productionChanged:false,vpsChanged:false,liveChanged:false,realTradingEnabled:false,penguExcluded:true,leverage:1,universe:UNIVERSE,signalSemantics:{family:V26.family,timeframeHours:2,importantNote:"breakoutBars/buffer are present in the genome but are NOT gating conditions for relative_strength family; engine only requires breakout for breakout or dual_direction families.",parameters:V26.parameters},development,validation,evaluation,combined3Y};const dir=process.env.RESEARCH_STATE_DIR||".research-state";await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"v26-v8-portfolio-audit.json"),JSON.stringify(out,null,2)+"\n","utf8");console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
