import fs from "fs/promises";
import path from "path";

import { loadPerpMarketData } from "../lib/research-lab/perp/data-store";
import type { Candle1h } from "../lib/backtest/types";

const HOUR=60*60*1000, BAR_HOURS=12, BAR_MS=BAR_HOURS*HOUR;
const START=Date.UTC(2023,6,1), DEV_END=Date.UTC(2024,6,1), VAL_END=Date.UTC(2025,6,1), END=Date.UTC(2026,6,1);
const NORMAL_BPS=10, STRESS_BPS=30, STRESS_DELAY_HOURS=1;
const LOOKBACK=50, BREAKOUT_BARS=20, HOLD_BARS=7; // 84H
const SYMBOLS=["BTC","ETH","BNB","SOL","LINK","AVAX","DOGE","INJ","PENGU"] as const;
type S=typeof SYMBOLS[number];
type B={ts:number;open:number;high:number;low:number;close:number;volume:number};
type F={close:number;sma50:number;momentum20:number;normalizedMomentum20:number;priorHigh20:number};
type T={symbol:S;side:"LONG";sideSign:1;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;grossReturnPct:number;netReturnPct:number;entryScore:number;exitReason:string;holdingHours:number};

const avg=(a:number[])=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);
function stdev(a:number[]){if(a.length<2)return 0;const m=avg(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function med(a:number[]){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function profitFactor(a:number[]){const g=a.filter(x=>x>0).reduce((x,y)=>x+y,0),l=Math.abs(a.filter(x=>x<0).reduce((x,y)=>x+y,0));return l<=1e-12?(g>0?999:null):g/l}
function resample(rows:Candle1h[]){const m=new Map<number,Candle1h[]>();for(const r of rows){const k=Math.floor(r.ts/BAR_MS)*BAR_MS,v=m.get(k)||[];v.push(r);m.set(k,v)}const out:B[]=[];for(const [k,v0] of [...m].sort((a,b)=>a[0]-b[0])){const v=[...v0].sort((a,b)=>a.ts-b.ts);if(v.length<10)continue;out.push({ts:k+BAR_MS,open:v[0].open,high:Math.max(...v.map(r=>r.high)),low:Math.min(...v.map(r=>r.low)),close:v.at(-1)!.close,volume:v.reduce((s,r)=>s+(r.volume||0),0)})}return out}
function features(b:B[]){const o=new Map<number,F>(),c=b.map(x=>x.close),r=[0];for(let i=1;i<b.length;i++)r.push(c[i]/c[i-1]-1);for(let i=LOOKBACK-1;i<b.length;i++){if(i<BREAKOUT_BARS)continue;const sma50=avg(c.slice(i-LOOKBACK+1,i+1)),mom=c[i]/c[i-BREAKOUT_BARS]-1,vol=stdev(r.slice(i-BREAKOUT_BARS+1,i+1)),norm=vol>1e-12?mom/(vol*Math.sqrt(BREAKOUT_BARS)):0,priorHigh=Math.max(...b.slice(i-BREAKOUT_BARS,i).map(x=>x.high));o.set(b[i].ts,{close:c[i],sma50,momentum20:mom,normalizedMomentum20:norm,priorHigh20:priorHigh})}return o}
function idx(rows:Candle1h[]){return new Map(rows.map((r,i)=>[r.ts,i]))}
function metric(tr:T[],start:number,end:number,dd:number){const v=tr.map(t=>t.netReturnPct);let e=1;for(const x of v)e*=Math.max(.000001,1+x/100);const yrs=(end-start)/(365.25*24*HOUR),wo=[...v];if(wo.length)wo.splice(wo.indexOf(Math.max(...wo)),1);const wins=v.filter(x=>x>0);return{trades:v.length,returnPct:(e-1)*100,cagrPct:(e**(1/yrs)-1)*100,pf:profitFactor(v),pfWithoutBest:profitFactor(wo),maxDDPct:dd,winRatePct:v.length?v.filter(x=>x>0).length/v.length*100:null,medianTradePct:med(v),bestWinningTradeShareOfGrossWins:wins.length?Math.max(...wins)/wins.reduce((a,b)=>a+b,0):0,symbolContributionPctPoints:Object.fromEntries(SYMBOLS.map(s=>[s,tr.filter(t=>t.symbol===s).reduce((a,t)=>a+t.netReturnPct,0)])),exitReasons:Object.fromEntries([...new Set(tr.map(t=>t.exitReason))].sort().map(x=>[x,tr.filter(t=>t.exitReason===x).length]))}}
function gate(c:any,s:any,a:Record<string,any>,as:Record<string,any>){const y=Object.values(a).map((x:any)=>x.returnPct),ys=Object.values(as).map((x:any)=>x.returnPct);const checks={everyAnnualAtLeast80:y.every(x=>x>=80),medianAnnualAtLeast100:med(y)>=100,cagrAtLeast100:c.cagrPct>=100,pfAtLeast1p40:(c.pf||0)>=1.4,pfWithoutBestAtLeast1p25:(c.pfWithoutBest||0)>=1.25,maxDDNoWorseThan40:c.maxDDPct>=-40,tradesAtLeast24:c.trades>=24,stressCagrAtLeast45:s.cagrPct>=45,stressPfAtLeast1p08:(s.pf||0)>=1.08,stressPfWithoutBestAtLeast1:(s.pfWithoutBest||0)>=1,stressDDNoWorseThan50:s.maxDDPct>=-50,atLeastTwoStressPositiveYears:ys.filter(x=>x>0).length>=2,worstStressYearAboveMinus25:Math.min(...ys)>-25};return{checks,historicalCandidatePass:Object.values(checks).every(Boolean)}}

async function simulate(data:Awaited<ReturnType<typeof loadPerpMarketData>>,f:Record<S,Map<number,F>>,start:number,end:number,cost:number,delay:number){const ix=Object.fromEntries(SYMBOLS.map(s=>[s,idx(data.bySymbol[s]||[])])) as Record<S,Map<number,number>>,times=[...f.BTC.keys()].filter(t=>t>=start&&t<end).sort((a,b)=>a-b);let eq=1,peak=1,dd=0,pos:null|{symbol:S;entryTs:number;entryPrice:number;entryScore:number;entryEq:number;releaseTs:number}=null;const tr:T[]=[];
 const mark=(ts:number)=>{if(!pos){peak=Math.max(peak,eq);dd=Math.min(dd,(eq/peak-1)*100);return}const j=ix[pos.symbol].get(ts-HOUR);if(j==null)return;const px=data.bySymbol[pos.symbol][j].close,m=pos.entryEq*Math.max(.000001,px/pos.entryPrice);peak=Math.max(peak,m);dd=Math.min(dd,(m/peak-1)*100)};
 const close=(ts:number,reason:string)=>{if(!pos)return;const et=ts+delay*HOUR,j=ix[pos.symbol].get(et);if(j==null)return;const px=data.bySymbol[pos.symbol][j].open,g=(px/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,side:"LONG",sideSign:1,entryTs:pos.entryTs,exitTs:et,entryPrice:pos.entryPrice,exitPrice:px,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,exitReason:reason,holdingHours:Math.round((et-pos.entryTs)/HOUR)});pos=null;peak=Math.max(peak,eq);dd=Math.min(dd,(eq/peak-1)*100)};
 const open=(ts:number,c:{symbol:S;score:number})=>{const et=ts+delay*HOUR,j=ix[c.symbol].get(et);if(j==null)return;pos={symbol:c.symbol,entryTs:et,entryPrice:data.bySymbol[c.symbol][j].open,entryScore:c.score,entryEq:eq,releaseTs:ts+HOLD_BARS*BAR_MS}};
 for(const ts of times){mark(ts);if(pos&&ts>=pos.releaseTs)close(ts,"FIXED_84H_RELEASE");if(pos)continue;const cand:{symbol:S;score:number}[]=[];for(const s of SYMBOLS){const x=f[s]?.get(ts);if(!x)continue;if(x.close>x.sma50&&x.momentum20>0&&x.close>x.priorHigh20)cand.push({symbol:s,score:x.normalizedMomentum20})}cand.sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));if(cand[0])open(ts,cand[0])}
 if(pos){const last=(data.bySymbol[pos.symbol]||[]).filter(r=>r.ts>=start&&r.ts<end).at(-1);if(last){const g=(last.close/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,side:"LONG",sideSign:1,entryTs:pos.entryTs,exitTs:last.ts,entryPrice:pos.entryPrice,exitPrice:last.close,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,exitReason:"PERIOD_END",holdingHours:Math.round((last.ts-pos.entryTs)/HOUR)})}}
 return{metric:metric(tr,start,end,dd),trades:tr}}

async function main(){const data=await loadPerpMarketData({symbols:[...SYMBOLS],startTs:START-40*24*HOUR,endTs:END}),bars=Object.fromEntries(SYMBOLS.map(s=>[s,resample(data.bySymbol[s]||[])])) as Record<S,B[]>,f=Object.fromEntries(SYMBOLS.map(s=>[s,features(bars[s])])) as Record<S,Map<number,F>>,periods={development:[START,DEV_END],validation:[DEV_END,VAL_END],evaluation:[VAL_END,END]} as const,annual:Record<string,any>={},annualStress:Record<string,any>={};for(const [k,[a,b]] of Object.entries(periods)){annual[k]=(await simulate(data,f,a,b,NORMAL_BPS,0)).metric;annualStress[k]=(await simulate(data,f,a,b,STRESS_BPS,STRESS_DELAY_HOURS)).metric}const c=await simulate(data,f,START,END,NORMAL_BPS,0),s=await simulate(data,f,START,END,STRESS_BPS,STRESS_DELAY_HOURS),g=gate(c.metric,s.metric,annual,annualStress),coverage=Object.fromEntries(SYMBOLS.map(x=>[x,{hourlyBars:(data.bySymbol[x]||[]).filter(r=>r.ts>=START&&r.ts<END).length,firstTs:data.bySymbol[x]?.[0]?.ts??null,lastTs:data.bySymbol[x]?.at(-1)?.ts??null}])),out={researchLine:"PORTFOLIO_PROFIT_ENGINE_V24_DYNAMIC_NARROW_BREAKOUT",researchOnly:true,productionChanged:false,vpsChanged:false,liveChanged:false,realTradingEnabled:false,liveEligible:false,freshOosRead:false,freshOosConsumed:false,freshOosPermission:g.historicalCandidatePass,target:{main3YCagrPct:100,progressFloorCagrPct:80,grossExposureCapPct:100,leverageMultiplier:1},architecture:"Dynamic 9-asset universe -> common 20x12H Donchian breakout + SMA50 + positive momentum -> strongest normalized momentum -> fixed 84H ownership",universe:SYMBOLS,dynamicListingPolicy:"participates only after own 50 completed 12H bars",antiOverfit:{parameterGrid:false,perSymbolParameters:false,yearSpecificParameters:false,validationUsedForSelection:false,evaluationUsedForSelection:false,freshOosUsedForTuning:false,leverageUsedToReachTarget:false},costs:{normalTotalBpsPerRoundTrip:NORMAL_BPS,stressTotalBpsPerRoundTrip:STRESS_BPS,stressExtraDelayHours:STRESS_DELAY_HOURS},periods,coverage,annual,annualStress,combined3Y:c.metric,combined3YStress:s.metric,historicalGate:g};const root=process.env.RESEARCH_STATE_DIR||".research-state";await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,"portfolio-profit-engine-v24.json"),JSON.stringify(out,null,2));await fs.writeFile(path.join(root,"portfolio-profit-engine-v24-trades.jsonl"),c.trades.map(t=>JSON.stringify(t)).join("\n")+"\n");console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
