import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

import { PENGU_DUAL_LS_V2 } from "../config/penguDualLsV2Runtime";
import {
  buildPenguDualLsV2EvaluationSeries,
  evaluatePenguDualLsV2PositionBar,
  targetGrossForAtr,
  type PenguDualLsV2History,
  type PenguDualLsV2Position,
  type PenguDualLsV2EvaluationRow,
} from "../lib/pengu-dual-ls-v2";
import type { DisDexV35Candle } from "../lib/disdex-v35-signal-engine";

const HOUR=3_600_000;
const WARM_START=Date.parse("2025-08-01T00:00:00Z");
const EVAL_START=Date.parse("2025-08-23T15:00:00Z");
const EVAL_END=Date.parse("2026-08-23T15:00:00Z");
const BASE_URL="https://fapi.asterdex.com";
const BASE_FEE_PER_SIDE=0.0006, STRESS_SLIPPAGE_PER_SIDE=0.0035;

type Mode="normal"|"stress";
type Side="L"|"S";
type ExitReason="hard"|"trail"|"time"|"shadow_preempt";
type Variant="PRICE_BRANCH"|"BREAKDOWN_RECLAIM"|"RELATIVE_BRANCH";
interface FundingPoint{fundingTime:number;fundingRate:number}
interface BaselineTrade{side:Side;signalTs:number;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;requestedGross:number;accountReturn:number;netUnitReturn:number;exitReason:"hard"|"trail"|"time"}
interface Campaign{variant:Variant;shadowSide:Side;signalTs:number;entryTs:number;exitTs:number;accountReturn:number;flipped:boolean;shortLegReturn?:number;longLegReturn?:number;exitReason:ExitReason}

function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function fetchJson(url:URL){let last:unknown;for(let a=0;a<6;a++){try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"DisDex-PENGU-Short-Bifurcation-V4/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,200)}`);const j=await r.json();if(!Array.isArray(j))throw new Error("not array");return j as unknown[];}catch(e){last=e;await sleep(400*(a+1));}}throw last;}
async function downloadCandles(symbol:string){const raws:unknown[][]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/klines",BASE_URL);u.searchParams.set("symbol",symbol);u.searchParams.set("interval","1h");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1500");const b=await fetchJson(u) as unknown[][];if(!b.length)break;raws.push(...b);const n=Number(b.at(-1)?.[0])+HOUR;if(!(n>cursor))throw new Error("pagination");cursor=n;await sleep(40);}const m=new Map<number,DisDexV35Candle>();for(const x of raws){const t=Number(x[0]);const c={openTime:t,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),closeTime:Number(x[6]??t+HOUR-1)};if(t>=WARM_START&&t<EVAL_END&&Object.values(c).every(Number.isFinite))m.set(t,c);}return [...m.values()].sort((a,b)=>a.openTime-b.openTime);}
async function downloadFunding(){const out:FundingPoint[]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/fundingRate",BASE_URL);u.searchParams.set("symbol","PENGUUSDT");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1000");const b=await fetchJson(u) as Array<{fundingTime?:unknown;fundingRate?:unknown}>;if(!b.length)break;for(const x of b){const t=Number(x.fundingTime),r=Number(x.fundingRate);if(t>=WARM_START&&t<EVAL_END&&Number.isFinite(r))out.push({fundingTime:t,fundingRate:r});}const n=Number(b.at(-1)?.fundingTime)+1;if(!(n>cursor))throw new Error("funding pagination");cursor=n;await sleep(40);}return [...new Map(out.map(x=>[x.fundingTime,x])).values()].sort((a,b)=>a.fundingTime-b.fundingTime);}
function fundingBetween(p:FundingPoint[],a:number,b:number){return p.filter(x=>x.fundingTime>a&&x.fundingTime<=b).reduce((s,x)=>s+x.fundingRate,0);}

function replayBaseline(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:BaselineTrade[]=[];const cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0);let i=250,cooldown=-1;while(i<rows.length-2){if(i<=cooldown){i++;continue;}const side:Side|undefined=rows[i].shortSignal?"S":rows[i].longSignal?"L":undefined;if(!side||!rows[i].features){i++;continue;}const ei=i+1,entry=rows[ei].candle,gross=targetGrossForAtr(rows[i].features!.atr24Ratio);let pos:PenguDualLsV2Position={side:side==="L"?1:-1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross,highWaterMark:entry.open,lowWaterMark:entry.open};const hold=side==="L"?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,ei+hold-1);let xi=last,xp=rows[last].candle.close,reason:"hard"|"trail"|"time"="time";for(let c=ei;c<=last;c++){const f=rows[c].features;assert(f);const ev=evaluatePenguDualLsV2PositionBar(pos,f);pos=ev.updatedPosition;if(ev.exit){xi=c;xp=ev.exit.stopPrice??rows[c].candle.close;reason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const xt=rows[xi].candle.openTime,raw=side==="L"?xp/entry.open-1:entry.open/xp-1,fr=fundingBetween(funding,entry.openTime,xt),fundRet=side==="L"?-fr:fr,net=raw+fundRet-2*cps;trades.push({side,signalTs:rows[i].candle.openTime,entryTs:entry.openTime,exitTs:xt,entryPrice:entry.open,exitPrice:xp,requestedGross:gross,accountReturn:gross*net,netUnitReturn:net,exitReason:reason});}cooldown=xi+PENGU_DUAL_LS_V2.cooldownHours;i=xi+1;}return trades;}

function shouldKeepShort(variant:Variant,signalRow:PenguDualLsV2EvaluationRow,firstBar:PenguDualLsV2EvaluationRow){assert(signalRow.features);if(variant==="PRICE_BRANCH")return firstBar.candle.close<signalRow.candle.close;if(variant==="BREAKDOWN_RECLAIM")return firstBar.candle.close<signalRow.features.previousLow;const p=firstBar.candle.close/signalRow.candle.close-1,b=firstBar.btcCandle.close/signalRow.btcCandle.close-1;return p<0&&p<b;}
function nextShadowEntry(base:BaselineTrade[],ts:number){return base.find(t=>t.entryTs>ts)?.entryTs;}
function campaignMetrics(ts:Campaign[]){let eq=1,peak=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{campaigns:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?ts.filter(t=>t.accountReturn>0).length/ts.length*100:null,profitFactor:gl>0?gp/gl:null,maxDrawdownPct:dd*100,flips:ts.filter(t=>t.flipped).length,executionLegs:ts.length+ts.filter(t=>t.flipped).length};}
function baselineMetrics(ts:BaselineTrade[]){let eq=1,peak=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{campaigns:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?ts.filter(t=>t.accountReturn>0).length/ts.length*100:null,profitFactor:gl>0?gp/gl:null,maxDrawdownPct:dd*100,flips:0,executionLegs:ts.length};}
function foldName(ts:number){const a=Date.parse("2025-12-23T15:00:00Z"),b=Date.parse("2026-04-23T15:00:00Z");return ts<a?"EARLY":ts<b?"MID":"LATE";}

function replayVariant(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],base:BaselineTrade[],variant:Variant,mode:Mode){const cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0),byTs=new Map(rows.map((r,i)=>[r.candle.openTime,i])),out:Campaign[]=[];for(const t of base){if(t.side==="L"){out.push({variant,shadowSide:"L",signalTs:t.signalTs,entryTs:t.entryTs,exitTs:t.exitTs,accountReturn:t.accountReturn,flipped:false,exitReason:t.exitReason});continue;}const si=byTs.get(t.signalTs),ei=byTs.get(t.entryTs);assert(si!==undefined&&ei!==undefined);const firstBarIndex=ei,branchEntryIndex=ei+1;if(branchEntryIndex>=rows.length||t.exitTs<branchEntryIndex*0){throw new Error("unreachable");}
    const branchTs=rows[branchEntryIndex].candle.openTime;
    // If the production shadow trade already exited during the first H1 bar, there is no safe completed-bar branch decision.
    if(t.exitTs<branchTs){out.push({variant,shadowSide:"S",signalTs:t.signalTs,entryTs:t.entryTs,exitTs:t.exitTs,accountReturn:t.accountReturn,flipped:false,exitReason:t.exitReason});continue;}
    const firstBar=rows[firstBarIndex],signalRow=rows[si];
    if(shouldKeepShort(variant,signalRow,firstBar)){out.push({variant,shadowSide:"S",signalTs:t.signalTs,entryTs:t.entryTs,exitTs:t.exitTs,accountReturn:t.accountReturn,flipped:false,exitReason:t.exitReason});continue;}
    const branchEntry=rows[branchEntryIndex].candle;
    const shortFr=fundingBetween(funding,t.entryTs,branchTs),shortNet=t.entryPrice/branchEntry.open-1+shortFr-2*cps,shortRet=t.requestedGross*shortNet;
    const f0=rows[firstBarIndex].features??signalRow.features;assert(f0);const longGross=targetGrossForAtr(f0.atr24Ratio);let pos:PenguDualLsV2Position={side:1,entryTs:branchTs,entryPrice:branchEntry.open,quantity:1,gross:longGross,highWaterMark:branchEntry.open,lowWaterMark:branchEntry.open};const last=Math.min(rows.length-1,branchEntryIndex+PENGU_DUAL_LS_V2.long.maxHoldHours-1);let xi=last,xp=rows[last].candle.close,reason:ExitReason="time";for(let c=branchEntryIndex;c<=last;c++){const f=rows[c].features;if(!f)continue;const ev=evaluatePenguDualLsV2PositionBar(pos,f);pos=ev.updatedPosition;if(ev.exit){xi=c;xp=ev.exit.stopPrice??rows[c].candle.close;reason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}
    const nextEntry=nextShadowEntry(base,t.entryTs);if(nextEntry!==undefined&&nextEntry<=rows[xi].candle.openTime){const ni=byTs.get(nextEntry);assert(ni!==undefined);xi=ni;xp=rows[ni].candle.open;reason="shadow_preempt";}
    const xt=rows[xi].candle.openTime,longFr=fundingBetween(funding,branchTs,xt),longNet=xp/branchEntry.open-1-longFr-2*cps,longRet=longGross*longNet,campaignRet=(1+shortRet)*(1+longRet)-1;
    out.push({variant,shadowSide:"S",signalTs:t.signalTs,entryTs:t.entryTs,exitTs:xt,accountReturn:campaignRet,flipped:true,shortLegReturn:shortRet,longLegReturn:longRet,exitReason:reason});}
  assert.equal(out.length,base.length);return out;}

async function main(){const [pengu,btc,funding]=await Promise.all([downloadCandles("PENGUUSDT"),downloadCandles("BTCUSDT"),downloadFunding()]);const expected=Math.floor((EVAL_END-EVAL_START)/HOUR);assert.equal(pengu.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);assert.equal(btc.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);const pTs=new Set(pengu.map(x=>x.openTime)),aligned=btc.filter(x=>pTs.has(x.openTime));assert.equal(aligned.length,pengu.length);const history:PenguDualLsV2History={pengu1h:pengu,btc1h:aligned,penguFunding:funding},rows=buildPenguDualLsV2EvaluationSeries(history,EVAL_END+HOUR),variants:Variant[]=["PRICE_BRANCH","BREAKDOWN_RECLAIM","RELATIVE_BRANCH"];
  const out:any={status:"PASS_RESEARCH_ONLY",schema:"pengu-short-bifurcation-v4/v1",period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},design:{shadowClock:"current production PENGU V2 clock remains authoritative; all 32 baseline opportunities are preserved",shortCampaign:"enter every current Short exactly as today; after first completed H1 bar either keep Short or flip to Long",branchRules:{PRICE_BRANCH:"keep Short only if first H1 close remains below signal close",BREAKDOWN_RECLAIM:"keep Short only if first H1 close remains below signal-time previousLow; otherwise Failed Breakdown Long",RELATIVE_BRANCH:"keep Short only if first-H1 PENGU return is negative and weaker than BTC; otherwise Long"},flipExit:"current production PENGU Long exit engine; preempt at next shadow-clock entry"},results:{},promotion:{},safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};
  for(const mode of ["normal","stress"] as Mode[]){const base=replayBaseline(rows,funding,mode);assert.equal(base.length,32);assert.equal(base.filter(t=>t.side==="S").length,25);assert.equal(base.filter(t=>t.side==="L").length,7);for(const v of variants){const campaigns=replayVariant(rows,funding,base,v,mode),shortCampaigns=campaigns.filter(t=>t.shadowSide==="S"),folds:any={};for(const n of ["EARLY","MID","LATE"])folds[n]=campaignMetrics(shortCampaigns.filter(t=>foldName(t.entryTs)===n));out.results[v]??={};out.results[v][mode.toUpperCase()]={BASELINE:baselineMetrics(base),BASELINE_SHORT:baselineMetrics(base.filter(t=>t.side==="S")),CAMPAIGNS:campaignMetrics(campaigns),SHORT_CAMPAIGNS:campaignMetrics(shortCampaigns),SHORT_FOLDS:folds,shortOpportunitiesPreserved:shortCampaigns.length,longOpportunitiesPreserved:campaigns.filter(t=>t.shadowSide==="L").length};}}
  for(const v of variants){const n=out.results[v].NORMAL,s=out.results[v].STRESS,b=n.BASELINE,bs=s.BASELINE,c=n.CAMPAIGNS,sc=n.SHORT_CAMPAIGNS,folds=["EARLY","MID","LATE"].filter(k=>n.SHORT_FOLDS[k].flips>0).length;const pass=n.shortOpportunitiesPreserved===25&&n.longOpportunitiesPreserved===7&&sc.flips>=5&&(c.winRatePct??0)>=(b.winRatePct??0)+5&&c.returnPct>=b.returnPct&&(c.profitFactor??0)>=(b.profitFactor??0)&&c.maxDrawdownPct>=b.maxDrawdownPct&&s.CAMPAIGNS.returnPct>=bs.returnPct&&(s.CAMPAIGNS.profitFactor??0)>=(bs.profitFactor??0)&&s.CAMPAIGNS.maxDrawdownPct>=bs.maxDrawdownPct&&folds>=2;out.promotion[v]={pass,shortOpportunities:sc.campaigns,flips:sc.flips,executionLegs:c.executionLegs,shortCampaignWinRatePct:sc.winRatePct,combinedWinRatePct:c.winRatePct,combinedReturnPct:c.returnPct,combinedPF:c.profitFactor,combinedDD:c.maxDrawdownPct,foldsWithFlips:folds};}
  const outPath=process.env.PENGU_BIFURCATION_V4_OUT||".research-state/pengu-short-bifurcation-v4/result.json";await fs.mkdir(path.dirname(outPath),{recursive:true});await fs.writeFile(outPath,JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
