from pathlib import Path

TARGET=Path('.pengu-current/scripts/.research_pengu_v57.generated.ts')
src=TARGET.read_text()

old='type RecoveryYieldMode="NONE"|"BASE_LONG"|"ANY_BASE";\ntype RecoveryBtConfig={rule:RecoveryRuleName;priority:RecoveryPriority;gross:number;exit:RecoveryExitConfig;yieldMode:RecoveryYieldMode};'
new='type RecoveryYieldMode="NONE"|"BASE_LONG"|"ANY_BASE";\ntype RecoveryV7Mode="BASE"|"P5BE"|"P5BE_H4_A12_G125"|"P5BE_H4_A18_G125"|"P5BE_H4_A24_G125"|"P5BE_H4_A12_G25"|"P5BE_H4_A18_G25"|"P5BE_H4_A24_G25"|"P5BE_H45_A12_G125"|"P5BE_H45_A18_G125"|"P5BE_H45_A24_G125";\ntype RecoveryBtConfig={rule:RecoveryRuleName;priority:RecoveryPriority;gross:number;exit:RecoveryExitConfig;yieldMode:RecoveryYieldMode;v7Mode:RecoveryV7Mode};'
if old not in src: raise SystemExit('V2 RecoveryBtConfig marker missing')
src=src.replace(old,new,1)

marker='function recoveryTradeCount(trades:RichTrade[]){return trades.filter(t=>t.engineExitReason.startsWith("RECOVERY_")).length;}'
insert=r'''
type RecoveryV7Plan={protectActivationPct:number|null;partialStopPct:number|null;partialAfterHours:number|null;partialGross:number};
const RECOVERY_V7_MODES:RecoveryV7Mode[]=["BASE","P5BE","P5BE_H4_A12_G125","P5BE_H4_A18_G125","P5BE_H4_A24_G125","P5BE_H4_A12_G25","P5BE_H4_A18_G25","P5BE_H4_A24_G25","P5BE_H45_A12_G125","P5BE_H45_A18_G125","P5BE_H45_A24_G125"];
function recoveryV7Plan(mode:RecoveryV7Mode):RecoveryV7Plan{
 if(mode==="BASE")return{protectActivationPct:null,partialStopPct:null,partialAfterHours:null,partialGross:0};
 if(mode==="P5BE")return{protectActivationPct:.05,partialStopPct:null,partialAfterHours:null,partialGross:0};
 const h4=mode.includes("_H4_")&&!mode.includes("_H45_");
 const stop=h4?.04:.045;
 const after=mode.includes("_A12_")?12:mode.includes("_A18_")?18:24;
 const gross=mode.endsWith("G25")?.25:.125;
 return{protectActivationPct:.05,partialStopPct:stop,partialAfterHours:after,partialGross:gross};
}
function v7FoldEligible(c:any,p:any){return c.returnPct+1e-9>=p.returnPct-.25&&pfRatioOk(c,p,.98)&&c.maxDrawdownPct>=p.maxDrawdownPct-.5;}
'''
if marker not in src: raise SystemExit('recoveryTradeCount marker missing')
src=src.replace(marker,insert+marker,1)

old='const entryIndex=index+1,entry=rows[entryIndex].candle;let exitIndex=entryIndex,exitPrice=entry.open,engineExitReason="",exitReason:ExitGroup="time",bestFavorable=0,worstAdverse=0;let initialShortState:any=undefined;let handoffSignalIndex:number|null=null;'
new='const entryIndex=index+1,entry=rows[entryIndex].candle;let exitIndex=entryIndex,exitPrice=entry.open,engineExitReason="",exitReason:ExitGroup="time",bestFavorable=0,worstAdverse=0;let initialShortState:any=undefined;let handoffSignalIndex:number|null=null;let recoveryPartialExitIndex:number|null=null,recoveryPartialExitPrice:number|null=null,recoveryPartialExitGross=0;'
if old not in src: raise SystemExit('V2 entry variable marker missing')
src=src.replace(old,new,1)

old='const ec=cfg.exit,last=Math.min(rows.length-1,entryIndex+ec.maxHoldHours-1);exitIndex=last;exitPrice=rows[last].candle.close;engineExitReason="RECOVERY_MAX_HOLD";let highWater=entry.open;const fixedStop=entry.open*(1-ec.hardStopPct);const structural=ec.structuralBufferPct===null?-Infinity:rec!.troughClose*(1-ec.structuralBufferPct);const hardStop=Math.max(fixedStop,structural);'
new='const ec=cfg.exit,last=Math.min(rows.length-1,entryIndex+ec.maxHoldHours-1);exitIndex=last;exitPrice=rows[last].candle.close;engineExitReason="RECOVERY_MAX_HOLD";let highWater=entry.open;const v7=recoveryV7Plan(cfg.v7Mode);const fixedStop=entry.open*(1-ec.hardStopPct);const structural=ec.structuralBufferPct===null?-Infinity:rec!.troughClose*(1-ec.structuralBufferPct);const hardStop=Math.max(fixedStop,structural);const partialStop=v7.partialStopPct===null?null:entry.open*(1-v7.partialStopPct);'
if old not in src: raise SystemExit('V2 hard-stop marker missing')
src=src.replace(old,new,1)

old='for(let cursor=entryIndex;cursor<=last;cursor++){const c=rows[cursor].candle;bestFavorable=Math.max(bestFavorable,c.high/entry.open-1);worstAdverse=Math.min(worstAdverse,c.low/entry.open-1);if(c.low<=hardStop){exitIndex=cursor;exitPrice=hardStop;engineExitReason="RECOVERY_HARD_STOP";exitReason="hard";break;}const priorHigh=highWater;if(priorHigh>=entry.open*(1+ec.trailActivationPct)){const stop=priorHigh*(1-ec.trailRetracePct);if(c.low<=stop){exitIndex=cursor;exitPrice=stop;engineExitReason="RECOVERY_TRAILING_STOP";exitReason="trail";break;}}highWater=Math.max(highWater,c.high);if(cfg.yieldMode!=="NONE"&&cursor<last&&cursor+1<rows.length){const yLong=longSignalForMode(rows,cursor,baseLongMode),yShort=rows[cursor].shortSignal;const shouldYield=cfg.yieldMode==="ANY_BASE"?(yLong||yShort):yLong;if(shouldYield){handoffSignalIndex=cursor;exitIndex=cursor+1;exitPrice=rows[cursor+1].candle.open;engineExitReason=yShort&&!yLong?"RECOVERY_YIELD_SHORT":"RECOVERY_YIELD_LONG";exitReason="time";break;}}}'
new='for(let cursor=entryIndex;cursor<=last;cursor++){const c=rows[cursor].candle;bestFavorable=Math.max(bestFavorable,c.high/entry.open-1);worstAdverse=Math.min(worstAdverse,c.low/entry.open-1);const heldHours=cursor-entryIndex+1;if(partialStop!==null&&v7.partialAfterHours!==null&&recoveryPartialExitIndex===null&&heldHours>=v7.partialAfterHours&&c.low<=partialStop){recoveryPartialExitIndex=cursor;recoveryPartialExitPrice=partialStop;recoveryPartialExitGross=v7.partialGross;}if(c.low<=hardStop){exitIndex=cursor;exitPrice=hardStop;engineExitReason=recoveryPartialExitIndex!==null?"RECOVERY_DELAYED_PARTIAL_HARD_STOP":"RECOVERY_HARD_STOP";exitReason="hard";break;}const priorHigh=highWater;if(priorHigh>=entry.open*(1+ec.trailActivationPct)){const stop=priorHigh*(1-ec.trailRetracePct);if(c.low<=stop){exitIndex=cursor;exitPrice=stop;engineExitReason=recoveryPartialExitIndex!==null?"RECOVERY_DELAYED_PARTIAL_TRAIL":"RECOVERY_TRAILING_STOP";exitReason="trail";break;}}if(v7.protectActivationPct!==null&&priorHigh>=entry.open*(1+v7.protectActivationPct)&&c.low<=entry.open){exitIndex=cursor;exitPrice=entry.open;engineExitReason="RECOVERY_P5_BREAKEVEN_PROTECT";exitReason="trail";break;}highWater=Math.max(highWater,c.high);if(cfg.yieldMode!=="NONE"&&cursor<last&&cursor+1<rows.length){const yLong=longSignalForMode(rows,cursor,baseLongMode),yShort=rows[cursor].shortSignal;const shouldYield=cfg.yieldMode==="ANY_BASE"?(yLong||yShort):yLong;if(shouldYield){handoffSignalIndex=cursor;exitIndex=cursor+1;exitPrice=rows[cursor+1].candle.open;engineExitReason=yShort&&!yLong?"RECOVERY_YIELD_SHORT":"RECOVERY_YIELD_LONG";exitReason="time";break;}}}'
if old not in src: raise SystemExit('V2 recovery exit loop marker missing')
src=src.replace(old,new,1)

old='if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime,rawUnitReturn=side==="L"?exitPrice/entry.open-1:entry.open/exitPrice-1,fundingRate=fundingBetween(funding,entry.openTime,exitTs),fundingUnitReturn=side==="L"?-fundingRate:fundingRate,costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn;trades.push({side,signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn:requestedGross*netUnitReturn,exitReason,engineExitReason,sizingState:side==="S"?classifyPenguShortV20SizingState(requestedGross):undefined,counterwind:initialShortState?.counterwind,entryFeatures:{...f},mfeUnit:bestFavorable,maeUnit:worstAdverse});}'
new='if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime;let rawUnitReturn=side==="L"?exitPrice/entry.open-1:entry.open/exitPrice-1,fundingRate=fundingBetween(funding,entry.openTime,exitTs),fundingUnitReturn=side==="L"?-fundingRate:fundingRate,costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn,accountReturn=requestedGross*netUnitReturn;if(kind==="REC_L"&&recoveryPartialExitIndex!==null&&recoveryPartialExitPrice!==null&&recoveryPartialExitGross>0){const pTs=rows[recoveryPartialExitIndex].candle.openTime,pRaw=recoveryPartialExitPrice/entry.open-1,pFunding=-fundingBetween(funding,entry.openTime,pTs),pCost=-2*costPerSide,pNet=pRaw+pFunding+pCost,remainingGross=Math.max(0,cfg.gross-recoveryPartialExitGross),rRaw=exitPrice/entry.open-1,rFunding=-fundingBetween(funding,entry.openTime,exitTs),rCost=-2*costPerSide,rNet=rRaw+rFunding+rCost;accountReturn=recoveryPartialExitGross*pNet+remainingGross*rNet;rawUnitReturn=(recoveryPartialExitGross*pRaw+remainingGross*rRaw)/cfg.gross;fundingUnitReturn=(recoveryPartialExitGross*pFunding+remainingGross*rFunding)/cfg.gross;costUnitReturn=(recoveryPartialExitGross*pCost+remainingGross*rCost)/cfg.gross;netUnitReturn=accountReturn/cfg.gross;requestedGross=cfg.gross;}trades.push({side,signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn,exitReason,engineExitReason,sizingState:side==="S"?classifyPenguShortV20SizingState(requestedGross):undefined,counterwind:initialShortState?.counterwind,entryFeatures:{...f},mfeUnit:bestFavorable,maeUnit:worstAdverse});}'
if old not in src: raise SystemExit('V2 trade accounting marker missing')
src=src.replace(old,new,1)

old='for(const rule of ["R_CORE3","R_LEVEL3","R_BTC3","R_CORE2OF3"] as const)for(const priority of ["SHORT_FIRST","RECOVERY_OVER_NEW_SHORT"] as const)for(const gross of [.25,.375,.5])for(const exit of RECOVERY_EXIT_CONFIGS)for(const yieldMode of ["NONE","BASE_LONG","ANY_BASE"] as const)configs.push({rule,priority,gross,exit,yieldMode});'
new='const v7Exit=RECOVERY_EXIT_CONFIGS.find(x=>x.name==="FIXED_A6_T6_R3_H72");if(!v7Exit)throw new Error("V7 fixed exit missing");for(const v7Mode of RECOVERY_V7_MODES)configs.push({rule:"R_BTC3",priority:"SHORT_FIRST",gross:.5,exit:v7Exit,yieldMode:"BASE_LONG",v7Mode});'
if old not in src: raise SystemExit('V2 candidate generation marker missing')
src=src.replace(old,new,1)

old='const survivors=evaluated.filter(x=>x.developmentFold1Pass&&x.validationFold2Pass).sort((a,b)=>b.score-a.score);const selected=survivors[0]??null;'
new='const parent=evaluated.find(x=>x.cfg.v7Mode==="BASE");if(!parent)throw new Error("V7 parent missing");for(const x of evaluated){const pn=parent.metrics.normalFolds,ps=parent.metrics.stressFolds,m=x.metrics;x.developmentFold1Pass=v7FoldEligible(m.normalFolds.FOLD1,pn.FOLD1)&&v7FoldEligible(m.stressFolds.FOLD1,ps.FOLD1);x.validationFold2Pass=v7FoldEligible(m.normalFolds.FOLD2,pn.FOLD2)&&v7FoldEligible(m.stressFolds.FOLD2,ps.FOLD2);const rd=(m.normalFolds.FOLD1.returnPct-pn.FOLD1.returnPct)+(m.stressFolds.FOLD1.returnPct-ps.FOLD1.returnPct)+1.5*(m.normalFolds.FOLD2.returnPct-pn.FOLD2.returnPct)+(m.stressFolds.FOLD2.returnPct-ps.FOLD2.returnPct);const dd=(m.normalFolds.FOLD1.maxDrawdownPct-pn.FOLD1.maxDrawdownPct)+(m.stressFolds.FOLD1.maxDrawdownPct-ps.FOLD1.maxDrawdownPct)+(m.normalFolds.FOLD2.maxDrawdownPct-pn.FOLD2.maxDrawdownPct)+(m.stressFolds.FOLD2.maxDrawdownPct-ps.FOLD2.maxDrawdownPct);x.v7ParentScore=rd+20*dd;x.parentDeltas={fold1NormalReturn:m.normalFolds.FOLD1.returnPct-pn.FOLD1.returnPct,fold1StressReturn:m.stressFolds.FOLD1.returnPct-ps.FOLD1.returnPct,fold2NormalReturn:m.normalFolds.FOLD2.returnPct-pn.FOLD2.returnPct,fold2StressReturn:m.stressFolds.FOLD2.returnPct-ps.FOLD2.returnPct,fold1NormalDD:m.normalFolds.FOLD1.maxDrawdownPct-pn.FOLD1.maxDrawdownPct,fold1StressDD:m.stressFolds.FOLD1.maxDrawdownPct-ps.FOLD1.maxDrawdownPct,fold2NormalDD:m.normalFolds.FOLD2.maxDrawdownPct-pn.FOLD2.maxDrawdownPct,fold2StressDD:m.stressFolds.FOLD2.maxDrawdownPct-ps.FOLD2.maxDrawdownPct};}const survivors=evaluated.filter(x=>x.developmentFold1Pass&&x.validationFold2Pass).sort((a,b)=>b.v7ParentScore-a.v7ParentScore);const selected=survivors[0]??null;'
if old not in src: raise SystemExit('V2 survivor marker missing')
src=src.replace(old,new,1)

src=src.replace('schema:"pengu-recovery-integrated-backtest/v1"','schema:"pengu-recovery-integrated-backtest/v7-delayed-defense"',1)
src=src.replace('thresholdSource:"entry thresholds fixed from Fold1 recovery-label medians only"','thresholdSource:"V2 R_BTC3 entry and original +6% trail/-6% hard stop are frozen. V7 predeclares a +5% prior-high breakeven protector and delayed partial downside defense after 12/18/24h. FOLD1/FOLD2 only select; FOLD3/prior external are diagnostics."',1)
src=src.replace('recycledHoldoutNotice:"FOLD3 informed the subordinate-yield redesign; FOLD3 is diagnostic only for V2 and is NOT a fresh holdout. External forward/cross-venue validation is required before promotion."','recycledHoldoutNotice:"FOLD3 and previously observed Aug-10-to-Aug-27/cross-venue results are contaminated diagnostics for V7. They motivated the delayed-defense family and cannot be called fresh. A new future freeze is required before LIVE promotion."',1)
src=src.replace('requirements:"Normal and Severe must improve Return in Fold1 and Fold2 with >=2 recovery trades, PF >=90% baseline, DD degradation <=2pp; final requires same on untouched Fold3 plus full Normal/Severe improvement, PF >=95%, full DD degradation <=1.5pp"','requirements:"V7 compares only 11 fixed modes against the frozen V2 parent. On both FOLD1/FOLD2 Normal+Severe, Return may not trail V2 by more than 0.25pp, PF must be >=98% of V2, and DD degradation <=0.5pp. Selection score uses only FOLD1/FOLD2 return deltas plus 20x the sum of DD deltas versus V2. No FOLD3 or prior external metric enters selection."',1)
src=src.replace('decision:strictPass?"RECOVERY_SLEEVE_ROBUST_CANDIDATE":"NO_ROBUST_RECOVERY_SLEEVE_YET"','decision:strictPass?"HISTORICAL_V7_DELAYED_DEFENSE_CANDIDATE_DIAGNOSTIC_ONLY":"NO_ROBUST_RECOVERY_SLEEVE_YET"',1)

TARGET.write_text(src)
print(f'PATCHED_RECOVERY_V7_DELAYED_DEFENSE={TARGET}')
