NATIVE_V57_GROSS_MAX = 0.9375
CONTINUATION_GROSS_MAX = 0.5
RECENT_BREAKOUT_LOOKBACK_HOURS = 12
FREQUENCY_GOAL_LONG_TRADES = 20
V61_MODES = (
    'V61_BREAKOUT_RETEST',
    'V61_HIGHER_LOW_RESUME',
    'V61_CONTRACTION_BREAK',
)
