import assert from "node:assert/strict";
import fs from "node:fs/promises";import path from "node:path";
import {PENGU_DUAL_LS_V2} from "../config/penguDualLsV2Runtime";
import {buildPenguDualLsV2EvaluationSeries,evaluatePenguDualLsV2PositionBar,targetGrossForAtr,type PenguDualLsV2History,type PenguDualLsV2Position,type PenguDualLsV2EvaluationRow} from "../lib/pengu-dual-ls-v2";
import type {DisDexV35Candle} from "../lib/disdex-v35-signal-engine";
const H=3_600_000,WARM=Date.parse("2024-12-17T00:00:00Z"),START=Date.parse("2024-12-24T00:00:00Z"),END=Date.parse("2026-08-01T00:00:00Z"),BASE="https://www.okx.com",FEE=.0006,SLIP=.0035;
type Mode="normal"|"stress";type Side="L"|"S";interface Fp{fundingTime:number;fundingRate:number}interface T{side:Side;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;requestedGross:number;accountReturn:number;netUnitReturn:number;atr:number;btcDist:number;protected?:boolean}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function okx(p:string,qs:Record<string,string>){const u=new URL(p,BASE);for(const [k,v] of Object.entries(qs))u.searchParams.set(k,v);for(let a=0;a<6;a++){const r=await fetch(u,{headers:{accept:"application/json","user-agent":"DisDex-PENGU-V10-Holdout/1.0"}});if(r.ok){const j=await r.json() as any;if(j?.code==="0"&&Array.isArray(j.data))return j.data as any[];throw new Error(`OKX code=${j?.code} msg=${j?.msg}`);}await sleep(500*(a+1));}throw new Error(`OKX HTTP failure ${u}`);}
async function candles(instId:string){const by=new Map<number,DisDexV35Candle>();let cursor=END+1,last=Infinity;for(let n=0;n<220&&cursor>WARM;n++){const d=await okx('/api/v5/market/history-candles',{instId,bar:'1H',after:String(cursor),limit:'100'});if(!d.length)break;let oldest=Infinity;for(const x of d){const t=Number(x[0]);oldest=Math.min(oldest,t);if(t>=WARM&&t<END&&String(x[8]??'1')==='1')by.set(t,{openTime:t,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),closeTime:t+H-1});}if(!(oldest<last))break;last=oldest;cursor=oldest;await sleep(120);}const a=[...by.values()].sort((x,y)=>x.openTime-y.openTime);if(a.length<5000)throw new Error(`insufficient ${instId} rows=${a.length}`);return a;}
async function funding(){const by=new Map<number,Fp>();let cursor=END+1,last=Infinity;for(let n=0;n<80&&cursor>WARM;n++){const d=await okx('/api/v5/public/funding-rate-history',{instId:'PENGU-USDT-SWAP',after:String(cursor),limit:'100'});if(!d.length)break;let oldest=Infinity;for(const x of d){const t=Number(x.fundingTime),r=Number(x.fundingRate);oldest=Math.min(oldest,t);if(t>=WARM&&t<END&&Number.isFinite(r))by.set(t,{fundingTime:t,fundingRate:r});}if(!(oldest<last))break;last=oldest;cursor=oldest;await sleep(120);}return [...by.values()].sort((a,b)=>a.fundingTime-b.fundingTime);}
const fsum=(p:Fp[],a:number,b:number)=>p.filter(x=>x.fundingTime>a&&x.fundingTime<=b).reduce((s,x)=>s+x.fundingRate,0);
function replay(rows:PenguDualLsV2EvaluationRow[],fund:Fp[],mode:Mode){const out:T[]=[];const cps=FEE+(mode==='stress'?SLIP:0);let i=250,cd=-1;while(i<rows.length-2){if(i<=cd){i++;continue;}const side:Side|undefined=rows[i].shortSignal?'S':rows[i].longSignal?'L':undefined,f=rows[i].features;if(!side||!f){i++;continue;}const ei=i+1,e=rows[ei].candle,g=targetGrossForAtr(f.atr24Ratio);let p:PenguDualLsV2Position={side:side==='L'?1:-1,entryTs:e.openTime,entryPrice:e.open,quantity:1,gross:g,highWaterMark:e.open,lowWaterMark:e.open};const hold=side==='L'?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,ei+hold-1);let xi=last,xp=rows[last].candle.close;for(let j=ei;j<=last;j++){const ff=rows[j].features;assert(ff);const ev=evaluatePenguDualLsV2PositionBar(p,ff);p=ev.updatedPosition;if(ev.exit){xi=j;xp=ev.exit.stopPrice??rows[j].candle.close;break;}}if(e.openTime>=START&&e.openTime<END){const xt=rows[xi].candle.openTime,raw=side==='L'?xp/e.open-1:e.open/xp-1,fr=fsum(fund,e.openTime,xt),net=raw+(side==='L'?-fr:fr)-2*cps;out.push({side,entryTs:e.openTime,exitTs:xt,entryPrice:e.open,exitPrice:xp,requestedGross:g,accountReturn:g*net,netUnitReturn:net,atr:f.atr24Ratio,btcDist:f.btcEma168Distance});}cd=xi+PENGU_DUAL_LS_V2.cooldownHours;i=xi+1;}return out;}
function protect(t:T,rows:PenguDualLsV2EvaluationRow[],fund:Fp[],mode:Mode,by:Map<number,number>){if(t.side!=='S'||t.btcDist<0)return t;const ei=by.get(t.entryTs),xi0=by.get(t.exitTs);assert(ei!==undefined&&xi0!==undefined);const hard=PENGU_DUAL_LS_V2.short.hardStopPct,u=Math.min(t.atr,hard/2),arm=u,goal=Math.min(2*u,hard),exit=u/2,cps=FEE+(mode==='stress'?SLIP:0);let armed=false,done=false,lw=t.entryPrice;for(let i=ei;i<xi0;i++){const b=rows[i].candle;lw=Math.min(lw,b.low);const mfe=1-lw/t.entryPrice;if(!armed&&!done&&mfe>=arm)armed=true;if(armed&&mfe>=goal){done=true;armed=false;}if(armed&&!done&&(1-b.close/t.entryPrice)<=exit&&i+1<=xi0){const x=rows[i+1].candle,raw=t.entryPrice/x.open-1,fr=fsum(fund,t.entryTs,x.openTime),net=raw+fr-2*cps;return{...t,exitTs:x.openTime,exitPrice:x.open,accountReturn:t.requestedGross*net,netUnitReturn:net,protected:true};}}return t;}
function m(ts:T[]){let eq=1,pk=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;pk=Math.max(pk,eq);dd=Math.min(dd,eq/pk-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{trades:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?100*ts.filter(t=>t.accountReturn>0).length/ts.length:null,profitFactor:gl?gp/gl:null,maxDrawdownPct:100*dd,protected:ts.filter(t=>t.protected).length};}
function fold(ts:number){const q=(ts-START)/(END-START);return q<.25?'Q1':q<.5?'Q2':q<.75?'Q3':'Q4';}function wob(b:T[],c:T[]){const d=c.map((x,i)=>x.accountReturn-b[i].accountReturn);let bi=0;for(let i=1;i<d.length;i++)if(d[i]>d[bi])bi=i;const bm=m(b.filter((_,i)=>i!==bi)),cm=m(c.filter((_,i)=>i!==bi));return{returnDeltaPct:cm.returnPct-bm.returnPct,removedBestDelta:d[bi]};}
async function main(){const [p,b,f]=await Promise.all([candles('PENGU-USDT-SWAP'),candles('BTC-USDT-SWAP'),funding()]);const bt=new Map(b.map(x=>[x.openTime,x])),ba=p.map(x=>bt.get(x.openTime)).filter(Boolean) as DisDexV35Candle[];const ps=new Set(p.map(x=>x.openTime));assert.equal(ba.length,p.length);const rows=buildPenguDualLsV2EvaluationSeries({pengu1h:p,btc1h:ba,penguFunding:f} as PenguDualLsV2History,END+H),by=new Map(rows.map((r,i)=>[r.candle.openTime,i])),out:any={status:'PASS_RESEARCH_ONLY',schema:'pengu-short-v10-okx-holdout/v1',preRegisteredCandidate:{name:'BTC_NONBEAR_REGIME_ATR_PROGRESS',candidateCount:1,thresholdSweep:false,entryCountChanges:false,directionChanges:false,rule:'Only when entry-known btcEma168Distance >= 0, apply ATR_PROGRESS_1_TO_2_EXIT_0P5; otherwise baseline unchanged.'},data:{venue:'OKX',period:[new Date(START).toISOString(),new Date(END).toISOString()],penguRows:p.length,btcRows:b.length,fundingRows:f.length},results:{},safety:{mode:'RESEARCH_ONLY',ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};for(const mode of ['normal','stress'] as Mode[]){const base=replay(rows,f,mode),cand=base.map(t=>protect(t,rows,f,mode,by)),folds:any={};for(const k of ['Q1','Q2','Q3','Q4'])folds[k]={baseline:m(base.filter(t=>fold(t.entryTs)===k)),candidate:m(cand.filter(t=>fold(t.entryTs)===k))};out.results[mode.toUpperCase()]={BASELINE:m(base),CANDIDATE:m(cand),FOLDS:folds,changed:cand.filter((t,i)=>t.exitTs!==base[i].exitTs||t.exitPrice!==base[i].exitPrice).length,withoutBest:wob(base,cand)};}const n=out.results.NORMAL,s=out.results.STRESS,bm=n.BASELINE,cm=n.CANDIDATE,bsm=s.BASELINE,csm=s.CANDIDATE,fw=['Q1','Q2','Q3','Q4'].filter(k=>(n.FOLDS[k].candidate.winRatePct??0)>=(n.FOLDS[k].baseline.winRatePct??0)),fr=['Q1','Q2','Q3','Q4'].filter(k=>n.FOLDS[k].candidate.returnPct>=n.FOLDS[k].baseline.returnPct);out.promotion={pass:bm.trades>=20&&cm.trades===bm.trades&&n.changed>=2&&(cm.winRatePct??0)>=(bm.winRatePct??0)+5&&cm.returnPct>=bm.returnPct&&(cm.profitFactor??0)>=(bm.profitFactor??0)&&cm.maxDrawdownPct>=bm.maxDrawdownPct&&csm.returnPct>=bsm.returnPct&&(csm.profitFactor??0)>=(bsm.profitFactor??0)&&csm.maxDrawdownPct>=bsm.maxDrawdownPct&&n.withoutBest.returnDeltaPct>=0&&s.withoutBest.returnDeltaPct>=0&&fw.length>=3&&fr.length>=3,foldsNonWorseWinRate:fw,foldsNonWorseReturn:fr};const op=process.env.PENGU_V10_OUT||'.research-state/pengu-short-v10-okx/result.json';await fs.mkdir(path.dirname(op),{recursive:true});await fs.writeFile(op,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));}main().catch(e=>{console.error(e);process.exitCode=1;});
