import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

import { PENGU_DUAL_LS_V2 } from "../config/penguDualLsV2Runtime";
import {
  buildPenguDualLsV2EvaluationSeries,
  evaluatePenguDualLsV2PositionBar,
  targetGrossForAtr,
  type PenguDualLsV2History,
  type PenguDualLsV2Position,
  type PenguDualLsV2EvaluationRow,
} from "../lib/pengu-dual-ls-v2";
import type { DisDexV35Candle } from "../lib/disdex-v35-signal-engine";

const HOUR=3_600_000;
const WARM_START=Date.parse("2025-08-01T00:00:00Z");
const EVAL_START=Date.parse("2025-08-23T15:00:00Z");
const EVAL_END=Date.parse("2026-08-23T15:00:00Z");
const BASE_URL="https://fapi.asterdex.com";
const BASE_FEE_PER_SIDE=0.0006, STRESS_SLIPPAGE_PER_SIDE=0.0035;

type Mode="normal"|"stress";
type Side="L"|"S";
type Reason="hard"|"trail"|"time"|"progression_fail";
type Variant="PROGRESS_4_TO_8_EXIT_2"|"PROGRESS_2_TO_4_EXIT_1";
interface FundingPoint{fundingTime:number;fundingRate:number}
interface Trade{side:Side;signalTs:number;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;requestedGross:number;accountReturn:number;netUnitReturn:number;exitReason:Reason}

function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function fetchJson(url:URL){let last:unknown;for(let a=0;a<6;a++){try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"DisDex-PENGU-Short-Progression-V6/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,200)}`);const j=await r.json();if(!Array.isArray(j))throw new Error("not array");return j as unknown[];}catch(e){last=e;await sleep(400*(a+1));}}throw last;}
async function downloadCandles(symbol:string){const raws:unknown[][]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/klines",BASE_URL);u.searchParams.set("symbol",symbol);u.searchParams.set("interval","1h");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1500");const b=await fetchJson(u) as unknown[][];if(!b.length)break;raws.push(...b);const n=Number(b.at(-1)?.[0])+HOUR;if(!(n>cursor))throw new Error("pagination");cursor=n;await sleep(40);}const m=new Map<number,DisDexV35Candle>();for(const x of raws){const t=Number(x[0]);const c={openTime:t,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),closeTime:Number(x[6]??t+HOUR-1)};if(t>=WARM_START&&t<EVAL_END&&Object.values(c).every(Number.isFinite))m.set(t,c);}return [...m.values()].sort((a,b)=>a.openTime-b.openTime);}
async function downloadFunding(){const out:FundingPoint[]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/fundingRate",BASE_URL);u.searchParams.set("symbol","PENGUUSDT");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1000");const b=await fetchJson(u) as Array<{fundingTime?:unknown;fundingRate?:unknown}>;if(!b.length)break;for(const x of b){const t=Number(x.fundingTime),r=Number(x.fundingRate);if(t>=WARM_START&&t<EVAL_END&&Number.isFinite(r))out.push({fundingTime:t,fundingRate:r});}const n=Number(b.at(-1)?.fundingTime)+1;if(!(n>cursor))throw new Error("funding pagination");cursor=n;await sleep(40);}return [...new Map(out.map(x=>[x.fundingTime,x])).values()].sort((a,b)=>a.fundingTime-b.fundingTime);}
function fundingBetween(p:FundingPoint[],a:number,b:number){return p.filter(x=>x.fundingTime>a&&x.fundingTime<=b).reduce((s,x)=>s+x.fundingRate,0);}

function replayBaseline(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:Trade[]=[];const cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0);let i=250,cooldown=-1;while(i<rows.length-2){if(i<=cooldown){i++;continue;}const side:Side|undefined=rows[i].shortSignal?"S":rows[i].longSignal?"L":undefined;if(!side||!rows[i].features){i++;continue;}const ei=i+1,entry=rows[ei].candle,gross=targetGrossForAtr(rows[i].features!.atr24Ratio);let pos:PenguDualLsV2Position={side:side==="L"?1:-1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross,highWaterMark:entry.open,lowWaterMark:entry.open};const hold=side==="L"?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,ei+hold-1);let xi=last,xp=rows[last].candle.close,reason:Reason="time";for(let c=ei;c<=last;c++){const f=rows[c].features;assert(f);const ev=evaluatePenguDualLsV2PositionBar(pos,f);pos=ev.updatedPosition;if(ev.exit){xi=c;xp=ev.exit.stopPrice??rows[c].candle.close;reason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const xt=rows[xi].candle.openTime,raw=side==="L"?xp/entry.open-1:entry.open/xp-1,fr=fundingBetween(funding,entry.openTime,xt),fundRet=side==="L"?-fr:fr,net=raw+fundRet-2*cps;trades.push({side,signalTs:rows[i].candle.openTime,entryTs:entry.openTime,exitTs:xt,entryPrice:entry.open,exitPrice:xp,requestedGross:gross,accountReturn:gross*net,netUnitReturn:net,exitReason:reason});}cooldown=xi+PENGU_DUAL_LS_V2.cooldownHours;i=xi+1;}return trades;}
function metrics(ts:Trade[]){let eq=1,peak=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{trades:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?ts.filter(t=>t.accountReturn>0).length/ts.length*100:null,profitFactor:gl>0?gp/gl:null,maxDrawdownPct:dd*100,progressionExits:ts.filter(t=>t.exitReason==="progression_fail").length};}
function params(v:Variant){const h=PENGU_DUAL_LS_V2.short.hardStopPct;return v==="PROGRESS_4_TO_8_EXIT_2"?{arm:h/2,goal:h,exit:h/4}:{arm:h/4,goal:h/2,exit:h/8};}
function replayProgression(t:Trade,v:Variant,rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode,byTs:Map<number,number>){const ei=byTs.get(t.entryTs),xi0=byTs.get(t.exitTs);assert(ei!==undefined&&xi0!==undefined);const p=params(v),cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0);let armed=false,progressed=false,lowWater=t.entryPrice,xi=xi0,xp=t.exitPrice,reason:Reason=t.exitReason;for(let i=ei;i<xi0;i++){const bar=rows[i].candle;lowWater=Math.min(lowWater,bar.low);const mfe=1-lowWater/t.entryPrice;if(!armed&&mfe>=p.arm)armed=true;if(armed&&mfe>=p.goal){progressed=true;armed=false;}if(armed&&!progressed){const remainingProfit=1-bar.close/t.entryPrice;if(remainingProfit<=p.exit&&i+1<=xi0){const next=rows[i+1].candle;xi=i+1;xp=next.open;reason="progression_fail";break;}}}
  const xt=rows[xi].candle.openTime,raw=t.entryPrice/xp-1,fr=fundingBetween(funding,t.entryTs,xt),net=raw+fr-2*cps;return{...t,exitTs:xt,exitPrice:xp,netUnitReturn:net,accountReturn:t.requestedGross*net,exitReason:reason};}
function foldName(ts:number){const a=Date.parse("2025-12-23T15:00:00Z"),b=Date.parse("2026-04-23T15:00:00Z");return ts<a?"EARLY":ts<b?"MID":"LATE";}

async function main(){const [pengu,btc,funding]=await Promise.all([downloadCandles("PENGUUSDT"),downloadCandles("BTCUSDT"),downloadFunding()]);const expected=Math.floor((EVAL_END-EVAL_START)/HOUR);assert.equal(pengu.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);assert.equal(btc.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);const pTs=new Set(pengu.map(x=>x.openTime)),aligned=btc.filter(x=>pTs.has(x.openTime));assert.equal(aligned.length,pengu.length);const history:PenguDualLsV2History={pengu1h:pengu,btc1h:aligned,penguFunding:funding},rows=buildPenguDualLsV2EvaluationSeries(history,EVAL_END+HOUR),byTs=new Map(rows.map((r,i)=>[r.candle.openTime,i])),variants:Variant[]=["PROGRESS_4_TO_8_EXIT_2","PROGRESS_2_TO_4_EXIT_1"];
  const out:any={status:"PASS_RESEARCH_ONLY",schema:"pengu-short-progression-v6/v1",period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},design:{principle:"preserve all current entries and directions; only detect failure to progress after a Short has first moved favorably",fixedBeforeRun:{PROGRESS_4_TO_8_EXIT_2:"after a completed bar reaches +4% MFE, require +8% MFE before an hourly close gives back to <=+2%; otherwise exit next H1 open",PROGRESS_2_TO_4_EXIT_1:"after +2% MFE, require +4% before hourly close gives back to <=+1%; otherwise exit next H1 open"},thresholdSource:"fractions of existing production Short hardStopPct=8%; no threshold sweep",baselineExit:"unchanged unless progression failure fires first"},results:{},promotion:{},safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};
  for(const mode of ["normal","stress"] as Mode[]){const base=replayBaseline(rows,funding,mode),shorts=base.filter(t=>t.side==="S"),longs=base.filter(t=>t.side==="L");assert.equal(base.length,32);assert.equal(shorts.length,25);assert.equal(longs.length,7);for(const v of variants){const changed=shorts.map(t=>replayProgression(t,v,rows,funding,mode,byTs)),combined=[...longs,...changed],folds:any={};for(const n of ["EARLY","MID","LATE"])folds[n]=metrics(changed.filter(t=>foldName(t.entryTs)===n));out.results[v]??={};out.results[v][mode.toUpperCase()]={BASELINE:metrics(base),BASELINE_SHORT:metrics(shorts),CANDIDATE_SHORT:metrics(changed),COMBINED:metrics(combined),SHORT_FOLDS:folds,shortEntriesPreserved:changed.length,longEntriesPreserved:longs.length,changedExits:changed.filter((t,i)=>t.exitTs!==shorts[i].exitTs||t.exitPrice!==shorts[i].exitPrice).length};}}
  for(const v of variants){const n=out.results[v].NORMAL,s=out.results[v].STRESS,b=n.BASELINE,bs=s.BASELINE,x=n.COMBINED,folds=["EARLY","MID","LATE"].filter(k=>n.SHORT_FOLDS[k].progressionExits>0).length;const pass=n.shortEntriesPreserved===25&&n.longEntriesPreserved===7&&n.changedExits>=2&&(x.winRatePct??0)>=(b.winRatePct??0)+5&&x.returnPct>=b.returnPct&&(x.profitFactor??0)>=(b.profitFactor??0)&&x.maxDrawdownPct>=b.maxDrawdownPct&&s.COMBINED.returnPct>=bs.returnPct&&(s.COMBINED.profitFactor??0)>=(bs.profitFactor??0)&&s.COMBINED.maxDrawdownPct>=bs.maxDrawdownPct&&folds>=2;out.promotion[v]={pass,changedExits:n.changedExits,progressionExits:n.CANDIDATE_SHORT.progressionExits,shortWinRatePct:n.CANDIDATE_SHORT.winRatePct,combinedWinRatePct:x.winRatePct,combinedReturnPct:x.returnPct,combinedPF:x.profitFactor,combinedDD:x.maxDrawdownPct,foldsWithProgressionExits:folds};}
  const outPath=process.env.PENGU_SHORT_PROGRESSION_OUT||".research-state/pengu-short-progression-v6/result.json";await fs.mkdir(path.dirname(outPath),{recursive:true});await fs.writeFile(outPath,JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
