import fs from "fs/promises";
import path from "path";
import { loadPerpMarketData } from "../lib/research-lab/perp/data-store";
import type { Candle1h } from "../lib/backtest/types";

const HOUR=3600000,BAR_MS=12*HOUR,REBALANCE_MS=84*HOUR,START=Date.UTC(2023,6,1),DEV_END=Date.UTC(2024,6,1),VAL_END=Date.UTC(2025,6,1),END=Date.UTC(2026,6,1);
const NORMAL_BPS=10,STRESS_BPS=30,STRESS_DELAY=1,LOOKBACK=50,MOM=20;
const SYMBOLS=["BTC","ETH","BNB","SOL","LINK","AVAX","DOGE","INJ","PENGU"] as const;
type S=typeof SYMBOLS[number];
type B={ts:number;open:number;high:number;low:number;close:number;volume:number};
type F={close:number;sma50:number;momentum20:number;normalizedMomentum20:number;priorHigh20:number};
type T={symbol:S;side:"LONG";sideSign:1;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;grossReturnPct:number;netReturnPct:number;entryScore:number;entryMode:"BROAD"|"NARROW";exitReason:string;holdingHours:number};
const avg=(a:number[])=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);
function sd(a:number[]){if(a.length<2)return 0;const m=avg(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function med(a:number[]){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function pf(a:number[]){const g=a.filter(x=>x>0).reduce((x,y)=>x+y,0),l=Math.abs(a.filter(x=>x<0).reduce((x,y)=>x+y,0));return l<=1e-12?(g>0?999:null):g/l}
function resample(rows:Candle1h[]){const m=new Map<number,Candle1h[]>();for(const r of rows){const k=Math.floor(r.ts/BAR_MS)*BAR_MS,v=m.get(k)||[];v.push(r);m.set(k,v)}const out:B[]=[];for(const [k,v0] of [...m].sort((a,b)=>a[0]-b[0])){const v=[...v0].sort((a,b)=>a.ts-b.ts);if(v.length<10)continue;out.push({ts:k+BAR_MS,open:v[0].open,high:Math.max(...v.map(r=>r.high)),low:Math.min(...v.map(r=>r.low)),close:v.at(-1)!.close,volume:v.reduce((s,r)=>s+(r.volume||0),0)})}return out}
function features(b:B[]){const o=new Map<number,F>(),c=b.map(x=>x.close),ret=[0];for(let i=1;i<b.length;i++)ret.push(c[i]/c[i-1]-1);for(let i=LOOKBACK-1;i<b.length;i++){if(i<MOM)continue;const sma50=avg(c.slice(i-LOOKBACK+1,i+1)),momentum20=c[i]/c[i-MOM]-1,v=sd(ret.slice(i-MOM+1,i+1)),normalizedMomentum20=v>1e-12?momentum20/(v*Math.sqrt(MOM)):0,priorHigh20=Math.max(...b.slice(i-MOM,i).map(x=>x.high));o.set(b[i].ts,{close:c[i],sma50,momentum20,normalizedMomentum20,priorHigh20})}return o}
const hidx=(r:Candle1h[])=>new Map(r.map((x,i)=>[x.ts,i]));
function metric(tr:T[],start:number,end:number,dd:number){const v=tr.map(t=>t.netReturnPct);let eq=1;for(const x of v)eq*=Math.max(.000001,1+x/100);const yrs=(end-start)/(365.25*24*HOUR),wo=[...v];if(wo.length)wo.splice(wo.indexOf(Math.max(...wo)),1);const wins=v.filter(x=>x>0);return{trades:v.length,returnPct:(eq-1)*100,cagrPct:(eq**(1/yrs)-1)*100,pf:pf(v),pfWithoutBest:pf(wo),maxDDPct:dd,winRatePct:v.length?v.filter(x=>x>0).length/v.length*100:null,medianTradePct:med(v),bestWinningTradeShareOfGrossWins:wins.length?Math.max(...wins)/wins.reduce((a,b)=>a+b,0):0,symbolContributionPctPoints:Object.fromEntries(SYMBOLS.map(s=>[s,tr.filter(t=>t.symbol===s).reduce((a,t)=>a+t.netReturnPct,0)])),modeContributionPctPoints:{BROAD:tr.filter(t=>t.entryMode==="BROAD").reduce((a,t)=>a+t.netReturnPct,0),NARROW:tr.filter(t=>t.entryMode==="NARROW").reduce((a,t)=>a+t.netReturnPct,0)},exitReasons:Object.fromEntries([...new Set(tr.map(t=>t.exitReason))].sort().map(x=>[x,tr.filter(t=>t.exitReason===x).length]))}}
function gate(c:any,s:any,a:Record<string,any>,as:Record<string,any>){const y=Object.values(a).map((x:any)=>x.returnPct),ys=Object.values(as).map((x:any)=>x.returnPct),checks={everyAnnualAtLeast80:y.every(x=>x>=80),medianAnnualAtLeast100:med(y)>=100,cagrAtLeast100:c.cagrPct>=100,pfAtLeast1p40:(c.pf||0)>=1.4,pfWithoutBestAtLeast1p25:(c.pfWithoutBest||0)>=1.25,maxDDNoWorseThan40:c.maxDDPct>=-40,tradesAtLeast24:c.trades>=24,stressCagrAtLeast45:s.cagrPct>=45,stressPfAtLeast1p08:(s.pf||0)>=1.08,stressPfWithoutBestAtLeast1:(s.pfWithoutBest||0)>=1,stressDDNoWorseThan50:s.maxDDPct>=-50,atLeastTwoStressPositiveYears:ys.filter(x=>x>0).length>=2,worstStressYearAboveMinus25:Math.min(...ys)>-25};return{checks,historicalCandidatePass:Object.values(checks).every(Boolean)}}
function route(ts:number,f:Record<S,Map<number,F>>){const avail:{symbol:S;f:F}[]=[];for(const s of SYMBOLS){const x=f[s]?.get(ts);if(x)avail.push({symbol:s,f:x})}if(avail.length<6)return{mode:"CASH" as const,ranked:[] as {symbol:S;score:number}[]};const broad=avail.filter(x=>x.f.close>x.f.sma50&&x.f.momentum20>0);if(broad.length>avail.length/2){return{mode:"BROAD" as const,ranked:broad.map(x=>({symbol:x.symbol,score:x.f.normalizedMomentum20})).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol))}}const narrow=avail.filter(x=>x.f.close>x.f.sma50&&x.f.momentum20>0&&x.f.close>x.f.priorHigh20).map(x=>({symbol:x.symbol,score:x.f.normalizedMomentum20})).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));return narrow.length?{mode:"NARROW" as const,ranked:narrow}:{mode:"CASH" as const,ranked:[] as {symbol:S;score:number}[]}}
async function simulate(data:Awaited<ReturnType<typeof loadPerpMarketData>>,f:Record<S,Map<number,F>>,start:number,end:number,cost:number,delay:number){const ix=Object.fromEntries(SYMBOLS.map(s=>[s,hidx(data.bySymbol[s]||[])])) as Record<S,Map<number,number>>,times=[...f.BTC.keys()].filter(t=>t>=start&&t<end).sort((a,b)=>a-b);let eq=1,peak=1,dd=0,pos:null|{symbol:S;entryTs:number;entryPrice:number;entryScore:number;entryEq:number;entryMode:"BROAD"|"NARROW"}=null;const tr:T[]=[];
 const mark=(ts:number)=>{if(!pos){peak=Math.max(peak,eq);dd=Math.min(dd,(eq/peak-1)*100);return}const j=ix[pos.symbol].get(ts-HOUR);if(j==null)return;const px=data.bySymbol[pos.symbol][j].close,m=pos.entryEq*Math.max(.000001,px/pos.entryPrice);peak=Math.max(peak,m);dd=Math.min(dd,(m/peak-1)*100)};
 const close=(ts:number,reason:string)=>{if(!pos)return;const et=ts+delay*HOUR,j=ix[pos.symbol].get(et);if(j==null)return;const px=data.bySymbol[pos.symbol][j].open,g=(px/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,side:"LONG",sideSign:1,entryTs:pos.entryTs,exitTs:et,entryPrice:pos.entryPrice,exitPrice:px,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,entryMode:pos.entryMode,exitReason:reason,holdingHours:Math.round((et-pos.entryTs)/HOUR)});pos=null;peak=Math.max(peak,eq);dd=Math.min(dd,(eq/peak-1)*100)};
 const open=(ts:number,c:{symbol:S;score:number},mode:"BROAD"|"NARROW")=>{const et=ts+delay*HOUR,j=ix[c.symbol].get(et);if(j==null)return;pos={symbol:c.symbol,entryTs:et,entryPrice:data.bySymbol[c.symbol][j].open,entryScore:c.score,entryEq:eq,entryMode:mode}};
 for(const ts of times){mark(ts);if((ts-START)%REBALANCE_MS!==0)continue;const r=route(ts,f),desired=r.ranked[0]||null;if(pos&&r.mode==="BROAD"){const rank=r.ranked.findIndex(x=>x.symbol===pos!.symbol)+1;if(rank>0&&rank<=2)continue}if(pos&&desired?.symbol===pos.symbol)continue;if(pos)close(ts,desired?"SCHEDULED_ROTATION":"SCHEDULED_TO_CASH");if(!pos&&desired&&r.mode!=="CASH")open(ts,desired,r.mode)}
 if(pos){const last=(data.bySymbol[pos.symbol]||[]).filter(r=>r.ts>=start&&r.ts<end).at(-1);if(last){const g=(last.close/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,side:"LONG",sideSign:1,entryTs:pos.entryTs,exitTs:last.ts,entryPrice:pos.entryPrice,exitPrice:last.close,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,entryMode:pos.entryMode,exitReason:"PERIOD_END",holdingHours:Math.round((last.ts-pos.entryTs)/HOUR)})}}
 return{metric:metric(tr,start,end,dd),trades:tr}}
async function main(){const data=await loadPerpMarketData({symbols:[...SYMBOLS],startTs:START-40*24*HOUR,endTs:END}),bars=Object.fromEntries(SYMBOLS.map(s=>[s,resample(data.bySymbol[s]||[])])) as Record<S,B[]>,f=Object.fromEntries(SYMBOLS.map(s=>[s,features(bars[s])])) as Record<S,Map<number,F>>,periods={development:[START,DEV_END],validation:[DEV_END,VAL_END],evaluation:[VAL_END,END]} as const,annual:Record<string,any>={},annualStress:Record<string,any>={};for(const [k,[a,b]] of Object.entries(periods)){annual[k]=(await simulate(data,f,a,b,NORMAL_BPS,0)).metric;annualStress[k]=(await simulate(data,f,a,b,STRESS_BPS,STRESS_DELAY)).metric}const c=await simulate(data,f,START,END,NORMAL_BPS,0),s=await simulate(data,f,START,END,STRESS_BPS,STRESS_DELAY),g=gate(c.metric,s.metric,annual,annualStress),out={researchLine:"PORTFOLIO_PROFIT_ENGINE_V25_PREREGISTERED_DYNAMIC_ROUTER",researchOnly:true,productionChanged:false,vpsChanged:false,liveChanged:false,realTradingEnabled:false,liveEligible:false,freshOosRead:false,freshOosConsumed:false,freshOosPermission:g.historicalCandidatePass,precommit:"docs/implementation/V25_DYNAMIC_ROUTER_PRECOMMIT_20260816.md",target:{main3YCagrPct:100,progressFloorCagrPct:80,grossExposureCapPct:100,leverageMultiplier:1},architecture:"84H router: BROAD strict-majority trend/top2 retention else NARROW common 20x12H breakout else CASH",universe:SYMBOLS,antiOverfit:{parameterGrid:false,perSymbolParameters:false,yearSpecificParameters:false,validationUsedForSelection:false,evaluationUsedForSelection:false,freshOosUsedForTuning:false,leverageUsedToReachTarget:false,preregisteredBeforeV24Result:true},costs:{normalTotalBpsPerRoundTrip:NORMAL_BPS,stressTotalBpsPerRoundTrip:STRESS_BPS,stressExtraDelayHours:STRESS_DELAY},periods,annual,annualStress,combined3Y:c.metric,combined3YStress:s.metric,historicalGate:g};const root=process.env.RESEARCH_STATE_DIR||".research-state";await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,"portfolio-profit-engine-v25.json"),JSON.stringify(out,null,2));await fs.writeFile(path.join(root,"portfolio-profit-engine-v25-trades.jsonl"),c.trades.map(t=>JSON.stringify(t)).join("\n")+"\n");console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
