import fs from "fs/promises";
import { loadPerpMarketData } from "../lib/research-lab/perp/data-store";
import type { PerpBar, PerpMarketData, PerpSide } from "../lib/research-lab/perp/types";

const H=3_600_000, START=Date.UTC(2023,6,1), D=Date.UTC(2024,6,1), V=Date.UTC(2025,6,1), END=Date.UTC(2026,6,1), WARM=START-180*24*H;
const SYMS=["BTC","ETH","BNB","SOL","LINK","AVAX","DOGE","INJ","XRP","ADA","LTC","ATOM","AAVE","NEAR"];
const P={sma:53,regMom:52,regThr:.0377,mom:45,minMom:.0227,minVol:.9845,edge:6.0879,volN:15,volPen:2.3953,atrN:31,stop:2.477,tp:3.1995,trail:.4,maxHold:23,rebalance:20,cooldown:1,riskPct:3.19};
type C={symbol:string;side:PerpSide;score:number;atr:number;ts:number};
type Pos={symbol:string;side:PerpSide;entry:number;qty:number;entryFee:number;funding:number;lastFund:number;initialStop:number;stop:number;tp:number;atr:number;peak:number;trough:number;bars:number;rank:number};
type Variant={name:string;slots:1|2;slotCap:number};
type Mode={name:string;fee:number;slip:number};
type Prepared={bars:Record<string,PerpBar[]>;idx:Record<string,Map<number,number>>;timeline:number[]};
const variants:Variant[]=[{name:"current_one_slot",slots:1,slotCap:1},{name:"top2_residual",slots:2,slotCap:1},{name:"top2_split_050",slots:2,slotCap:.5}];
const modes:Mode[]=[{name:"normal",fee:5,slip:0},{name:"stress",fee:10,slip:5}];
function mean(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0} function sd(a:number[]){if(a.length<2)return NaN;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function resample(a:PerpBar[]){const out=new Map<number,PerpBar>();for(const x of a){const ts=Math.floor(x.ts/(2*H))*2*H,e=out.get(ts);if(!e)out.set(ts,{...x,ts});else{e.high=Math.max(e.high,x.high);e.low=Math.min(e.low,x.low);e.close=x.close;e.volume+=x.volume}}return [...out.values()].sort((a,b)=>a.ts-b.ts)}
function prep(d:PerpMarketData):Prepared{const bars:Record<string,PerpBar[]>={},idx:Record<string,Map<number,number>>={};for(const [s,a] of Object.entries(d.bySymbol)){bars[s]=resample(a);idx[s]=new Map(bars[s].map((x,i)=>[x.ts,i]))}return{bars,idx,timeline:(bars.BTC||[]).map(x=>x.ts)}}
function sma(b:PerpBar[],i:number,n:number){if(i<n-1)return NaN;return mean(b.slice(i-n+1,i+1).map(x=>x.close))} function mom(b:PerpBar[],i:number,n:number){return i>=n?b[i].close/b[i-n].close-1:NaN}
function atr(b:PerpBar[],i:number,n:number){if(i<n)return NaN;const a=[] as number[];for(let j=i-n+1;j<=i;j++)a.push(Math.max(b[j].high-b[j].low,Math.abs(b[j].high-b[j-1].close),Math.abs(b[j].low-b[j-1].close)));return mean(a)}
function vol(b:PerpBar[],i:number,n:number){if(i<n)return NaN;const a=[] as number[];for(let j=i-n+1;j<=i;j++)a.push(Math.log(b[j].close/b[j-1].close));return sd(a)} function vr(b:PerpBar[],i:number){if(i<20)return NaN;const m=mean(b.slice(i-20,i).map(x=>x.volume));return m>0?b[i].volume/m:NaN}
function cand(p:Prepared,ts:number):C[]{const bi=p.idx.BTC?.get(ts),btc=p.bars.BTC;if(bi==null||!btc)return[];const s=sma(btc,bi,P.sma),m=mom(btc,bi,P.regMom);if(!Number.isFinite(s)||!Number.isFinite(m))return[];const dist=btc[bi].close/s-1,long=dist>=P.regThr&&m>0,short=dist<=-P.regThr&&m<0,neutral=!long&&!short,minEdge=.001*P.edge,out:C[]=[];for(const symbol of SYMS){const i=p.idx[symbol]?.get(ts),b=p.bars[symbol];if(i==null||!b)continue;const mm=mom(b,i,P.mom),vv=vol(b,i,P.volN),aa=atr(b,i,P.atrN),rr=vr(b,i);if(![mm,vv,aa,rr].every(Number.isFinite)||rr<P.minVol||Math.abs(mm)<minEdge)continue;const score=(mm/Math.max(.0001,vv*Math.sqrt(P.mom)))/(1+P.volPen*vv*100);if(mm>=P.minMom&&(long||(neutral&&score>=1.4649)))out.push({symbol,side:"long",score,atr:aa,ts});if(mm<=-P.minMom&&(short||(neutral&&-score>=1.4649)))out.push({symbol,side:"short",score:-score,atr:aa,ts})}return out.sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol))}
function firstFund(a:{ts:number;rate:number}[],ts:number){let l=0,r=a.length;while(l<r){const m=(l+r)>>1;if(a[m].ts<=ts)l=m+1;else r=m}return l} function fund(a:{ts:number;rate:number}[],from:number,to:number){let i=firstFund(a,from),x=0;for(;i<a.length&&a[i].ts<=to;i++)x+=a[i].rate;return x}
function pf(a:number[]){const gp=a.filter(x=>x>0).reduce((s,x)=>s+x,0),gl=-a.filter(x=>x<0).reduce((s,x)=>s+x,0);return gl?gp/gl:gp?99:0} function pfwb(a:number[]){const b=[...a];if(b.length)b.splice(b.indexOf(Math.max(...b)),1);return pf(b)}
function simulate(d:PerpMarketData,p:Prepared,a:number,z:number,v:Variant,m:Mode){const fee=m.fee/10000,slip=m.slip/10000,times=p.timeline.filter(t=>t>=a&&t<z);let cash=10000,peak=10000,dd=0,gSum=0,gMax=0,obs=0,twoBars=0,rank2=0,whileHeld=0,blocked=0;const pos=new Map<string,Pos>(),pending=new Map<string,{c:C;rank:number}>(),exits=new Map<string,string>(),cool=new Map<string,number>(),pnls:number[]=[];const px=(s:string,t:number,f:"open"|"close"="close")=>{const i=p.idx[s]?.get(t);return i==null?undefined:p.bars[s]?.[i]?.[f]};const equity=(t:number,f:"open"|"close"="close")=>{let e=cash;for(const q of pos.values()){const x=px(q.symbol,t,f)??q.entry,dir=q.side==="long"?1:-1;e+=dir*q.qty*(x-q.entry)-q.qty*x*fee}return Math.max(0,e)};const gross=(t:number,f:"open"|"close"="close")=>{const e=Math.max(1,equity(t,f));let n=0;for(const q of pos.values())n+=q.qty*(px(q.symbol,t,f)??q.entry);return n/e};const close=(q:Pos,raw:number,reason:string,t:number)=>{const x=q.side==="long"?raw*(1-slip):raw*(1+slip),dir=q.side==="long"?1:-1,g=dir*q.qty*(x-q.entry),ef=q.qty*x*fee,net=g-q.entryFee-ef-q.funding;cash=Math.max(0,cash+g-ef);pnls.push(net);pos.delete(q.symbol);exits.delete(q.symbol);cool.set(q.symbol,t+2*H)};
for(const t of times){for(const [s,r] of [...exits]){const q=pos.get(s),o=px(s,t,"open");if(q&&o)close(q,o,r,t);exits.delete(s)}for(const [s,x] of [...pending]){if(pos.size>=v.slots||pos.has(s)||(cool.get(s)||0)>t){pending.delete(s);continue}const raw=px(s,t,"open");if(!raw){pending.delete(s);continue}const e=equity(t,"open"),entry=x.c.side==="long"?raw*(1+slip):raw*(1-slip),dist=Math.max(x.c.atr*P.stop,entry*.005),risk=e*(P.riskPct/100)/(dist/entry),active=[...pos.values()].reduce((n,q)=>n+q.qty*(px(q.symbol,t,"open")??q.entry),0),remain=Math.max(0,e-active),notional=Math.min(risk,e*v.slotCap,remain);if(notional/e<.1){blocked++;pending.delete(s);continue}const qty=notional/entry,ef=notional*fee,init=x.c.side==="long"?entry-dist:entry+dist,tp=x.c.side==="long"?entry+x.c.atr*P.tp:entry-x.c.atr*P.tp,had=pos.size>0;cash-=ef;pos.set(s,{symbol:s,side:x.c.side,entry,qty,entryFee:ef,funding:0,lastFund:t,initialStop:init,stop:init,tp,atr:x.c.atr,peak:entry,trough:entry,bars:0,rank:x.rank});if(x.rank===2)rank2++;if(had)whileHeld++;pending.delete(s)}for(const q of [...pos.values()]){const i=p.idx[q.symbol]?.get(t),b=i==null?undefined:p.bars[q.symbol]?.[i];if(!b)continue;q.bars++;const fr=fund(d.fundingBySymbol[q.symbol]||[],q.lastFund,t),fc=q.qty*q.entry*fr*(q.side==="long"?1:-1);q.funding+=fc;q.lastFund=t;cash-=fc;if(q.side==="long"){if(b.low<=q.stop){close(q,q.stop,q.stop>q.initialStop?"trail":"stop",t);continue}if(b.high>=q.tp){close(q,q.tp,"tp",t);continue}}else{if(b.high>=q.stop){close(q,q.stop,q.stop<q.initialStop?"trail":"stop",t);continue}if(b.low<=q.tp){close(q,q.tp,"tp",t);continue}}q.peak=Math.max(q.peak,b.high);q.trough=Math.min(q.trough,b.low);q.stop=q.side==="long"?Math.max(q.initialStop,q.peak-q.atr*P.trail):Math.min(q.initialStop,q.trough+q.atr*P.trail)}const e=equity(t),g=gross(t);peak=Math.max(peak,e);dd=Math.max(dd,(peak-e)/peak*100);gSum+=g;gMax=Math.max(gMax,g);obs++;if(pos.size===2)twoBars++;const cs=cand(p,t).slice(0,v.slots),keys=new Set(cs.map(x=>x.symbol+":"+x.side));for(const q of pos.values()){if(q.bars>=P.maxHold)exits.set(q.symbol,"max-hold");else if(q.bars>=P.rebalance&&!keys.has(q.symbol+":"+q.side))exits.set(q.symbol,"rotation")}let slots=Math.max(0,v.slots-[...pos.keys()].filter(s=>!exits.has(s)).length-pending.size);for(let r=0;r<cs.length&&slots>0;r++){const c=cs[r];if((pos.has(c.symbol)&&!exits.has(c.symbol))||pending.has(c.symbol)||(cool.get(c.symbol)||0)>t)continue;pending.set(c.symbol,{c,rank:r+1});slots--}}
for(const q of [...pos.values()]){const last=[...(d.bySymbol[q.symbol]||[])].reverse().find(x=>x.ts<z);if(last)close(q,last.close,"end",z)}const years=(z-a)/(365.25*24*H),ret=(cash/10000-1)*100,cagr=(Math.pow(cash/10000,1/years)-1)*100;return{returnPct:ret,cagrPct:cagr,maxDrawdownPct:dd,profitFactor:pf(pnls),profitFactorWithoutBest:pfwb(pnls),winRatePct:pnls.length?pnls.filter(x=>x>0).length/pnls.length*100:0,tradeCount:pnls.length,averageGross:obs?gSum/obs:0,maximumGross:gMax,twoPositionBarPct:obs?twoBars/obs*100:0,rank2Entries:rank2,entriesWhileAnotherV12Held:whileHeld,capacityBlocks:blocked}}
async function main(){const d=await loadPerpMarketData({symbols:SYMS,startTs:WARM,endTs:END+4*H}),p=prep(d),periods=[["development",START,D],["validation",D,V],["evaluation",V,END],["combined3y",START,END]] as const,out:any={researchOnly:true,productionChanged:false,vpsChanged:false,ordersSent:false,dataSource:d.source,definition:{aggregateV12GrossCap:1,period:"2023-07-01..2026-07-01",timeframe:"2H",variants}};for(const [name,a,z] of periods){out[name]={};for(const v of variants){out[name][v.name]={};for(const m of modes)out[name][v.name][m.name]=simulate(d,p,a,z,v,m)}}await fs.mkdir(".research-state",{recursive:true});await fs.writeFile(".research-state/v12-gross-compare.json",JSON.stringify(out,null,2)+"\n");console.log("V12_GROSS_COMPARE="+JSON.stringify(out))}main().catch(e=>{console.error(e);process.exitCode=1});