from pathlib import Path
TARGET=Path('.pengu-current/scripts/.research_pengu_v57.generated.ts');src=TARGET.read_text();marker='\nfunction longDiagnostics(rows: PenguDualLsV2EvaluationRow[]) {'
insert=r'''
type V75Family="BTC_WEAK_RELATIVE_RESILIENCE";
const V75_NEW_LONG_GROSS=0.25,V75_MATERIAL_GAIN_MULTIPLE=1.05,V75_MIN_TRADES_PER_FOLD=2;
const V75_NEW_LONG_SLEEVE="PENGU_V75_NEW_LONG_SLEEVE";
const V75_FOLD_BOUNDARIES=["2025-08-10T00:00:00Z","2025-12-09T16:00:00Z","2026-04-10T08:00:00Z","2026-08-10T00:00:00Z"].map(x=>Date.parse(x));
const V75_FROZEN_V64_CONFIG:V64Config={rule:{feature:"penguReturn72h",op:"lte",threshold:0.12049482888834451},lowGross:0.1875,label:"penguReturn72h_lte_0.12049483_LOW0.1875",trainScore:31.7010356792032};
function v75Raw(rows:PenguDualLsV2EvaluationRow[],index:number){if(index<1)return false;const row=rows[index],f=row.features;if(!f||row.shortSignal||longRawForMode(row,"V64_DYNAMIC"))return false;return f.btcReturn24h<=-0.005&&f.btcReturn24h>=-0.04&&f.relativeReturn24h>=0.025&&f.penguReturn24h>=-0.005&&f.volumeRatio6OverPrior36>=0.90&&f.rsi14>=42&&f.rsi14<=62&&row.candle.close>row.candle.open&&row.candle.close>rows[index-1].candle.close;}
function v75NewLongSignal(rows:PenguDualLsV2EvaluationRow[],index:number){const c=v75Raw(rows,index),p=index>0?v75Raw(rows,index-1):false;return c&&!p;}
function replayV75NewLongSleeve(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:RichTrade[]=[];const costPerSide=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_ADVERSE_SLIPPAGE_PER_SIDE:0);let index=250,cooldown=-1;while(index<rows.length-2){if(index<=cooldown){index++;continue;}const features=rows[index].features;if(!features||!v75NewLongSignal(rows,index)){index++;continue;}const entryIndex=index+1,entry=rows[entryIndex].candle;let position:PenguDualLsV2Position={side:1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross:V75_NEW_LONG_GROSS,highWaterMark:entry.open,lowWaterMark:entry.open,entryVersion:"LONG_V2_FINAL"};const last=Math.min(rows.length-1,entryIndex+PENGU_DUAL_LS_V2.long.maxHoldHours-1);let exitIndex=last,exitPrice=rows[last].candle.close,engineExitReason="LONG_MAX_HOLD",exitReason:ExitGroup="time",mfe=0,mae=0;for(let cursor=entryIndex;cursor<=last;cursor++){const f=rows[cursor].features;assert(f);mfe=Math.max(mfe,f.high/entry.open-1);mae=Math.min(mae,f.low/entry.open-1);const e=evaluatePenguDualLsV2PositionBar(position,f);position=e.updatedPosition;if(e.exit){exitIndex=cursor;exitPrice=e.exit.stopPrice??rows[cursor].candle.close;engineExitReason=e.exit.reason;exitReason=e.exit.reason.includes("HARD")?"hard":e.exit.reason.includes("TRAILING")?"trail":"time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime,rawUnitReturn=exitPrice/entry.open-1,fundingUnitReturn=-fundingBetween(funding,entry.openTime,exitTs),costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn;trades.push({side:"L",signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross:V75_NEW_LONG_GROSS,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn:V75_NEW_LONG_GROSS*netUnitReturn,exitReason,engineExitReason,entryFeatures:{...features},mfeUnit:mfe,maeUnit:mae});}cooldown=exitIndex+PENGU_DUAL_LS_V2.cooldownHours;index=exitIndex+1;}return trades;}
function evaluateV75(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],baselineV56Normal:RichTrade[]){const derivation=deriveV57Thresholds(baselineV56Normal);v57Thresholds=derivation.thresholds;v64ActiveConfig=V75_FROZEN_V64_CONFIG;const incN=replay(rows,funding,{mode:"normal",longMode:"V64_DYNAMIC"}).trades,incS=replay(rows,funding,{mode:"stress",longMode:"V64_DYNAMIC"}).trades,incNM=metrics(incN),incSM=metrics(incS);assert.equal(incNM.trades,41);assert.equal(incNM.longTrades,13);assert.equal(incNM.shortTrades,28);assert.ok(Math.abs(incNM.returnPct-303.9903920953809)<1e-6);const normal=replayV75NewLongSleeve(rows,funding,"normal"),stress=replayV75NewLongSleeve(rows,funding,"stress"),folds:Array<any>=[];for(let i=0;i<3;i++){const a=V75_FOLD_BOUNDARIES[i],b=V75_FOLD_BOUNDARIES[i+1],n=sliceByTime(normal,a,b),s=sliceByTime(stress,a,b),mn=metrics(n),ms=metrics(s),normalPass=n.length>=V75_MIN_TRADES_PER_FOLD&&mn.returnPct>0&&(mn.profitFactor??0)>=1,stressPass=s.length>=V75_MIN_TRADES_PER_FOLD&&ms.returnPct>0&&(ms.profitFactor??0)>=1;folds.push({fold:i+1,start:new Date(a).toISOString(),end:new Date(b).toISOString(),trades:{normal:n.length,stress:s.length},metrics:{normal:mn,stress:ms},normalPass,stressPass,pass:normalPass&&stressPass});}const allFoldPass=folds.every(x=>x.pass),fmN=metrics(normal),fmS=metrics(stress),strictPass=allFoldPass;return{schema:"pengu-v75-independent-long-sleeve/v1",family:"BTC_WEAK_RELATIVE_RESILIENCE" as V75Family,frozenV64Config:V75_FROZEN_V64_CONFIG,newLongGross:V75_NEW_LONG_GROSS,materialGainThresholdMultiple:V75_MATERIAL_GAIN_MULTIPLE,incumbent:{normal:incNM,stress:incSM},folds,allFoldPass,fullMetrics:{normal:fmN,stress:fmS},strictPass,decision:strictPass?"ADOPT_V75_STANDALONE_CANDIDATE":"KEEP_V64_RESEARCH_CANDIDATE"};}
'''
if marker not in src:raise SystemExit('marker missing');src=src.replace(marker,insert+marker,1)
start=src.index('  const v64 = evaluateV64(rows,funding,baselineNormal);');end=src.index('\n}\n\nmain().catch',start)
tail=r'''  const v75=evaluateV75(rows,funding,baselineNormal);v64ActiveConfig=V75_FROZEN_V64_CONFIG;const incumbentNormal=replay(rows,funding,{mode:"normal",longMode:"V64_DYNAMIC"}).trades,incumbentStress=replay(rows,funding,{mode:"stress",longMode:"V64_DYNAMIC"}).trades,newLongNormal=replayV75NewLongSleeve(rows,funding,"normal"),newLongStress=replayV75NewLongSleeve(rows,funding,"stress");const resultPayload={status:"PASS_RESEARCH_ONLY",v75,final:{v64Preserved:true,newLongSleeveSelected:"BTC_WEAK_RELATIVE_RESILIENCE",newLongSleevePromoted:v75.strictPass},safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};
function mkV64(n:RichTrade[],s:RichTrade[]){return{schema:"pengu-dual-ls-v2-aster-ledger/v1",strategyId:PENGU_DUAL_LS_V2.id,longVariant:"PENGU_DUAL_LS_V2_FINAL_V64_FROZEN",shortVariant:"COUNTERWIND_VOL_TARGET_FAILURE_EXIT",currentProductionSourceSha:SOURCE_SHA,researchOnly:true,period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},source:{venue:"Aster perpetual public REST V3",productionLogicSha:SOURCE_SHA},costs:{normalFeeBpsPerSide:6,stressAdditionalAdverseBpsPerSide:35,actualFunding:true},integrity:{noOverlap:n.every((t,i)=>i===0||t.entryTs>n[i-1].exitTs),maximumRequestedGross:Math.max(...n.map(t=>t.requestedGross))},modes:{normal:{metrics:metrics(n),trades:n.map(publicTrade)},stress:{metrics:metrics(s),trades:s.map(publicTrade)}},safety:{ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};}function mkNew(n:RichTrade[],s:RichTrade[]){return{schema:"pengu-v75-new-long-sleeve-ledger/v1",strategyId:V75_NEW_LONG_SLEEVE,researchOnly:true,selectedFamily:"BTC_WEAK_RELATIVE_RESILIENCE",requestedGross:V75_NEW_LONG_GROSS,period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},source:{venue:"Aster perpetual public REST V3",productionLogicSha:SOURCE_SHA},costs:{normalFeeBpsPerSide:6,stressAdditionalAdverseBpsPerSide:35,actualFunding:true},integrity:{noOverlap:n.every((t,i)=>i===0||t.entryTs>n[i-1].exitTs),longOnly:n.every(t=>t.side==="L"),maximumRequestedGross:n.length?Math.max(...n.map(t=>t.requestedGross)):0},modes:{normal:{metrics:metrics(n),trades:n.map(publicTrade)},stress:{metrics:metrics(s),trades:s.map(publicTrade)}},safety:{ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};}const incumbentLedger=mkV64(incumbentNormal,incumbentStress),newLongLedger=mkNew(newLongNormal,newLongStress);assert.equal(newLongLedger.integrity.longOnly,true);await fs.mkdir(OUTPUT_DIR,{recursive:true});await fs.writeFile(path.join(OUTPUT_DIR,"v75-result.json"),JSON.stringify(resultPayload,null,2)+"\n");await fs.writeFile(path.join(OUTPUT_DIR,"incumbent-v64-pengu-ledger.json"),JSON.stringify(incumbentLedger,null,2)+"\n");await fs.writeFile(path.join(OUTPUT_DIR,"new-long-sleeve-ledger.json"),JSON.stringify(newLongLedger,null,2)+"\n");console.log("V75_RESULT="+JSON.stringify(v75));
'''
src=src[:start]+tail+src[end:];TARGET.write_text(src);print(f'PATCHED_V75={TARGET}')
