V58B_MODES = (
    'V58B_REENTRY_ONE_FAIL',
    'V58B_REENTRY_CORE',
    'V58B_REENTRY_ELITE',
)

REENTRY_NATIVE_V57 = False
REENTRY_RECOVERY = True
RECOVERY_COOLDOWN_HOURS = 6
ONE_FAIL_GROSS_CAP = 0.625
TWO_FAIL_GROSS_CAP = 0.375
