import fs from "fs/promises";
import path from "path";
import { loadPerpMarketData } from "../lib/research-lab/perp/data-store";
import type { Candle1h } from "../lib/backtest/types";

const H=3600000,BAR=12*H,REB=84*H,START=Date.UTC(2023,6,1),DEND=Date.UTC(2024,6,1),VEND=Date.UTC(2025,6,1),END=Date.UTC(2026,6,1),NORMAL=10,STRESS=30;
const U=["BTC","ETH","BNB","SOL","LINK","AVAX","DOGE","INJ","PENGU","XRP","ADA","LTC","ATOM","AAVE","NEAR"] as const;type S=typeof U[number];
type B={ts:number;open:number;high:number;low:number;close:number};type F={close:number;sma50:number;m20:number;m60:number;n20:number;n60:number};type T={symbol:S;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;netReturnPct:number;grossReturnPct:number;entryScore:number;exitReason:string};
const mean=(a:number[])=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);function sd(a:number[]){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}function med(a:number[]){const x=[...a].sort((a,b)=>a-b);if(!x.length)return 0;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}function pf(v:number[]){const g=v.filter(x=>x>0).reduce((a,b)=>a+b,0),l=Math.abs(v.filter(x=>x<0).reduce((a,b)=>a+b,0));return l?g/l:g?99:0}
function bars(rows:Candle1h[]){const m=new Map<number,Candle1h[]>();for(const r of rows){const k=Math.floor(r.ts/BAR)*BAR,v=m.get(k)||[];v.push(r);m.set(k,v)}const o:B[]=[];for(const [k,a0] of [...m].sort((x,y)=>x[0]-y[0])){const a=[...a0].sort((x,y)=>x.ts-y.ts);if(a.length<10)continue;o.push({ts:k+BAR,open:a[0].open,high:Math.max(...a.map(x=>x.high)),low:Math.min(...a.map(x=>x.low)),close:a.at(-1)!.close})}return o}
function feat(b:B[]){const o=new Map<number,F>(),c=b.map(x=>x.close),r=[0];for(let i=1;i<b.length;i++)r.push(c[i]/c[i-1]-1);for(let i=60;i<b.length;i++){const sma50=mean(c.slice(i-49,i+1)),m20=c[i]/c[i-20]-1,m60=c[i]/c[i-60]-1,v20=sd(r.slice(i-19,i+1)),v60=sd(r.slice(i-59,i+1));o.set(b[i].ts,{close:c[i],sma50,m20,m60,n20:v20?m20/(v20*Math.sqrt(20)):0,n60:v60?m60/(v60*Math.sqrt(60)):0})}return o}
const idx=(r:Candle1h[])=>new Map(r.map((x,i)=>[x.ts,i]));
function metric(t:T[],a:number,b:number,dd:number){const v=t.map(x=>x.netReturnPct);let e=1;for(const x of v)e*=Math.max(.000001,1+x/100);const yrs=(b-a)/(365.25*24*H),wo=[...v];if(wo.length)wo.splice(wo.indexOf(Math.max(...wo)),1);return{trades:v.length,returnPct:(e-1)*100,cagrPct:(e**(1/yrs)-1)*100,pf:pf(v),pfWithoutBest:pf(wo),maxDDPct:dd,winRatePct:v.length?v.filter(x=>x>0).length/v.length*100:0,medianTradePct:med(v),symbolContributionPctPoints:Object.fromEntries(U.map(s=>[s,t.filter(x=>x.symbol===s).reduce((q,x)=>q+x.netReturnPct,0)]))}}
function gate(c:any,s:any,a:Record<string,any>,as:Record<string,any>){const y=Object.values(a).map((x:any)=>x.returnPct),ys=Object.values(as).map((x:any)=>x.returnPct),checks={everyAnnualAtLeast80:y.every(x=>x>=80),medianAnnualAtLeast100:med(y)>=100,cagrAtLeast100:c.cagrPct>=100,pfAtLeast1p40:c.pf>=1.4,pfWithoutBestAtLeast1p25:c.pfWithoutBest>=1.25,maxDDNoWorseThan40:c.maxDDPct>=-40,tradesAtLeast24:c.trades>=24,stressCagrAtLeast45:s.cagrPct>=45,stressPfAtLeast1p08:s.pf>=1.08,stressPfWithoutBestAtLeast1:s.pfWithoutBest>=1,stressDDNoWorseThan50:s.maxDDPct>=-50,atLeastTwoStressPositiveYears:ys.filter(x=>x>0).length>=2,worstStressYearAboveMinus25:Math.min(...ys)>-25};return{checks,historicalCandidatePass:Object.values(checks).every(Boolean)}}
async function sim(data:Awaited<ReturnType<typeof loadPerpMarketData>>,f:Record<S,Map<number,F>>,a:number,b:number,cost:number,delay:number){const ix=Object.fromEntries(U.map(s=>[s,idx(data.bySymbol[s]||[])])) as Record<S,Map<number,number>>,times=[...f.BTC.keys()].filter(t=>t>=a&&t<b).sort((x,y)=>x-y);let eq=1,peak=1,dd=0,pos:null|{symbol:S;entryTs:number;entryPrice:number;entryScore:number;entryEq:number}=null;const tr:T[]=[];const mark=(ts:number)=>{if(!pos){peak=Math.max(peak,eq);return}const j=ix[pos.symbol].get(ts-H);if(j==null)return;const q=pos.entryEq*(data.bySymbol[pos.symbol][j].close/pos.entryPrice);peak=Math.max(peak,q);dd=Math.min(dd,(q/peak-1)*100)};const close=(ts:number,reason:string)=>{if(!pos)return;const et=ts+delay*H,j=ix[pos.symbol].get(et);if(j==null)return;const p=data.bySymbol[pos.symbol][j].open,g=(p/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,entryTs:pos.entryTs,exitTs:et,entryPrice:pos.entryPrice,exitPrice:p,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,exitReason:reason});pos=null;peak=Math.max(peak,eq);dd=Math.min(dd,(eq/peak-1)*100)};const open=(ts:number,x:{symbol:S;score:number})=>{const et=ts+delay*H,j=ix[x.symbol].get(et);if(j==null)return;pos={symbol:x.symbol,entryTs:et,entryPrice:data.bySymbol[x.symbol][j].open,entryScore:x.score,entryEq:eq}};
 for(const ts of times){mark(ts);if((ts-START)%REB!==0)continue;const rank:{symbol:S;score:number}[]=[];for(const s of U){const x=f[s]?.get(ts);if(!x)continue;if(x.close>x.sma50&&x.m20>0&&x.m60>0)rank.push({symbol:s,score:(x.n20+x.n60)/2})}rank.sort((x,y)=>y.score-x.score||x.symbol.localeCompare(y.symbol));if(pos){const k=rank.findIndex(x=>x.symbol===pos!.symbol);if(k>=0&&k<2)continue}const d=rank[0]||null;if(pos&&d?.symbol===pos.symbol)continue;if(pos)close(ts,d?"ROTATION":"TO_CASH");if(!pos&&d)open(ts,d)}if(pos){const last=(data.bySymbol[pos.symbol]||[]).filter(x=>x.ts>=a&&x.ts<b).at(-1);if(last){const g=(last.close/pos.entryPrice-1)*100,n=g-cost/100;eq=pos.entryEq*Math.max(.000001,1+n/100);tr.push({symbol:pos.symbol,entryTs:pos.entryTs,exitTs:last.ts,entryPrice:pos.entryPrice,exitPrice:last.close,grossReturnPct:g,netReturnPct:n,entryScore:pos.entryScore,exitReason:"PERIOD_END"})}}return{m:metric(tr,a,b,dd),tr}}
async function main(){const data=await loadPerpMarketData({symbols:[...U],startTs:START-45*24*H,endTs:END}),f=Object.fromEntries(U.map(s=>[s,feat(bars(data.bySymbol[s]||[]))])) as Record<S,Map<number,F>>,p={development:[START,DEND],validation:[DEND,VEND],evaluation:[VEND,END]} as const,a:Record<string,any>={},as:Record<string,any>={};for(const [k,[x,y]] of Object.entries(p)){a[k]=(await sim(data,f,x,y,NORMAL,0)).m;as[k]=(await sim(data,f,x,y,STRESS,1)).m}const c=await sim(data,f,START,END,NORMAL,0),s=await sim(data,f,START,END,STRESS,1),g=gate(c.m,s.m,a,as),out={researchLine:"V27_MULTI_HORIZON_LEADER",researchOnly:true,productionChanged:false,vpsChanged:false,liveChanged:false,realTradingEnabled:false,freshOosRead:false,freshOosConsumed:false,target:{main3YCagrPct:100,grossExposureCapPct:100,leverageMultiplier:1},architecture:"15-asset dynamic common rule: SMA50 + positive 20/60 x12H momentum -> average normalized 20/60 momentum rank -> 84H top2 ownership",antiOverfit:{parameterGrid:false,perSymbolParameters:false,yearSpecificParameters:false,leverageUsedToReachTarget:false},annual:a,annualStress:as,combined3Y:c.m,combined3YStress:s.m,historicalGate:g};const root=process.env.RESEARCH_STATE_DIR||".research-state";await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,"multi-horizon-leader-v27.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});
