from pathlib import Path

TARGET=Path('.pengu-current/scripts/.research_pengu_v57.generated.ts')
src=TARGET.read_text()
marker='\nfunction longDiagnostics(rows: PenguDualLsV2EvaluationRow[]) {'
insert=r'''
type RecoveryRuleName="R_CORE3"|"R_LEVEL3"|"R_BTC3"|"R_CORE2OF3";
type RecoveryPriority="SHORT_FIRST"|"RECOVERY_OVER_NEW_SHORT";
type RecoveryExitConfig={name:string;hardStopPct:number;trailActivationPct:number;trailRetracePct:number;maxHoldHours:number;structuralBufferPct:number|null};
type RecoveryBtConfig={rule:RecoveryRuleName;priority:RecoveryPriority;gross:number;exit:RecoveryExitConfig};
const RECOVERY_RULE_THRESHOLDS={failedGateMax:5,rsiDelta6Min:7.392354615445917,ema168DistanceMinPct:-5.864583483302943,btcReturn6hMinPct:0.20571786048402818,rsi14Min:49.37147363707568} as const;
const RECOVERY_EXIT_CONFIGS:RecoveryExitConfig[]=[
 {name:"STRUCT_A6_T6_R3_H72",hardStopPct:.06,trailActivationPct:.06,trailRetracePct:.03,maxHoldHours:72,structuralBufferPct:.005},
 {name:"STRUCT_A8_T8_R3_H96",hardStopPct:.08,trailActivationPct:.08,trailRetracePct:.03,maxHoldHours:96,structuralBufferPct:.01},
 {name:"STRUCT_A8_T8_R4_H96",hardStopPct:.08,trailActivationPct:.08,trailRetracePct:.04,maxHoldHours:96,structuralBufferPct:.005},
 {name:"FIXED_A6_T6_R3_H72",hardStopPct:.06,trailActivationPct:.06,trailRetracePct:.03,maxHoldHours:72,structuralBufferPct:null},
 {name:"FIXED_A8_T8_R4_H96",hardStopPct:.08,trailActivationPct:.08,trailRetracePct:.04,maxHoldHours:96,structuralBufferPct:null},
 {name:"STRUCT_A8_T10_R3_H120",hardStopPct:.08,trailActivationPct:.10,trailRetracePct:.03,maxHoldHours:120,structuralBufferPct:.01},
 {name:"FIXED_A5_T5_R2P5_H48",hardStopPct:.05,trailActivationPct:.05,trailRetracePct:.025,maxHoldHours:48,structuralBufferPct:null},
 {name:"STRUCT_A6_T10_R4_H120",hardStopPct:.06,trailActivationPct:.10,trailRetracePct:.04,maxHoldHours:120,structuralBufferPct:.005},
];
function rawRecoveryCross3(rows:PenguDualLsV2EvaluationRow[],i:number){if(i<RECOVERY_LOOKBACK||!rows[i]?.features)return null;const troughIndex=rollingCloseMinIndex(rows,i,RECOVERY_LOOKBACK);if(troughIndex<0)return null;const age=i-troughIndex;if(age<1||age>RECOVERY_MAX_TROUGH_AGE)return null;const troughClose=rows[troughIndex].candle.close,level=troughClose*1.03;if(rows[i-1].candle.close>=level||rows[i].candle.close<level)return null;return{troughIndex,troughClose};}
function dedupedRecoveryCross3(rows:PenguDualLsV2EvaluationRow[],i:number){const c=rawRecoveryCross3(rows,i);if(!c)return null;for(let j=Math.max(RECOVERY_LOOKBACK,i-5);j<i;j++)if(rawRecoveryCross3(rows,j))return null;return c;}
function recoveryRuleAt(rows:PenguDualLsV2EvaluationRow[],i:number,rule:RecoveryRuleName){const c=dedupedRecoveryCross3(rows,i);if(!c)return null;const x=recoveryFeatures(rows,i,c.troughIndex,c.troughClose,3),t=RECOVERY_RULE_THRESHOLDS;const failed=x.failedLongGateCount<=t.failedGateMax,rsi6=x.rsiDelta6>=t.rsiDelta6Min,ema=x.ema168DistancePct>=t.ema168DistanceMinPct,btc6=x.btcReturn6hPct>=t.btcReturn6hMinPct,rsi=x.rsi14>=t.rsi14Min;let pass=false;if(rule==="R_CORE3")pass=failed&&rsi6&&ema;else if(rule==="R_LEVEL3")pass=failed&&ema&&rsi;else if(rule==="R_BTC3")pass=rsi6&&ema&&btc6;else pass=(Number(failed)+Number(rsi6)+Number(ema))>=2;return pass?{...c,features:x}:null;}
function recoveryTradeCount(trades:RichTrade[]){return trades.filter(t=>t.engineExitReason.startsWith("RECOVERY_")).length;}
function replayRecoveryIntegrated(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode,baseLongMode:LongMode,cfg:RecoveryBtConfig){
 const trades:RichTrade[]=[];const costPerSide=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_ADVERSE_SLIPPAGE_PER_SIDE:0);let index=250,cooldown=-1;
 while(index<rows.length-2){if(index<=cooldown){index++;continue;}const f=rows[index].features;if(!f){index++;continue;}const baseLong=longSignalForMode(rows,index,baseLongMode);const rec=!baseLong?recoveryRuleAt(rows,index,cfg.rule):null;const short=rows[index].shortSignal;
   let kind:"S"|"BASE_L"|"REC_L"|undefined;if(cfg.priority==="RECOVERY_OVER_NEW_SHORT"&&rec&&short)kind="REC_L";else if(short)kind="S";else if(baseLong)kind="BASE_L";else if(rec)kind="REC_L";if(!kind){index++;continue;}
   const side:Side=kind==="S"?"S":"L";let requestedGross=kind==="REC_L"?cfg.gross:targetGrossForAtr(f.atr24Ratio,side==="L"?1:-1);if(kind==="BASE_L"&&baseLongMode==="V64_DYNAMIC"&&!rows[index].longRaw)requestedGross=v64SupplementalGross(f,requestedGross);
   const entryIndex=index+1,entry=rows[entryIndex].candle;let exitIndex=entryIndex,exitPrice=entry.open,engineExitReason="",exitReason:ExitGroup="time",bestFavorable=0,worstAdverse=0;let initialShortState:any=undefined;
   if(kind==="REC_L"){
     const ec=cfg.exit,last=Math.min(rows.length-1,entryIndex+ec.maxHoldHours-1);exitIndex=last;exitPrice=rows[last].candle.close;engineExitReason="RECOVERY_MAX_HOLD";let highWater=entry.open;const fixedStop=entry.open*(1-ec.hardStopPct);const structural=ec.structuralBufferPct===null?-Infinity:rec!.troughClose*(1-ec.structuralBufferPct);const hardStop=Math.max(fixedStop,structural);
     for(let cursor=entryIndex;cursor<=last;cursor++){const c=rows[cursor].candle;bestFavorable=Math.max(bestFavorable,c.high/entry.open-1);worstAdverse=Math.min(worstAdverse,c.low/entry.open-1);if(c.low<=hardStop){exitIndex=cursor;exitPrice=hardStop;engineExitReason="RECOVERY_HARD_STOP";exitReason="hard";break;}const priorHigh=highWater;if(priorHigh>=entry.open*(1+ec.trailActivationPct)){const stop=priorHigh*(1-ec.trailRetracePct);if(c.low<=stop){exitIndex=cursor;exitPrice=stop;engineExitReason="RECOVERY_TRAILING_STOP";exitReason="trail";break;}}highWater=Math.max(highWater,c.high);}
   } else {
     let position:PenguDualLsV2Position={side:side==="L"?1:-1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross:requestedGross,highWaterMark:entry.open,lowWaterMark:entry.open,entryVersion:side==="S"?"SHORT_V20":"LONG_V2_FINAL",shortV20:side==="S"?createPenguShortV20State({entryPrice:entry.open,requestedGross,entryAtr24Ratio:f.atr24Ratio,btcEma168Distance:f.btcEma168Distance,btcReturn24h:f.btcReturn24h}):undefined};initialShortState=position.shortV20?{...position.shortV20}:undefined;const hold=side==="L"?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,entryIndex+hold-1);exitIndex=last;exitPrice=rows[last].candle.close;engineExitReason=side==="L"?"LONG_MAX_HOLD":"SHORT_MAX_HOLD";
     for(let cursor=entryIndex;cursor<=last;cursor++){const ff=rows[cursor].features;assert(ff);if(side==="L"){bestFavorable=Math.max(bestFavorable,ff.high/entry.open-1);worstAdverse=Math.min(worstAdverse,ff.low/entry.open-1);}else{bestFavorable=Math.max(bestFavorable,1-ff.low/entry.open);worstAdverse=Math.min(worstAdverse,1-ff.high/entry.open);}const ev=evaluatePenguDualLsV2PositionBar(position,ff);position=ev.updatedPosition;if(ev.exit){exitIndex=cursor;exitPrice=ev.exit.stopPrice??rows[cursor].candle.close;engineExitReason=ev.exit.reason;exitReason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}
   }
   if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime,rawUnitReturn=side==="L"?exitPrice/entry.open-1:entry.open/exitPrice-1,fundingRate=fundingBetween(funding,entry.openTime,exitTs),fundingUnitReturn=side==="L"?-fundingRate:fundingRate,costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn;trades.push({side,signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn:requestedGross*netUnitReturn,exitReason,engineExitReason,sizingState:side==="S"?classifyPenguShortV20SizingState(requestedGross):undefined,counterwind:initialShortState?.counterwind,entryFeatures:{...f},mfeUnit:bestFavorable,maeUnit:worstAdverse});}
   cooldown=exitIndex+PENGU_DUAL_LS_V2.cooldownHours;index=exitIndex+1;
 }
 return trades;
}
function foldBounds(){const span=EVAL_END-EVAL_START,a=EVAL_START+Math.floor(span/3),b=EVAL_START+Math.floor(span*2/3);return{FOLD1:[EVAL_START,a],FOLD2:[a,b],FOLD3:[b,EVAL_END]} as const;}
function metricByFold(trades:RichTrade[]){const out:any={};for(const [fold,[a,b]] of Object.entries(foldBounds()) as any)out[fold]={...metrics(sliceByTime(trades,undefined,a,b)),recoveryTrades:recoveryTradeCount(sliceByTime(trades,undefined,a,b))};return out;}
function pfRatioOk(c:any,b:any,ratio:number){if(b.profitFactor===null)return true;if(c.profitFactor===null)return true;return c.profitFactor+1e-12>=b.profitFactor*ratio;}
function foldEligible(c:any,b:any,minRecovery=2){return c.recoveryTrades>=minRecovery&&c.returnPct>b.returnPct+1e-9&&pfRatioOk(c,b,.90)&&c.maxDrawdownPct>=b.maxDrawdownPct-2.0;}
function analyzeRecoveryBacktest(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],v64:any,selectedConfig:V64Config|null){
 const useV64=Boolean(v64.strictPass&&selectedConfig);v64ActiveConfig=useV64?selectedConfig:null;const baseMode:LongMode=useV64?"V64_DYNAMIC":"V57_REGIME72_BREAKOUT";const baseN=replay(rows,funding,{mode:"normal",longMode:baseMode}).trades,baseS=replay(rows,funding,{mode:"stress",longMode:baseMode}).trades;const base={normal:metrics(baseN),stress:metrics(baseS),normalFolds:metricByFold(baseN),stressFolds:metricByFold(baseS)};
 const configs:RecoveryBtConfig[]=[];for(const rule of ["R_CORE3","R_LEVEL3","R_BTC3","R_CORE2OF3"] as const)for(const priority of ["SHORT_FIRST","RECOVERY_OVER_NEW_SHORT"] as const)for(const gross of [.25,.375,.5])for(const exit of RECOVERY_EXIT_CONFIGS)configs.push({rule,priority,gross,exit});
 const evaluated:any[]=[];for(const cfg of configs){v64ActiveConfig=useV64?selectedConfig:null;const n=replayRecoveryIntegrated(rows,funding,"normal",baseMode,cfg);v64ActiveConfig=useV64?selectedConfig:null;const s=replayRecoveryIntegrated(rows,funding,"stress",baseMode,cfg);const nf=metricByFold(n),sf=metricByFold(s),m={normal:metrics(n),stress:metrics(s),normalFolds:nf,stressFolds:sf};const f1=foldEligible(nf.FOLD1,base.normalFolds.FOLD1)&&foldEligible(sf.FOLD1,base.stressFolds.FOLD1);const f2=foldEligible(nf.FOLD2,base.normalFolds.FOLD2)&&foldEligible(sf.FOLD2,base.stressFolds.FOLD2);const f3=foldEligible(nf.FOLD3,base.normalFolds.FOLD3)&&foldEligible(sf.FOLD3,base.stressFolds.FOLD3);const score=(nf.FOLD1.returnPct-base.normalFolds.FOLD1.returnPct)+(sf.FOLD1.returnPct-base.stressFolds.FOLD1.returnPct)*.5+(nf.FOLD2.returnPct-base.normalFolds.FOLD2.returnPct)*1.5+(sf.FOLD2.returnPct-base.stressFolds.FOLD2.returnPct);evaluated.push({cfg,developmentFold1Pass:f1,validationFold2Pass:f2,untouchedFold3Pass:f3,score,metrics:m,deltas:{fullNormalReturnPct:m.normal.returnPct-base.normal.returnPct,fullStressReturnPct:m.stress.returnPct-base.stress.returnPct,fold1Normal:nf.FOLD1.returnPct-base.normalFolds.FOLD1.returnPct,fold2Normal:nf.FOLD2.returnPct-base.normalFolds.FOLD2.returnPct,fold3Normal:nf.FOLD3.returnPct-base.normalFolds.FOLD3.returnPct}});}
 const survivors=evaluated.filter(x=>x.developmentFold1Pass&&x.validationFold2Pass).sort((a,b)=>b.score-a.score);const selected=survivors[0]??null;let strictPass=false;if(selected){const m=selected.metrics;strictPass=selected.untouchedFold3Pass&&m.normal.returnPct>base.normal.returnPct+1e-9&&m.stress.returnPct>base.stress.returnPct+1e-9&&pfRatioOk(m.normal,base.normal,.95)&&pfRatioOk(m.stress,base.stress,.95)&&m.normal.maxDrawdownPct>=base.normal.maxDrawdownPct-1.5&&m.stress.maxDrawdownPct>=base.stress.maxDrawdownPct-1.5;}
 return {schema:"pengu-recovery-integrated-backtest/v1",selectionProtocol:{thresholdSource:"entry thresholds fixed from Fold1 recovery-label medians only",development:"Fold1",validation:"Fold2",finalUntouched:"Fold3 not used for candidate selection",candidateCount:configs.length,requirements:"Normal and Severe must improve Return in Fold1 and Fold2 with >=2 recovery trades, PF >=90% baseline, DD degradation <=2pp; final requires same on untouched Fold3 plus full Normal/Severe improvement, PF >=95%, full DD degradation <=1.5pp"},ruleThresholds:RECOVERY_RULE_THRESHOLDS,exitConfigs:RECOVERY_EXIT_CONFIGS,baseline:base,survivorCount:survivors.length,topValidation:survivors.slice(0,20),selected,strictPass,decision:strictPass?"RECOVERY_SLEEVE_ROBUST_CANDIDATE":"NO_ROBUST_RECOVERY_SLEEVE_YET",safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};
}
'''
if marker not in src: raise SystemExit('longDiagnostics marker missing for recovery backtest')
src=src.replace(marker,insert+marker,1)
old='  analysis.recoveryStudy=analyzeRecoveryStudy(rows,v64Trades);'
new='  analysis.recoveryStudy=analyzeRecoveryStudy(rows,v64Trades);\n  analysis.recoveryBacktest=analyzeRecoveryBacktest(rows,funding,v64,selectedConfig);'
if old not in src: raise SystemExit('recoveryStudy assignment missing for recovery backtest')
src=src.replace(old,new,1)
TARGET.write_text(src)
print(f'PATCHED_RECOVERY_BACKTEST={TARGET}')
