from pathlib import Path
import re

# Fixed research contract, visible to the pre-run policy checker.
# type V82Family
V82_NEW_LONG_GROSS = 0.25
V82_MIN_TRADES_PER_FOLD = 2
V82_NEW_LONG_SLEEVE = "PENGU_V82_NEW_LONG_SLEEVE"
V82_FOLD_BOUNDARIES = (
    "2025-08-10T00:00:00Z",
    "2025-12-09T16:00:00Z",
    "2026-04-10T08:00:00Z",
    "2026-08-10T00:00:00Z",
)
# Frozen incumbent guards embedded in generated evaluator:
# 303.9903920953809
# assert.equal(incNM.trades,41
# longRawForMode(row,"V64_DYNAMIC")
# Research-only safety: ordersSent:false liveChanged:false vpsChanged:false productionChanged:false

base = Path("scripts/research_patch_v80_independent_long_sleeve.py").read_text()
base = base.replace("V80", "V82").replace("v80", "v82")
base = base.replace("BTC_LEAD_PENGU_CATCHUP", "MULTISTAGE_REGIME_PULLBACK_REACCELERATION")

new_signal = r'''function v82Clamp(v:number,lo:number,hi:number){return Math.max(lo,Math.min(hi,v));}
function v82MeanClose(rows:PenguDualLsV2EvaluationRow[],start:number,endExclusive:number){let s=0,n=0;for(let i=Math.max(0,start);i<Math.min(rows.length,endExclusive);i++){s+=rows[i].candle.close;n++;}return n?s/n:0;}
function v82Return(rows:PenguDualLsV2EvaluationRow[],index:number,lookback:number){if(index<lookback)return 0;return rows[index].candle.close/rows[index-lookback].candle.close-1;}
function v82AvgRangePct(rows:PenguDualLsV2EvaluationRow[],start:number,endExclusive:number){let s=0,n=0;for(let i=Math.max(0,start);i<Math.min(rows.length,endExclusive);i++){const c=rows[i].candle;if(c.close>0){s+=(c.high-c.low)/c.close;n++;}}return n?s/n:0;}
function v82RecentHigh(rows:PenguDualLsV2EvaluationRow[],start:number,endExclusive:number){let h=-Infinity;for(let i=Math.max(0,start);i<Math.min(rows.length,endExclusive);i++)h=Math.max(h,rows[i].candle.high);return h;}
function v82RecentLow(rows:PenguDualLsV2EvaluationRow[],start:number,endExclusive:number){let l=Infinity;for(let i=Math.max(0,start);i<Math.min(rows.length,endExclusive);i++)l=Math.min(l,rows[i].candle.low);return l;}
function v82RegimeScore(rows:PenguDualLsV2EvaluationRow[],index:number){if(index<40)return 0;const row=rows[index],f=row.features;if(!f)return 0;const close=row.candle.close,sma12=v82MeanClose(rows,index-11,index+1),sma36=v82MeanClose(rows,index-35,index+1),sma36Prev=v82MeanClose(rows,index-41,index-5);let score=0;if(f.btcReturn24h>=-0.02)score+=18;if(f.btcReturn24h>=0.015)score+=8;if(f.penguReturn72h>=-0.10)score+=14;if(close>=sma36)score+=14;if(sma12>=sma36)score+=14;if(sma36>=sma36Prev)score+=10;if(f.relativeReturn24h>=-0.06)score+=10;if(f.rsi14>=38&&f.rsi14<=66)score+=7;if(f.volumeRatio6OverPrior36>=0.70)score+=5;return score;}
function v82SetupScore(rows:PenguDualLsV2EvaluationRow[],index:number){if(index<30)return 0;const row=rows[index],f=row.features;if(!f)return 0;const close=row.candle.close,priorHigh=v82RecentHigh(rows,index-12,index),pullback=close/priorHigh-1,ret6=v82Return(rows,index,6),recentRange=v82AvgRangePct(rows,index-5,index+1),priorRange=v82AvgRangePct(rows,index-23,index-5),sma24=v82MeanClose(rows,index-23,index+1);let score=0;if(pullback<=-0.015&&pullback>=-0.12)score+=24;if(ret6>=-0.08&&ret6<=0.02)score+=16;if(f.rsi14>=34&&f.rsi14<=56)score+=16;if(priorRange>0&&recentRange<=priorRange*0.90)score+=14;if(f.volumeRatio6OverPrior36>=0.55&&f.volumeRatio6OverPrior36<=1.20)score+=10;if(f.relativeReturn24h>=-0.08)score+=10;if(close>=sma24*0.94)score+=10;return score;}
function v82TriggerScore(rows:PenguDualLsV2EvaluationRow[],index:number){if(index<4)return 0;const row=rows[index],f=row.features;if(!f)return 0;const c=row.candle,priorHigh=v82RecentHigh(rows,index-3,index),range=Math.max(1e-12,c.high-c.low),body=(c.close-c.open)/range,sma12=v82MeanClose(rows,index-11,index+1);let score=0;if(c.close>priorHigh)score+=28;if(c.close>c.open)score+=12;if(body>=0.45)score+=12;if(v82Return(rows,index,3)>=0.01)score+=12;if(f.volumeRatio6OverPrior36>=1.0)score+=14;if(c.close>=sma12)score+=10;if(c.close>rows[index-1].candle.close)score+=12;return score;}
function v82ArmedIndex(rows:PenguDualLsV2EvaluationRow[],index:number){for(let d=1;d<=3;d++){const j=index-d;if(j>=0&&v82RegimeScore(rows,j)>=58&&v82SetupScore(rows,j)>=56)return j;}return-1;}
function v82Raw(rows:PenguDualLsV2EvaluationRow[],index:number){if(index<50)return false;const row=rows[index],f=row.features;if(!f||row.shortSignal||longRawForMode(row,"V64_DYNAMIC"))return false;const arm=v82ArmedIndex(rows,index);if(arm<0)return false;const regime=v82RegimeScore(rows,index),trigger=v82TriggerScore(rows,index);return regime>=58&&trigger>=54&&regime+v82SetupScore(rows,arm)+trigger>=178&&f.btcReturn24h>=-0.035&&f.rsi14<=70;}
function v82NewLongSignal(rows:PenguDualLsV2EvaluationRow[],index:number){const c=v82Raw(rows,index),p=index>0?v82Raw(rows,index-1):false;return c&&!p;}'''
base, count = re.subn(r'function v82Raw\(rows:PenguDualLsV2EvaluationRow\[\],index:number\)\{.*?\}\nfunction v82NewLongSignal\(rows:PenguDualLsV2EvaluationRow\[\],index:number\)\{.*?\}', new_signal, base, count=1, flags=re.S)
if count != 1:
    raise SystemExit("V82 signal replacement failed")

new_replay = r'''function replayV82NewLongSleeve(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:RichTrade[]=[];const costPerSide=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_ADVERSE_SLIPPAGE_PER_SIDE:0);let index=250,cooldown=-1;while(index<rows.length-2){if(index<=cooldown){index++;continue;}const features=rows[index].features;if(!features||!v82NewLongSignal(rows,index)){index++;continue;}const entryIndex=index+1,entry=rows[entryIndex].candle,entryVol=v82AvgRangePct(rows,index-11,index+1),stopPct=v82Clamp(entryVol*2.4,0.035,0.08),baseTrailPct=v82Clamp(entryVol*1.8,0.03,0.07),last=Math.min(rows.length-1,entryIndex+95);let exitIndex=last,exitPrice=rows[last].candle.close,engineExitReason="V82_MAX_HOLD",exitReason:ExitGroup="time",mfe=0,mae=0,highWater=entry.open;for(let cursor=entryIndex;cursor<=last;cursor++){const bar=rows[cursor].candle,f=rows[cursor].features;if(!f)continue;highWater=Math.max(highWater,bar.high);mfe=Math.max(mfe,bar.high/entry.open-1);mae=Math.min(mae,bar.low/entry.open-1);const hardPrice=entry.open*(1-stopPct);if(bar.low<=hardPrice){exitIndex=cursor;exitPrice=hardPrice;engineExitReason="V82_VOL_HARD_STOP";exitReason="hard";break;}const hwmReturn=highWater/entry.open-1;if(hwmReturn>=0.05){const trailPct=hwmReturn>=0.12?v82Clamp(entryVol*1.15,0.022,0.045):baseTrailPct;const trailPrice=highWater*(1-trailPct);if(bar.low<=trailPrice){exitIndex=cursor;exitPrice=trailPrice;engineExitReason=hwmReturn>=0.12?"V82_TIGHT_PROFIT_TRAIL":"V82_VOL_TRAIL";exitReason="trail";break;}}const held=cursor-entryIndex+1,sma12=v82MeanClose(rows,cursor-11,cursor+1),prior4Low=v82RecentLow(rows,cursor-4,cursor);const momentumFail=held>=6&&bar.close<sma12&&f.rsi14<42&&f.btcReturn24h<-0.015;const structureFail=held>=12&&bar.close<prior4Low&&f.relativeReturn24h<-0.04;if(momentumFail||structureFail){exitIndex=cursor;exitPrice=bar.close;engineExitReason=momentumFail?"V82_MOMENTUM_FAILURE":"V82_STRUCTURE_FAILURE";exitReason="time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const exitTs=rows[exitIndex].candle.openTime,rawUnitReturn=exitPrice/entry.open-1,fundingUnitReturn=-fundingBetween(funding,entry.openTime,exitTs),costUnitReturn=-2*costPerSide,netUnitReturn=rawUnitReturn+fundingUnitReturn+costUnitReturn;trades.push({side:"L",signalTs:rows[index].candle.openTime,entryTs:entry.openTime,exitTs,entryPrice:entry.open,exitPrice,requestedGross:V82_NEW_LONG_GROSS,rawUnitReturn,fundingUnitReturn,costUnitReturn,netUnitReturn,accountReturn:V82_NEW_LONG_GROSS*netUnitReturn,exitReason,engineExitReason,entryFeatures:{...features},mfeUnit:mfe,maeUnit:mae});}cooldown=exitIndex+PENGU_DUAL_LS_V2.cooldownHours;index=exitIndex+1;}return trades;}'''
base, count = re.subn(r'function replayV82NewLongSleeve\(rows:PenguDualLsV2EvaluationRow\[\],funding:FundingPoint\[\],mode:Mode\)\{.*?\}\nfunction evaluateV82', new_replay + '\nfunction evaluateV82', base, count=1, flags=re.S)
if count != 1:
    raise SystemExit("V82 replay replacement failed")

new_eval = r'''function evaluateV82(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],baselineV56Normal:RichTrade[]){const derivation=deriveV57Thresholds(baselineV56Normal);v57Thresholds=derivation.thresholds;v64ActiveConfig=V82_FROZEN_V64_CONFIG;const incN=replay(rows,funding,{mode:"normal",longMode:"V64_DYNAMIC"}).trades,incS=replay(rows,funding,{mode:"stress",longMode:"V64_DYNAMIC"}).trades,incNM=metrics(incN),incSM=metrics(incS);assert.equal(incNM.trades,41);assert.equal(incNM.longTrades,13);assert.equal(incNM.shortTrades,28);assert.ok(Math.abs(incNM.returnPct-303.9903920953809)<1e-6);const normal=replayV82NewLongSleeve(rows,funding,"normal"),stress=replayV82NewLongSleeve(rows,funding,"stress"),folds:Array<any>=[];for(let i=0;i<3;i++){const a=V82_FOLD_BOUNDARIES[i],b=V82_FOLD_BOUNDARIES[i+1],n=sliceByTime(normal,a,b),s=sliceByTime(stress,a,b),mn=metrics(n),ms=metrics(s),normalPass=n.length>=V82_MIN_TRADES_PER_FOLD&&mn.returnPct>0&&(mn.profitFactor??999)>=1,stressPass=s.length>=V82_MIN_TRADES_PER_FOLD&&ms.returnPct>0&&(ms.profitFactor??999)>=1;folds.push({fold:i+1,start:new Date(a).toISOString(),end:new Date(b).toISOString(),trades:{normal:n.length,stress:s.length},metrics:{normal:mn,stress:ms},normalPass,stressPass,pass:normalPass&&stressPass});}const allFoldPass=folds.every(x=>x.pass),fmN=metrics(normal),fmS=metrics(stress),robustness={minTotalTrades:12,totalTradesPass:normal.length>=12,normalPfPass:(fmN.profitFactor??999)>=1.25,stressPfPass:(fmS.profitFactor??999)>=1.10,normalDdPass:fmN.maxDrawdownPct>=-12,stressDdPass:fmS.maxDrawdownPct>=-16,normalPositive:fmN.returnPct>0,stressPositive:fmS.returnPct>0};const robustnessPass=Object.entries(robustness).filter(([k])=>k.endsWith("Pass")||k.endsWith("Positive")).every(([,v])=>v===true),strictPass=allFoldPass&&robustnessPass;return{schema:"pengu-v82-independent-long-sleeve/v1",family:"MULTISTAGE_REGIME_PULLBACK_REACCELERATION" as V82Family,frozenV64Config:V82_FROZEN_V64_CONFIG,newLongGross:V82_NEW_LONG_GROSS,materialGainThresholdMultiple:V82_MATERIAL_GAIN_MULTIPLE,incumbent:{normal:incNM,stress:incSM},folds,allFoldPass,fullMetrics:{normal:fmN,stress:fmS},robustness,robustnessPass,strictPass,decision:strictPass?"ADOPT_V82_STANDALONE_CANDIDATE":"KEEP_V64_RESEARCH_CANDIDATE"};}'''
base, count = re.subn(r'function evaluateV82\(rows:PenguDualLsV2EvaluationRow\[\],funding:FundingPoint\[\],baselineV56Normal:RichTrade\[\]\)\{.*?\}\n\'\'\'', new_eval + "\n'''", base, count=1, flags=re.S)
if count != 1:
    raise SystemExit("V82 evaluator replacement failed")

exec(compile(base, "<generated-v82-composite-patch>", "exec"), {"__name__": "__main__"})
