import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

import { PENGU_DUAL_LS_V2 } from "../config/penguDualLsV2Runtime";
import {
  buildPenguDualLsV2EvaluationSeries,
  evaluatePenguDualLsV2PositionBar,
  targetGrossForAtr,
  type PenguDualLsV2History,
  type PenguDualLsV2Position,
  type PenguDualLsV2EvaluationRow,
} from "../lib/pengu-dual-ls-v2";
import type { DisDexV35Candle } from "../lib/disdex-v35-signal-engine";

const HOUR=3_600_000;
const WARM_START=Date.parse("2025-08-01T00:00:00Z");
const EVAL_START=Date.parse("2025-08-23T15:00:00Z");
const EVAL_END=Date.parse("2026-08-23T15:00:00Z");
const BASE_URL="https://fapi.asterdex.com";
const BASE_FEE_PER_SIDE=0.0006, STRESS_SLIPPAGE_PER_SIDE=0.0035;

type Mode="normal"|"stress";
type Side="L"|"S";
type ExitReason="hard"|"trail"|"time"|"baseline_preempt";
type Variant="HARD_STOP_REVERSE"|"HARD_OR_NEG_TIME_REVERSE"|"ALL_NEG_SHORT_REVERSE";
interface FundingPoint{fundingTime:number;fundingRate:number}
interface Trade{kind:"BASELINE"|"RECOVERY";variant?:Variant;side:Side;signalTs:number;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;requestedGross:number;accountReturn:number;netUnitReturn:number;exitReason:ExitReason}

function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function fetchJson(url:URL){let last:unknown;for(let a=0;a<6;a++){try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"DisDex-PENGU-Failure-Reversal/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,200)}`);const j=await r.json();if(!Array.isArray(j))throw new Error("not array");return j as unknown[];}catch(e){last=e;await sleep(400*(a+1));}}throw last;}
async function downloadCandles(symbol:string){const raws:unknown[][]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/klines",BASE_URL);u.searchParams.set("symbol",symbol);u.searchParams.set("interval","1h");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1500");const b=await fetchJson(u) as unknown[][];if(!b.length)break;raws.push(...b);const n=Number(b.at(-1)?.[0])+HOUR;if(!(n>cursor))throw new Error("pagination");cursor=n;await sleep(40);}const m=new Map<number,DisDexV35Candle>();for(const x of raws){const t=Number(x[0]);const c={openTime:t,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),closeTime:Number(x[6]??t+HOUR-1)};if(t>=WARM_START&&t<EVAL_END&&Object.values(c).every(Number.isFinite))m.set(t,c);}return [...m.values()].sort((a,b)=>a.openTime-b.openTime);}
async function downloadFunding(){const out:FundingPoint[]=[];let cursor=WARM_START;while(cursor<EVAL_END){const u=new URL("/fapi/v3/fundingRate",BASE_URL);u.searchParams.set("symbol","PENGUUSDT");u.searchParams.set("startTime",String(cursor));u.searchParams.set("endTime",String(EVAL_END-1));u.searchParams.set("limit","1000");const b=await fetchJson(u) as Array<{fundingTime?:unknown;fundingRate?:unknown}>;if(!b.length)break;for(const x of b){const t=Number(x.fundingTime),r=Number(x.fundingRate);if(t>=WARM_START&&t<EVAL_END&&Number.isFinite(r))out.push({fundingTime:t,fundingRate:r});}const n=Number(b.at(-1)?.fundingTime)+1;if(!(n>cursor))throw new Error("funding pagination");cursor=n;await sleep(40);}return [...new Map(out.map(x=>[x.fundingTime,x])).values()].sort((a,b)=>a.fundingTime-b.fundingTime);}
function fundingBetween(p:FundingPoint[],a:number,b:number){return p.filter(x=>x.fundingTime>a&&x.fundingTime<=b).reduce((s,x)=>s+x.fundingRate,0);}

function replayBaseline(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],mode:Mode){const trades:Trade[]=[];const cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0);let i=250,cooldown=-1;while(i<rows.length-2){if(i<=cooldown){i++;continue;}const side:Side|undefined=rows[i].shortSignal?"S":rows[i].longSignal?"L":undefined;if(!side||!rows[i].features){i++;continue;}const ei=i+1,entry=rows[ei].candle,gross=targetGrossForAtr(rows[i].features!.atr24Ratio);let pos:PenguDualLsV2Position={side:side==="L"?1:-1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross,highWaterMark:entry.open,lowWaterMark:entry.open};const hold=side==="L"?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,ei+hold-1);let xi=last,xp=rows[last].candle.close,reason:ExitReason="time";for(let c=ei;c<=last;c++){const f=rows[c].features;assert(f);const ev=evaluatePenguDualLsV2PositionBar(pos,f);pos=ev.updatedPosition;if(ev.exit){xi=c;xp=ev.exit.stopPrice??rows[c].candle.close;reason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}if(entry.openTime>=EVAL_START&&entry.openTime<EVAL_END){const xt=rows[xi].candle.openTime,raw=side==="L"?xp/entry.open-1:entry.open/xp-1,fr=fundingBetween(funding,entry.openTime,xt),fundRet=side==="L"?-fr:fr,net=raw+fundRet-2*cps;trades.push({kind:"BASELINE",side,signalTs:rows[i].candle.openTime,entryTs:entry.openTime,exitTs:xt,entryPrice:entry.open,exitPrice:xp,requestedGross:gross,accountReturn:gross*net,netUnitReturn:net,exitReason:reason});}cooldown=xi+PENGU_DUAL_LS_V2.cooldownHours;i=xi+1;}return trades;}
function triggerRecovery(t:Trade,v:Variant){if(t.side!=="S")return false;if(v==="HARD_STOP_REVERSE")return t.exitReason==="hard";if(v==="HARD_OR_NEG_TIME_REVERSE")return t.exitReason==="hard"||(t.exitReason==="time"&&t.accountReturn<0);return t.accountReturn<0;}
function nextBaselineEntry(trades:Trade[],ts:number){return trades.find(t=>t.entryTs>ts)?.entryTs;}
function replayRecoveries(rows:PenguDualLsV2EvaluationRow[],funding:FundingPoint[],baseline:Trade[],variant:Variant,mode:Mode){const cps=BASE_FEE_PER_SIDE+(mode==="stress"?STRESS_SLIPPAGE_PER_SIDE:0),byTs=new Map(rows.map((r,i)=>[r.candle.openTime,i])),out:Trade[]=[];let busyUntil=-1;for(const t of baseline){if(!triggerRecovery(t,variant))continue;const exitIndex=byTs.get(t.exitTs);if(exitIndex===undefined||exitIndex+1>=rows.length)continue;const ei=exitIndex+1,entry=rows[ei].candle;if(entry.openTime<EVAL_START||entry.openTime>=EVAL_END||entry.openTime<busyUntil)continue;const f0=rows[ei].features??rows[exitIndex].features;if(!f0)continue;const gross=targetGrossForAtr(f0.atr24Ratio);let pos:PenguDualLsV2Position={side:1,entryTs:entry.openTime,entryPrice:entry.open,quantity:1,gross,highWaterMark:entry.open,lowWaterMark:entry.open};const last=Math.min(rows.length-1,ei+PENGU_DUAL_LS_V2.long.maxHoldHours-1);let xi=last,xp=rows[last].candle.close,reason:ExitReason="time";for(let c=ei;c<=last;c++){const f=rows[c].features;if(!f)continue;const ev=evaluatePenguDualLsV2PositionBar(pos,f);pos=ev.updatedPosition;if(ev.exit){xi=c;xp=ev.exit.stopPrice??rows[c].candle.close;reason=ev.exit.reason.includes("HARD")?"hard":ev.exit.reason.includes("TRAILING")?"trail":"time";break;}}
    const nextBase=nextBaselineEntry(baseline,entry.openTime);if(nextBase!==undefined&&nextBase<rows[xi].candle.openTime){const pi=byTs.get(nextBase);assert(pi!==undefined);xi=pi;xp=rows[pi].candle.open;reason="baseline_preempt";}
    const xt=rows[xi].candle.openTime,raw=xp/entry.open-1,fr=fundingBetween(funding,entry.openTime,xt),net=raw-fr-2*cps;out.push({kind:"RECOVERY",variant,side:"L",signalTs:t.exitTs,entryTs:entry.openTime,exitTs:xt,entryPrice:entry.open,exitPrice:xp,requestedGross:gross,accountReturn:gross*net,netUnitReturn:net,exitReason:reason});busyUntil=xt;}return out;}
function metrics(ts:Trade[]){let eq=1,peak=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{trades:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?ts.filter(t=>t.accountReturn>0).length/ts.length*100:null,profitFactor:gl>0?gp/gl:null,maxDrawdownPct:dd*100,hardStops:ts.filter(t=>t.exitReason==="hard").length,preempts:ts.filter(t=>t.exitReason==="baseline_preempt").length};}
function foldName(ts:number){const a=Date.parse("2025-12-23T15:00:00Z"),b=Date.parse("2026-04-23T15:00:00Z");return ts<a?"EARLY":ts<b?"MID":"LATE";}
function summarize(base:Trade[],recovery:Trade[]){const folds:any={};for(const n of ["EARLY","MID","LATE"])folds[n]=metrics(recovery.filter(t=>foldName(t.entryTs)===n));return{BASELINE:metrics(base),RECOVERY:metrics(recovery),COMBINED:metrics([...base,...recovery]),RECOVERY_FOLDS:folds,baselineTradesPreserved:base.length};}

async function main(){const [pengu,btc,funding]=await Promise.all([downloadCandles("PENGUUSDT"),downloadCandles("BTCUSDT"),downloadFunding()]);const expected=Math.floor((EVAL_END-EVAL_START)/HOUR);assert.equal(pengu.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);assert.equal(btc.filter(x=>x.openTime>=EVAL_START&&x.openTime<EVAL_END).length,expected);const pTs=new Set(pengu.map(x=>x.openTime)),aligned=btc.filter(x=>pTs.has(x.openTime));assert.equal(aligned.length,pengu.length);const history:PenguDualLsV2History={pengu1h:pengu,btc1h:aligned,penguFunding:funding},rows=buildPenguDualLsV2EvaluationSeries(history,EVAL_END+HOUR),variants:Variant[]=["HARD_STOP_REVERSE","HARD_OR_NEG_TIME_REVERSE","ALL_NEG_SHORT_REVERSE"];const out:any={status:"PASS_RESEARCH_ONLY",schema:"pengu-short-failure-reversal/v1",period:{startInclusive:new Date(EVAL_START).toISOString(),endExclusive:new Date(EVAL_END).toISOString()},design:{principle:"do not filter or alter any current PENGU trade; after an observed failed short, add a long recovery trade on the next H1 open",recoveryExit:"current production PENGU long exit engine; baseline entry always preempts recovery"},results:{},promotion:{},safety:{mode:"RESEARCH_ONLY",ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};for(const mode of ["normal","stress"] as Mode[]){const base=replayBaseline(rows,funding,mode);assert.equal(base.length,32);if(mode==="normal"){assert.equal(base.filter(t=>t.side==="S").length,25);assert.equal(base.filter(t=>t.side==="S"&&t.exitReason==="hard").length,6);}for(const v of variants){const rec=replayRecoveries(rows,funding,base,v,mode);out.results[v]??={};out.results[v][mode.toUpperCase()]=summarize(base,rec);}}
  for(const v of variants){const n=out.results[v].NORMAL,s=out.results[v].STRESS,b=n.BASELINE,bs=s.BASELINE,r=n.RECOVERY,c=n.COMBINED,folds=["EARLY","MID","LATE"].filter(k=>n.RECOVERY_FOLDS[k].trades>0).length;const pass=n.baselineTradesPreserved===32&&r.trades>=5&&(r.winRatePct??0)>=70&&c.winRatePct>=(b.winRatePct??0)+5&&c.returnPct>=b.returnPct&&(c.profitFactor??0)>=(b.profitFactor??0)&&c.maxDrawdownPct>=b.maxDrawdownPct&&s.COMBINED.returnPct>=bs.returnPct&&(s.COMBINED.profitFactor??0)>=(bs.profitFactor??0)&&folds>=2;out.promotion[v]={pass,addedTrades:r.trades,recoveryWinRatePct:r.winRatePct,recoveryReturnPct:r.returnPct,recoveryPF:r.profitFactor,combinedWinRatePct:c.winRatePct,combinedReturnPct:c.returnPct,foldsWithRecovery:folds};}
  const outPath=process.env.PENGU_FAILURE_REVERSAL_OUT||".research-state/pengu-failure-reversal/result.json";await fs.mkdir(path.dirname(outPath),{recursive:true});await fs.writeFile(outPath,JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
