import assert from "node:assert/strict";
import fs from "node:fs/promises";import path from "node:path";
import {PENGU_DUAL_LS_V2} from "../config/penguDualLsV2Runtime";
import {buildPenguDualLsV2EvaluationSeries,evaluatePenguDualLsV2PositionBar,targetGrossForAtr,type PenguDualLsV2History,type PenguDualLsV2Position,type PenguDualLsV2EvaluationRow} from "../lib/pengu-dual-ls-v2";
import type {DisDexV35Candle} from "../lib/disdex-v35-signal-engine";
const HOUR=3_600_000,WARM_START=Date.parse(process.env.PENGU_V9_WARM_START||"2025-08-01T00:00:00Z"),EVAL_START=Date.parse(process.env.PENGU_V9_EVAL_START||"2025-08-23T15:00:00Z"),EVAL_END=Date.parse(process.env.PENGU_V9_EVAL_END||"2026-08-23T15:00:00Z"),BASE_URL=process.env.PENGU_V9_BASE_URL||"https://fapi.asterdex.com",LOCAL=process.env.PENGU_V9_LOCAL_DATA_DIR||"",FEE=.0006,SLIP=.0035;
type Mode="normal"|"stress";type Side="L"|"S";interface FundingPoint{fundingTime:number;fundingRate:number}interface Trade{side:Side;entryTs:number;exitTs:number;entryPrice:number;exitPrice:number;requestedGross:number;accountReturn:number;netUnitReturn:number;entryAtr24Ratio:number;partialTriggered?:boolean;partialTs?:number}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}async function fj(u:URL){let e:unknown;for(let a=0;a<6;a++){try{const r=await fetch(u,{headers:{accept:"application/json","user-agent":"DisDex-V9/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(!Array.isArray(j))throw new Error("array");return j as unknown[];}catch(x){e=x;await sleep(400*(a+1));}}throw e;}
async function candles(sym:string){if(LOCAL){const r=JSON.parse(await fs.readFile(path.join(LOCAL,`${sym}.json`),"utf8")) as DisDexV35Candle[];return r.filter(x=>x.openTime>=WARM_START&&x.openTime<EVAL_END);}const raw:unknown[][]=[];let c=WARM_START;while(c<EVAL_END){const u=new URL('/fapi/v3/klines',BASE_URL);for(const [k,v] of [['symbol',sym],['interval','1h'],['startTime',String(c)],['endTime',String(EVAL_END-1)],['limit','1500']])u.searchParams.set(k,v);const b=await fj(u) as unknown[][];if(!b.length)break;raw.push(...b);const n=Number(b.at(-1)?.[0])+HOUR;if(n<=c)throw new Error('page');c=n;}const m=new Map<number,DisDexV35Candle>();for(const x of raw){const t=Number(x[0]),v={openTime:t,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),closeTime:Number(x[6]??t+HOUR-1)};if(t>=WARM_START&&t<EVAL_END)m.set(t,v);}return [...m.values()].sort((a,b)=>a.openTime-b.openTime);}
async function funding(){if(LOCAL){const r=JSON.parse(await fs.readFile(path.join(LOCAL,'PENGUUSDT-funding.json'),'utf8')) as FundingPoint[];return r.filter(x=>x.fundingTime>=WARM_START&&x.fundingTime<EVAL_END);}const o:FundingPoint[]=[];let c=WARM_START;while(c<EVAL_END){const u=new URL('/fapi/v3/fundingRate',BASE_URL);u.searchParams.set('symbol','PENGUUSDT');u.searchParams.set('startTime',String(c));u.searchParams.set('endTime',String(EVAL_END-1));u.searchParams.set('limit','1000');const b=await fj(u) as any[];if(!b.length)break;for(const x of b){const t=Number(x.fundingTime),r=Number(x.fundingRate);if(Number.isFinite(r))o.push({fundingTime:t,fundingRate:r});}c=Number(b.at(-1)?.fundingTime)+1;}return [...new Map(o.map(x=>[x.fundingTime,x])).values()].sort((a,b)=>a.fundingTime-b.fundingTime);}
const fb=(p:FundingPoint[],a:number,b:number)=>p.filter(x=>x.fundingTime>a&&x.fundingTime<=b).reduce((s,x)=>s+x.fundingRate,0);
function baseline(rows:PenguDualLsV2EvaluationRow[],fund:FundingPoint[],mode:Mode){const out:Trade[]=[];const cps=FEE+(mode==='stress'?SLIP:0);let i=250,cd=-1;while(i<rows.length-2){if(i<=cd){i++;continue;}const side:Side|undefined=rows[i].shortSignal?'S':rows[i].longSignal?'L':undefined,f=rows[i].features;if(!side||!f){i++;continue;}const ei=i+1,e=rows[ei].candle,g=targetGrossForAtr(f.atr24Ratio);let p:PenguDualLsV2Position={side:side==='L'?1:-1,entryTs:e.openTime,entryPrice:e.open,quantity:1,gross:g,highWaterMark:e.open,lowWaterMark:e.open};const hold=side==='L'?PENGU_DUAL_LS_V2.long.maxHoldHours:PENGU_DUAL_LS_V2.short.maxHoldHours,last=Math.min(rows.length-1,ei+hold-1);let xi=last,xp=rows[last].candle.close;for(let j=ei;j<=last;j++){const ff=rows[j].features;assert(ff);const ev=evaluatePenguDualLsV2PositionBar(p,ff);p=ev.updatedPosition;if(ev.exit){xi=j;xp=ev.exit.stopPrice??rows[j].candle.close;break;}}if(e.openTime>=EVAL_START&&e.openTime<EVAL_END){const xt=rows[xi].candle.openTime,raw=side==='L'?xp/e.open-1:e.open/xp-1,fr=fb(fund,e.openTime,xt),net=raw+(side==='L'?-fr:fr)-2*cps;out.push({side,entryTs:e.openTime,exitTs:xt,entryPrice:e.open,exitPrice:xp,requestedGross:g,accountReturn:g*net,netUnitReturn:net,entryAtr24Ratio:f.atr24Ratio});}cd=xi+PENGU_DUAL_LS_V2.cooldownHours;i=xi+1;}return out;}
function metrics(ts:Trade[]){let eq=1,pk=1,dd=0,gp=0,gl=0;for(const t of [...ts].sort((a,b)=>a.exitTs-b.exitTs)){eq*=1+t.accountReturn;pk=Math.max(pk,eq);dd=Math.min(dd,eq/pk-1);if(t.accountReturn>0)gp+=t.accountReturn;else gl-=t.accountReturn;}return{trades:ts.length,wins:ts.filter(t=>t.accountReturn>0).length,returnPct:(eq-1)*100,winRatePct:ts.length?ts.filter(t=>t.accountReturn>0).length/ts.length*100:null,profitFactor:gl?gp/gl:null,maxDrawdownPct:dd*100,partialTriggers:ts.filter(t=>t.partialTriggered).length};}
function partial(t:Trade,rows:PenguDualLsV2EvaluationRow[],fund:FundingPoint[],mode:Mode,by:Map<number,number>){const ei=by.get(t.entryTs),xi=by.get(t.exitTs);assert(ei!==undefined&&xi!==undefined);const unit=Math.min(t.entryAtr24Ratio,PENGU_DUAL_LS_V2.short.hardStopPct/2),arm=unit,goal=Math.min(2*unit,PENGU_DUAL_LS_V2.short.hardStopPct),exit=.5*unit,cps=FEE+(mode==='stress'?SLIP:0);let armed=false,progress=false,lw=t.entryPrice;for(let i=ei;i<xi;i++){const b=rows[i].candle;lw=Math.min(lw,b.low);const mfe=1-lw/t.entryPrice;if(!armed&&!progress&&mfe>=arm)armed=true;if(armed&&mfe>=goal){progress=true;armed=false;}if(armed&&!progress&&(1-b.close/t.entryPrice)<=exit&&i+1<=xi){const x=rows[i+1].candle,raw1=t.entryPrice/x.open-1,fr1=fb(fund,t.entryTs,x.openTime),net1=raw1+fr1-2*cps,net=.5*net1+.5*t.netUnitReturn;return{...t,accountReturn:t.requestedGross*net,netUnitReturn:net,partialTriggered:true,partialTs:x.openTime};}}return t;}
function fold(ts:number){const q=(ts-EVAL_START)/(EVAL_END-EVAL_START);return q<.25?'Q1':q<.5?'Q2':q<.75?'Q3':'Q4';}function wob(b:Trade[],c:Trade[]){const d=c.map((t,i)=>t.accountReturn-b[i].accountReturn);let bi=0;for(let i=1;i<d.length;i++)if(d[i]>d[bi])bi=i;const bm=metrics(b.filter((_,i)=>i!==bi)),cm=metrics(c.filter((_,i)=>i!==bi));return{returnDeltaPct:cm.returnPct-bm.returnPct,removedBestDelta:d[bi]};}
async function main(){const [p,b,f]=await Promise.all([candles('PENGUUSDT'),candles('BTCUSDT'),funding()]);const ps=new Set(p.map(x=>x.openTime)),ba=b.filter(x=>ps.has(x.openTime));assert.equal(ba.length,p.length);const rows=buildPenguDualLsV2EvaluationSeries({pengu1h:p,btc1h:ba,penguFunding:f} as PenguDualLsV2History,EVAL_END+HOUR),by=new Map(rows.map((r,i)=>[r.candle.openTime,i])),out:any={status:'PASS_RESEARCH_ONLY',schema:'pengu-short-partial-v9/v1',design:{candidate:'ATR_PROGRESS_HALF_DERISK',candidateCount:1,split:'50/50 fixed',thresholdSweep:false,entriesChanged:false},results:{},safety:{mode:'RESEARCH_ONLY',ordersSent:false,liveChanged:false,vpsChanged:false,productionChanged:false}};for(const mode of ['normal','stress'] as Mode[]){const base=baseline(rows,f,mode),s=base.filter(t=>t.side==='S'),l=base.filter(t=>t.side==='L'),c=s.map(t=>partial(t,rows,f,mode,by)),all=[...l,...c],folds:any={};for(const k of ['Q1','Q2','Q3','Q4'])folds[k]={baseline:metrics(s.filter(t=>fold(t.entryTs)===k)),candidate:metrics(c.filter(t=>fold(t.entryTs)===k))};out.results[mode.toUpperCase()]={BASELINE:metrics(base),BASELINE_SHORT:metrics(s),CANDIDATE_SHORT:metrics(c),COMBINED:metrics(all),SHORT_FOLDS:folds,changedExits:c.filter(t=>t.partialTriggered).length,withoutBestImprovement:wob(s,c)};}const op=process.env.PENGU_V9_OUT||'.research-state/pengu-short-partial-v9/result.json';await fs.mkdir(path.dirname(op),{recursive:true});await fs.writeFile(op,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));}main().catch(e=>{console.error(e);process.exitCode=1;});
