import type { PolymarketSnapshot } from "./types";

export const samplePolymarketSnapshots: PolymarketSnapshot[] = [
  {
    snapshotIso: "2026-06-28T12:00:00Z",
    source: "mock-rule-engine",
    markets: [
      {
        marketId: "sample-entry-001",
        title: "Will a major company announce an AI partnership by June 30?",
        category: "business",
        deadlineIso: "2026-06-30T23:59:59Z",
        currentYesPrice: 0.42,
        currentNoPrice: 0.58,
        recommendedSide: "YES",
        estimatedProbability: 0.64,
        edge: 0.22,
        expectedReturn: 0.52,
        liquidityUsd: 32000,
        spread: 0.02,
        volume24h: 16000,
        evidenceStrength: 0.9,
        sourceCount: 8,
        primarySources: true,
        xSignalStrength: 0.82,
        newsSignalStrength: 0.88,
        ruleClarity: 0.91,
        resolutionRisk: "low",
        negativeNews: false,
        strongOpposition: false,
        liquidityOk: true,
        actualResolutionSide: "YES",
        finalYesPrice: 1,
        finalNoPrice: 0,
        maxYesPriceAfterEntry: 0.62,
        minYesPriceAfterEntry: 0.39,
        notes: ["Primary source supports YES", "Market price appears behind latest information"]
      },
      {
        marketId: "sample-watch-001",
        title: "Will a politician file by the deadline?",
        category: "politics",
        deadlineIso: "2026-07-05T23:59:59Z",
        currentYesPrice: 0.55,
        currentNoPrice: 0.45,
        recommendedSide: "YES",
        estimatedProbability: 0.66,
        edge: 0.11,
        expectedReturn: 0.2,
        liquidityUsd: 7000,
        spread: 0.05,
        volume24h: 2500,
        evidenceStrength: 0.62,
        sourceCount: 3,
        primarySources: false,
        xSignalStrength: 0.56,
        newsSignalStrength: 0.61,
        ruleClarity: 0.8,
        resolutionRisk: "medium",
        negativeNews: false,
        strongOpposition: false,
        liquidityOk: true,
        complexRules: true,
        finalYesPrice: 0.64,
        finalNoPrice: 0.36,
        maxYesPriceAfterEntry: 0.69,
        minYesPriceAfterEntry: 0.5,
        notes: ["Needs review because filing rules are not simple"]
      },
      {
        marketId: "sample-reject-001",
        title: "Will a rumor be confirmed today?",
        category: "news",
        deadlineIso: "2026-06-29T23:59:59Z",
        currentYesPrice: 0.72,
        currentNoPrice: 0.28,
        recommendedSide: "YES",
        estimatedProbability: 0.76,
        edge: 0.04,
        expectedReturn: 0.06,
        liquidityUsd: 5000,
        spread: 0.04,
        volume24h: 1800,
        evidenceStrength: 0.45,
        sourceCount: 2,
        primarySources: false,
        xSignalStrength: 0.48,
        newsSignalStrength: 0.42,
        ruleClarity: 0.72,
        resolutionRisk: "medium",
        negativeNews: false,
        strongOpposition: false,
        liquidityOk: true,
        notes: ["Edge is too small"]
      },
      {
        marketId: "sample-force-reject-001",
        title: "Will an ambiguous event resolve YES?",
        category: "other",
        deadlineIso: "2026-07-01T23:59:59Z",
        currentYesPrice: 0.33,
        currentNoPrice: 0.67,
        recommendedSide: "YES",
        estimatedProbability: 0.59,
        edge: 0.26,
        expectedReturn: 0.79,
        liquidityUsd: 22000,
        spread: 0.02,
        volume24h: 9000,
        evidenceStrength: 0.88,
        sourceCount: 7,
        primarySources: true,
        xSignalStrength: 0.75,
        newsSignalStrength: 0.84,
        ruleClarity: 0.35,
        resolutionRisk: "high",
        negativeNews: false,
        strongOpposition: false,
        liquidityOk: true,
        notes: ["High resolution risk must force reject"]
      }
    ]
  }
];
